### ISSUE TITLE
"Atom.jl: unrecognised message loadgallium." when trying to set breakpoint

### ISSUE THREAD

**Issue by xximranxx** [JunoLab/Juno.jl#100]
Whether I try to set the breakpoint via ^x or right-click, I get this error in the REPL
This is using julia 0.6.2 and Juno 0.4.0 and Atom 1.23.3 (all packages up-to-date)

So at the moment, I cannot seem to set breakpoints at all

**Comment by pfitzseb** [comment]
Breakpoints are not supported at all at the moment, so I've disabled them for now in https://github.com/JunoLab/atom-julia-client/commit/7f27e2e6eb7a6282e9f67464723987e0aebd781d.
