### ISSUE TITLE
Background instance of Julia in cycler boot mode waits with loading of junorc.jl

### ISSUE THREAD

**Issue by TsurHerman** [JunoLab/Juno.jl#101]
Before the latest update I had several heavy packages loaded and worked-out a little bit in 
junorc.jl , so whenever I had to kill the current instance and switch to the background one ,I would get 
an instance with all the heavy lifting already done , and thus no more waiting for modules to load.

After the latest update , it seems that
Working directory is set correctly to be the current working directory in junorc.jl which is a 
long lasting bug finally fixed.

However the loading of junorc.jl is delayed until the background instance is made live

**Comment by pfitzseb** [comment]
Yes, this is by design (see http://docs.junolab.org/latest/man/faq.html#How-do-I-execute-code-on-Juno-startup?-1 and https://github.com/JunoLab/atom-julia-client/pull/410).

The idea is that you could load these packages in `.juliarc.jl` and use `.junorc.jl` only for code that queries the frontend etc.

**Comment by TsurHerman** [comment]
I see, yes that would make sense ...

**Comment by TsurHerman** [comment]
It would give an overall more consolidated experience whether working from Atom or directly in REPL

**Comment by TsurHerman** [comment]
Mark as closed then , thanks and good work as always.

**Comment by pfitzseb** [comment]
Alright -- I wasn't sure if this is the right decision :)

**Comment by TsurHerman** [comment]
I find that I like the legacy console much more, as it gives a nice rendering to custom types.
And in that sense I prefer .junorc.jl to preload , and thus leaving the regular Julia REPL fast and nimble 
for when I do updates or package creation etc , or just to "test" something quickly
