### ISSUE TITLE
Buttons for interrupt/stop julia in REPL console

### ISSUE THREAD

**Issue by stakaz** [JunoLab/Juno.jl#105]
Is it planed to reintroduce the toolbar of the console? I really miss the interrupt/stop julia buttons in the new REPL console look.

**Comment by pfitzseb** [comment]
No, not really. You can just use the global toolbar though.

**Comment by pfitzseb** [comment]
I've added a "Interrupt Julia" button to the toolbar:
![grafik](https://user-images.githubusercontent.com/6735977/35682031-a3323bc6-075f-11e8-851f-7e275ecf5b11.png)
