### ISSUE TITLE
Errors not shown in REPL

### ISSUE THREAD

**Issue by stakaz** [JunoLab/Juno.jl#108]
Hello, I have a further problem with the new REPL console. Sometimes the errors are not shown in the console but the code does not run completely. So I have no hints where the bug is. Same code in normal julia REPL (outside atom) gives an error.

```julia
ERROR: LoadError: UndefVarError: L not defined
Stacktrace:
 [1] anonymous at ./<missing>:?
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] process_options(::Base.JLOptions) at ./client.jl:305
 [5] _start() at ./client.jl:371
while loading 
...
```
This should not be the case, I think.

**Comment by pfitzseb** [comment]
Does this happen when evaluating something in the REPL or when evaling something in an editor?

**Comment by stakaz** [comment]
This happens when evaluating from the editor.

**Comment by pfitzseb** [comment]
Hm, can you describe what you're doing exactly?

**Comment by stakaz** [comment]
It is really easy to reproduce:
This code run in atom without an error message 
```julia
f(x) = y + 2
f(1)
```

While in an external julia REPL it roduces the right error:
```julia
julia> f(x) = y + 2
f (generic function with 1 method)

julia> f(1)
ERROR: UndefVarError: y not defined
Stacktrace:
 [1] f(::Int64) at ./REPL[1]:1
```

**Comment by pfitzseb** [comment]
Ah I see now, will fix. This is only relevant when running a complete file instead of running that code line-by-line.
For now, there's a setting called "Error Notifications" that displays those errors as a pop up in Atom.

**Comment by stakaz** [comment]
Thanks. I will turn the notifications on until the fix arrives.

**Comment by pfitzseb** [comment]
Should be fixed with the latest version of Atom.jl.
