### ISSUE TITLE
New terminal with git bash does not open in a pane, but outside of the editor

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JunoLab/Juno.jl#111]
I set Shell to C:\Program Files\Git\git-bash.exe . The terminal opens in an outside window, not inside the editor.

**Comment by pfitzseb** [comment]
`C:\Program Files\Git\bin\sh.exe` works for me.

IIUC it's the point of `git-bash.exe` to open a new terminal to work around the somewhat annyoing windows console, so that behaviour makes sense.

**Comment by PetrKryslUCSD** [comment]
It is true: C:\Program Files\Git\bin\bash.exe works fine. I chose the wrong program to run in the terminal.
