### ISSUE TITLE
Console number of stored lines

### ISSUE THREAD

**Issue by stakaz** [JunoLab/Juno.jl#112]
Hello, it would be great to have on option to choose the number of saved lines in the console.
The current number is not suitable for a long work on an analysis as older results get deleted in the output.

Thanks.

**Comment by pfitzseb** [comment]
Doesn't this work for you? 
![grafik](https://user-images.githubusercontent.com/6735977/35912284-6cd888b8-0bfc-11e8-859b-be34fb76fb6d.png)
(Can be found under Settings > Packages > julia-client)

**Comment by stakaz** [comment]
My fault, I have overseen it and thought that the option was gone due to the new console. Works as expected.
