### ISSUE TITLE
A toggle between opening a function with (1) a new tab and (2) within the current one when stepping in

### ISSUE THREAD

**Issue by kuanxu** [JunoLab/Juno.jl#114]
Currently, when stepping into a function which is not contained in the file opened by the current tab, the stepped-in file is opened in the same tab, replacing the file where the function is called. This keeps the number of the tabs unchanged, avoiding being flooded by new tabs.

However, sometimes it's desired to open a file in a new tab when stepping into it and at the same time keep the tab of the file which the debugger just left (with the bug symbol travels with the debugger to the newly-opened tab, indicating the location of the current debugger). This way, one can always look around and check a few files of successive levels simultaneously. This is exactly what Matlab does (VS does too, iirc). 

It would be great if a toggle for switching between these two modes can be made available.

**Comment by pfitzseb** [comment]
Alright, if you insist :)

**Comment by kuanxu** [comment]
Thanks, buddy. This is ever my shortest-lived ticket. ;) You're lightening fast!
