### ISSUE TITLE
readline() woes

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/Juno.jl#118]
When evaluating `readline` in the editor input is wonky -- you need to type a newline before the input you want to pass to `readline`.

**Comment by banbh** [comment]
I see this too (Win 10; julia-client 0.8.12-beta2). After hitting Ctrl-Enter on a line with `readline()` I need to switch to the REPL, type something (e.g., "1"), hit Enter, then my input, then Enter. Whatever I typed first gets evaluated (hence a space or the digit 1). Simply starting with a newline did not work.
