### ISSUE TITLE
Debugging hotkeys enabled all the time

### ISSUE THREAD

**Issue by kuanxu** [JunoLab/Juno.jl#120]
Current, if the cursor is with the REPL window, one has to manually click the Juno editor using the mouse or the touchpad to return to the editor and hence be able to command the debugger through the hotkeys again. This significantly drags the speed of debugging work. 

It'll be vastly beneficial to have the hotkeys, e.g. F10 and F11, still enabled when the cursor is at the REPL. This can bring uninterrupted and seamless debugging experience.

**Comment by aviatesk** [comment]
Now we can set those keybindings within REPL with `whitelistedKeybindings` config and the custom keymaps.
