### ISSUE TITLE
plot does not appear unless pane is on top

### ISSUE THREAD

**Issue by bjarthur** [JunoLab/Juno.jl#121]
my atom window is configured such that the plot and workspace pages share the same physical space on the screen (is this called a "pane"?) and i switch back and forth between the two by clicking on the tabs at the top.  in a separate pane is the REPL.  if the workspace tab is active, and hence the plot panel is not, then plots generated in the REPL do not appear, even when afterwards i switch to the plot pane.  a bug, right?

**Comment by pfitzseb** [comment]
Are you using Plots.jl? I can't reproduce this with `using Plots; gr(); plot([1,2,3])`, although the plot size is wrong if the plot pane is not focused.

**Comment by pfitzseb** [comment]
And that sizing issue should be fixed with https://github.com/JunoLab/atom-julia-client/commit/401581a0384099c12537b596903a4755e069e4a2. There's also a chance it fixes your issue :)

**Comment by bjarthur** [comment]
works now.  thanks!
