### ISSUE TITLE
Does Juno work with 0.7 DEV build?

### ISSUE THREAD

**Issue by nickeubank** [JunoLab/Juno.jl#129]
I can't seem to get Juno working with a 0.7 DEV build of Julia. It was working fine with 0.6.2. 

I changed my Julia Path in `julia-client` package to `/Applications/Julia-0.7.app/Contents/Resources/julia/bin/julia` (which works if entered into terminal), and in Julia ran `Pkg.add("Atom")`. 

But when I start a session, I get:

```

Julia has exited. Press Enter to start a new session.
Starting Julia...
ERROR: LoadError: UndefVarError: find_in_path not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at /Users/Nick/.atom/packages/julia-client/script/boot_repl.jl:3
 [3] include at ./boot.jl:306 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1067
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] exec_options(::Base.JLOptions) at ./client.jl:327
 [7] _start() at ./client.jl:455
in expression starting at /Users/Nick/.atom/packages/julia-client/script/boot_repl.jl:3
```

Is julia 0.7 supported / is there something else I'm supposed to be doing?

**Comment by pfitzseb** [comment]
The latest release does not support 0.7. See #127 for progress (and a list of branches you need to check out).

**Comment by MikeInnes** [comment]
I just set this up on a new machine; setup is pretty straightforward if you're happy checking out the branches. Otherwise, I'm sure we'll get this working properly as soon as the alpha is out.
