### ISSUE TITLE
Progress macro does nothing if Juno is not loaded

### ISSUE THREAD

**Issue by MikeInnes** [JunoLab/Juno.jl#131]
```
julia> using Juno, MacroTools

julia> @expand @progress for i = 1:10 sleep(1) end
:(for i = 1:10 # REPL[3], line 1:
        sleep(1)
    end)
```

I don't know when this changed, but this should lower to code that does the right thing when Juno is loaded (presumably the lower level progress API should work and just be a no-op). Otherwise, `@progress` cannot be used inside packages.

**Comment by pfitzseb** [comment]
That changed in https://github.com/JunoLab/Juno.jl/pull/95.

We'd need to change [this](https://github.com/JunoLab/Juno.jl/blob/d978c5ff3d471dffadb686a4960a9460a2afef6f/src/progress.jl#L90-L96) to something like
```julia
function _progress(name, ex)
  quote
    if isactive()
      Atom.Progress._progress($name, $(esc(ex)))
    else
      $(esc(ex))
    end
  end
end
```
but I'm not sure how to pass `$(esc(ex))` as an expression to `Atom.Progress._progress`.

**Comment by MikeInnes** [comment]
I think you want

```julia
function _progress(name, ex)
  quote
    if isactive()
      $(Atom.Progress._progress(name, ex))
    else
      $(esc(ex))
    end
  end
end
```

**Comment by pfitzseb** [comment]
That's problematic because of 
```
julia> @progress for i = 1:10 sleep(1) end
ERROR: UndefVarError: Atom not defined
```
when Atom isn't loaded as well...

**Comment by MikeInnes** [comment]
Is there are particular reason for the macro expansion to be in Atom though? It seems like it's just lowering straight to the API defined in Juno anyway, right?

**Comment by pfitzseb** [comment]
IIRC that's to avoid having Juno.jl depend on MacroTools (used [here](https://github.com/JunoLab/Atom.jl/blob/2dc7bcc088d24541a9e3f7affa9eb91b0ed5e2e3/src/progress.jl#L97-L99)).

**Comment by pfitzseb** [comment]
"Fixed" with https://github.com/JunoLab/Juno.jl/commit/40dc6765e9bb1e3e73af12d42cc88f2e5e9e08bd.

**Comment by pfitzseb** [comment]
Actually fixed in latest Juno.jl/Atom.jl release.
