### ISSUE TITLE
Custom inline override no longer works

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/Juno.jl#134]
My custom inline override no longer works: 
```julia
Juno.render(i::Juno.Inline, f::Fun) = string(f)
```
It now doesn't display anything inline.

**Comment by pfitzseb** [comment]
IIRC that's fixed with https://github.com/JunoLab/atom-ink/commit/ce0fdf0454cf3914f536ab61163979037ea86d78.

**Comment by dlfivefifty** [comment]
It now only displays the standard `render(::Inline, ::Function)` display, not my override.

**Comment by pfitzseb** [comment]
It looks like this for me:
![grafik](https://user-images.githubusercontent.com/6735977/40199354-73d85dc6-5a19-11e8-90ac-0c24dfc71dee.png)
