### ISSUE TITLE
REPL console does not report source file location of julia exceptions;  no stacktrace

### ISSUE THREAD

**Issue by mattcbro** [JunoLab/Juno.jl#135]
The console in the atom/Juno window behaves differently from a pure julia session in bash.  It fails to show where in the source file an error actually occurs.

Here is an example from something I ran recently:
Juno console:
julia> include("calsim.jl")
Calibration gain error = -74.77519048362441 dB
ERROR: LoadError: ArgumentError: squeezed dims must all be size 1
while loading /data/projects/Maestro/calsim.jl, in expression starting on line 102

From a normal julia session launched from bash:
julia> include("calsim.jl")
Calibration gain error = -70.78762965234019 dB 
ERROR: LoadError: ArgumentError: squeezed dims must all be size 1
Stacktrace:
 [1] squeeze(::Array{Float64,2}, ::Tuple{Int64}) at ./abstractarraymath.jl:70
 [2] learnantpos(::Array{Complex{Float64},3}, ::Array{Float64,2}, ::Algo_Chan.ChanPrams, ::GeoAlgos.AlgoPrams) at /data/projects/Maestro/GeoAlgos.jl:187
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
while loading /data/projects/Maestro/calsim.jl, in expression starting on line 102

The Juno sessions does not include the stacktrace and hence the source information needed to track down the bug.

**Comment by pfitzseb** [comment]
This is fixed on master (and in the next release, which should hopefully be out today).
