### ISSUE TITLE
Simple entering of Greek characters

### ISSUE THREAD

**Issue by lwhitefox** [JunoLab/Juno.jl#140]
Coming from Mathematica background, I find it powerful to be able to quickly enter Greek characters via the key combination, e.g.,  ESC-f-ESC (for phi).  

It would be great to have something comparable for working with Julia.

**Comment by ChrisRackauckas** [comment]
Just do \alpha and then tab. It's even easier since the keys are nearby and it matches TeX more closely.

**Comment by juliohm** [comment]
I personally find this feature very useful. Perhaps the Greek alphabet could have a special shortcut like a key plus a single letter in the keyboard corresponding to the Greek letter (a = alpha, b = beta, ...).

**Comment by ChrisRackauckas** [comment]
Mathematica is less predictable since I've never thought the Euler constant is ee. Simplifications only make sense of you're used to  them. But \alpha always works and it's exactly the name everyone else uses. It matches LaTeX too so you already know the language.

**Comment by juliohm** [comment]
The proposal seems to suggest an extension. It wouldn't affect the current behavior of `\alpha`.

**Comment by ChrisRackauckas** [comment]
Are you sure escape can be captured like that in Atom?

**Comment by juliohm** [comment]
I am not sure about `ESC` but any unused key would do the trick.

On VIM for example we can also configure a sequence of key strokes to trigger the conversion to unicode. Mine for example has a sequence `jj` that behaves like `ESC` and switches the editor to normal mode. If I just press a single `j` and wait a bit, it doesn't take effect.

**Comment by ChrisRackauckas** [comment]
I think this could just be an Atom package, not necessarily part of Juno?

**Comment by juliohm** [comment]
Good call, this could be implemented as an Atom package.

**Comment by ChrisRackauckas** [comment]
For reference, the LaTeX completions "in Juno" are actually a separate Atom package called [latex-completions](https://atom.io/packages/latex-completions), so it could just be implemented similarly and then used with any language. That might be good code to look at to find out how to do it.

**Comment by pfitzseb** [comment]
A compromise could be to give greek charcters a higher priority in the autocompletion list so you can always complete them after two typed chars.

**Comment by pfitzseb** [comment]
Alright, I'll look into implementing that then.

**Comment by pfitzseb** [comment]
atom-latex-completions version 0.3.4 has an option for this (enabled by default) -- with that it's always enough to the first two characters (usually one, but e.g. `θ` and `τ` both start with `t` so the extra char is required to disambiguate them) when you want to enter greek.

**Comment by lwhitefox** [comment]
Thanks for updating and clarifying.
