### ISSUE TITLE
Repl keeps printing `WARNING: Atom.jl: unrecognized message validatepath.`

### ISSUE THREAD

**Issue by jamesonquinn** [JunoLab/Juno.jl#141]
I was having this issue in a fully-updated Atom. I googled it and saw that several people had had the issue and resolved it by updating atom. But that didn't work for me. I tried installing JuliaPro-Juno-0.6.2.2 and that fixed it for a few days but now (after clicking OK to a "rebuild native version of package") it's back, on both Atom and JuliaPro. It's not impossible that it's an old manually-created symlink to a bad version of something, but I don't think I would have done that without using the version in the filename at least.

The dev console has the following errors:

IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:121025
misc.coffee [sm]:30 Julia Boot: 18.70s
internal/process/next_tick.js:103 Uncaught (in promise) undefined
internal/process/next_tick.js:103 Uncaught (in promise) undefined
internal/process/next_tick.js:103 Uncaught (in promise) undefined
internal/process/next_tick.js:103 Uncaught (in promise) undefined
internal/process/next_tick.js:103 Uncaught (in promise) undefined ... x50 or so.

The REPL has: 

WARNING: Atom.jl: unrecognised message changemodule.
WARNING: Atom.jl: unrecognised message changemodule.
WARNING: Atom.jl: unrecognised message validatepath.
WARNING: Atom.jl: unrecognised message validatepath.
WARNING: Atom.jl: unrecognised message validatepath. ... x20 or so, and more appear every time I switch focus from or to the REPL

Here's my versioninfo in JuliaPro:

julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)

I tried updating my node version following the instructions at https://solarianprogrammer.com/2016/04/29/how-to-upgrade-nodejs-mac-os-x/ and it doesn't help:

chema$ node -v
v10.2.1

I tried uninstalling and reinstalling the julia-client in various ways and none of it helped.

My atom was at version 1.23.1 but it's now updated to 1.27.2 x64 and still broken.

I'm at wits' end on this.

**Comment by jamesonquinn** [comment]
I just removed both Atom and JuliaPro. When I reinstalled JuliaPro it worked fine, until I updated atom from version 1.23 to 1.27; then it started having the same problem again.

For now, I'll just use it and make sure not to update.

**Comment by pfitzseb** [comment]
Yoiu'll get those `WARNING: Atom.jl: unrecognised message changemodule.` messages whenever your version of Atom.jl is too old for the julia-client version your running. That should obviously never happen with JuliaPro, but on a normal Juno install you'll need to `Pkg.update()` whenever you update the Atom packages.
