### ISSUE TITLE
Profile lines build up over time

### ISSUE THREAD

**Issue by MikeInnes** [JunoLab/Juno.jl#142]
Now that we have a plot history, profiling multiple times will accumulate lines from each trace overlaying each other. Probably need some way to (de)activate the current plot.

**Comment by pfitzseb** [comment]
Hm, I thought I'd fixed that with https://github.com/JunoLab/atom-ink/commit/24ff85097410e8914c80d470cc55698e0569ac61 -- are you sure your on at least that commit?

**Comment by MikeInnes** [comment]
Yeah I could be out of date.

Thinking about it, I wonder if we really need the history at all given that this isn't the plot pane.

**Comment by MikeInnes** [comment]
Ok, that fixes things. Is there a reason the profile pane steals focus?

**Comment by pfitzseb** [comment]
Uh, that should've been fixed with https://github.com/JunoLab/atom-julia-client/commit/9729d312885d4036bf899b53a2e9532973b75798 :)
