### ISSUE TITLE
Feature Request: Allow hiding `julia>`

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#147]
This request comes after https://github.com/JunoLab/Juno.jl/issues/127#issuecomment-404481797 .

For me it is easier to have an empty entry line in my console than one that starts with `julia>`. I don't know how possible this is... But it is the only reason whatsoever I keep using Legacy console instead of the new one!

**Comment by pfitzseb** [comment]
There's an option for that ( `Console Options > Terminal Prompt`). Just set it to the empty string or `>`.
