### ISSUE TITLE
Hover message with new progress logging

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Juno.jl#149]
With the old logging system I could give a hover message. Now there's just name and one spot for a message which would override the time estimate. Are there no hover detailed allowed anymore?

**Comment by pfitzseb** [comment]
Fixed on ink/Atom.jl master. Will be in the next release.

**Comment by ChrisRackauckas** [comment]
How do you send the message? What's the keyword argument?

**Comment by pfitzseb** [comment]
`message`, so if you just uncomment that line in DiffEq or wherever then it should just work. Also see https://github.com/JunoLab/Atom.jl/blob/master/src/progress.jl#L8-L26.

**Comment by pfitzseb** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/16034
