### ISSUE TITLE
Feature Request: Make "expand button" on the left line of inline bubble

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#154]
Consider this very frequent case:

![image](https://user-images.githubusercontent.com/19669089/43411127-984faf8e-9429-11e8-8dc1-4f4fe9136441.png)

What happens at the inline evaluation of the line `integ = ...`  is unknown to me. I cannot scroll my panel to the right to see it either.

Because this "expand" button (that expands the inline evaluation fully below the line) is on the right side of the bubble, I also cannot reach that. Having this expanding button on the left would solve this problem.

By the way I don't really care if the solution to the problem in the figure comes from moving the expand button or from any other way! I just suggested a solution here.

**Comment by pfitzseb** [comment]
Should be much better after https://github.com/JunoLab/atom-ink/commit/09ff14c1b39ba804a3fd9bac7fefb11b967fb706. Let me know if that's enough for you :)

**Comment by Datseris** [comment]
Hey seb, to try this I need to do what...? Always clueless what to do with the atom packages :D

**Comment by pfitzseb** [comment]
Just install ink v0.9.6 :)

**Comment by Datseris** [comment]
Spectacular! So you've made it so that the inline result "pops up". Veeeery fancy

There is a bug though.

This popping up doesn't work in the case where a line off code exceeds the current scope (and one has to scroll right to see the end of the line). I would expect to be able to scroll to the end of the line, and then see the beggining of the inline result, but I don't see anything. Here is the code to replicate:

```
using DynamicalSystems

@inbounds @inline function ż(z, p, t)
    A, B, D = p
    p₀, p₂ = z[1:2]
    q₀, q₂ = z[3:4]

    return SVector{4}(
        -A * q₀ - 3 * B / √2 * (q₂^2 - q₀^2) - D * q₀ * (q₀^2 + q₂^2),
        -q₂ * (A + 3 * √2 * B * q₀ + D * (q₀^2 + q₂^2)),
        A * p₀,
        A * p₂
    )
end

z0 = SVector{4}(2.3499921651423565, -9.801351029039825, 0.0, -2.7230316965872268)

ds = ContinuousDynamicalSystem(ż, z0, (A=1, B=0.55, D=0.4))
```
if you zoom enough so that the `z0` line exceeds the current scope, but the `ds = ` line does not, you will see what I mean.
