### ISSUE TITLE
Indicate supported version(s) of Julia

### ISSUE THREAD

**Issue by benninkrs** [JunoLab/Juno.jl#158]
I could not find anywhere on the Juno website an indication of which version(s) of Julia are supported.  After following the [installation instructions](http://docs.junolab.org/latest/man/installation.html) and failing to get a REPL, I had to google to find [this comment](https://discourse.julialang.org/t/cant-start-julia-in-juno/13135) claiming that Juno does not support the latest version of Julia (1.0 as of today).

**Comment by pfitzseb** [comment]
Juno does support Julia 1.0 (and 0.6 and 0.7) as of the last release (see [here](https://discourse.julialang.org/t/ann-juno-0-7/12557/18?u=pfitzseb)).

I'll add a note to the website though.

**Comment by benninkrs** [comment]
ok. I must be experiencing a bug then.  I'll file a separate issue.
