### ISSUE TITLE
Multiple REPL consoles

### ISSUE THREAD

**Issue by dominusmi** [JunoLab/Juno.jl#159]
Hi all,

I thought it would be a really nice feature to be able to have multiple REPL in different "tabs", which would just be different julia processes entirely. There was a similar issue ( #82 ) which seemed to be mentioning a way to connect/disconnect from REPLs, but I think simply having different tabs would be more than enough and seems much simpler to both implement and use.

**Comment by pfitzseb** [comment]
You can use the `Julia Client: New Terminal` command to open a new terminal (which just starts your shell) and start a separate Julia process in there. There's also the `Julia Client: Connect External Process` command if you want to connect to that.

**Comment by dominusmi** [comment]
Oh I didn't know thanks! Although I just tried and I do get a bunch of available commands, but neither the new terminal nor the connect external. You're meant to find them in thte control pallette, right? (`ctrl+shift+p`)
I suppose I might be running on slightly outdated versions, is this a relatively new feature?
