### ISSUE TITLE
REPL console does not start

### ISSUE THREAD

**Issue by benninkrs** [JunoLab/Juno.jl#160]
On a fresh install of Julia, Atom, and Juno following the [installation instructions](http://docs.junolab.org/latest/man/installation.html), the REPL console in Juno never gets past the "Press Enter to start Julia" prompt. The progress bar indicates activity, but the REPL is completely unresponsive.

Windows 10
Julia 1.0.0 (installed as administrator into C:\Program Files\)
Atom 1.29.0 (installed as administrator)
uber-juno 0.2.0
Julia-client 0.7.3 (boot mode cycler)
language-Julia 0.16.0

If I switch the console to legacy, it does eventually launch but with some `UndefVarError`s.

**Comment by pfitzseb** [comment]
What happens if you call `using Atom` in a REPL outside of Juno? Are you sure you're on the latest versions of Atom.jl, Juno.jl and all related packages?

**Comment by benninkrs** [comment]
`using Atom` in a separate terminal results in "Package Atom not found in current path" error.  Checking the status showed that I had no installed packages at all.  `.julia` didn't even have the `environments`,  `packages`, and `registries`  folders.

**Comment by benninkrs** [comment]
Is there a log file or something I could be looking at to try to diagnose the problem?

**Comment by benninkrs** [comment]
It works after I updated to Julia-client 0.7.5 and language-Julia 0.17.0.

**Comment by GiAbreu** [comment]
I have the same issue. I was using Julia version 0.6.4, but yesterday the REPL console in Juno stopped working. It shows the message "Press Enter to start Julia", but nothing happens. I already did a clean uninstallation and I try to install the versions 0.7 and them 1.0, but it still doesn't work.
