### ISSUE TITLE
Installation of uber-juno in Atom fails during julia-client install

### ISSUE THREAD

**Issue by DoktorMike** [JunoLab/Juno.jl#161]
Hi I just tried installing Juno in Atom using the install functionality in Atom for package uber-juno. It however fails during what I assume to be the final stages of the installation. 

Juno: Error installing package julia-client
Please check your internet connection, or report this to
    http://discuss.junolab.org
and we'll try to help.
    –––
Error: Installing “julia-client@0.7.3” failed.

Based on a suggestion I also tried deleting my .atom folder with the same outcome.

I'm on a Surface Pro 4, Ubuntu 17.10, Kernel 4.17 and using i3wm tiling window manager. I tried Atom version 1.23.3 and 1.29.

**Comment by pfitzseb** [comment]
Can you try installing `julia-client` without going through uber-juno? If that doesn't work then maybe `apm install julia-client` will.

**Comment by DoktorMike** [comment]
I can confirm that that works.
