### ISSUE TITLE
Juno: Error installing package julia-client

### ISSUE THREAD

**Issue by 3mlyh** [JunoLab/Juno.jl#165]
I can't install the uber-juno package. 
This is the error message: 
Please check your internet connection, or report this to
    http://discuss.junolab.org
and we'll try to help.
    –––
Error: Installing “julia-client@0.7.5” failed.

I have tried installing the julia-client package alone, but it still doesn't work. I also reinstalled Atom and tried to run as Administrator, but nothing worked. Any help is very much appreciated.

**Comment by pfitzseb** [comment]
Can you try starting a terminal and type in `apm install julia-client`? If that fails as well, please paste the error here.

**Comment by 3mlyh** [comment]
Not sure how I start a terminal.. I'm new to this and I don't know a lot of programming. I use Atom and Julia just for a subject. Please let me know how to start a terminal.

**Comment by pfitzseb** [comment]
Depends on your OS. On Windows, open the start menu and type in `cmd`.

**Comment by 3mlyh** [comment]
```Microsoft Windows [Version 10.0.17134.228]
(c) 2018 Microsoft Corporation. Med enerett.

C:\Users\Emily>apm install julia-client
Installing julia-client to C:\Users\Emily\.atom\packages failed

> node-pty-prebuilt@0.7.6 install C:\Users\Emily\AppData\Local\Temp\apm-install-dir-118729-16292-1ce92tv.za671oflxr\node_modules\julia-client\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\Emily\AppData\Local\Temp\apm-install-dir-118729-16292-1ce92tv.za671oflxr\node_modules\julia-client\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\Emily\AppData\Local\atom\app-1.30.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\Emily\AppData\Local\atom\app-1.30.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )
C:\Users\Emily\AppData\Local\Temp\apm-install-dir-118729-16292-1ce92tv.za671oflxr
`-- (empty)


npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
prebuild-install WARN install unexpected end of file
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\Emily\AppData\Local\Programs\Python\Python36\python.EXE" is v3.6.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\Emily\AppData\Local\atom\app-1.30.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\Emily\AppData\Local\atom\app-1.30.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Emily\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Emily\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\Emily\AppData\Local\Temp\apm-install-dir-118729-16292-1ce92tv.za671oflxr\node_modules\julia-client\node_modules\node-pty-prebuilt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Emily\AppData\Local\Temp\apm-install-dir-118729-16292-1ce92tv.za671oflxr\package.json'
npm WARN apm-install-dir-118729-16292-1ce92tv.za671oflxr No description
npm WARN apm-install-dir-118729-16292-1ce92tv.za671oflxr No repository field.
npm WARN apm-install-dir-118729-16292-1ce92tv.za671oflxr No README data
npm WARN apm-install-dir-118729-16292-1ce92tv.za671oflxr No license field.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\Emily\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Emily\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Emily\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Emily\\.atom\\.apmrc" "install" "C:\\Users\\Emily\\AppData\\Local\\Temp\\d-118729-16292-1wm6awg.wnntp4x6r\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script 'prebuild-install || node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Emily\AppData\Local\Temp\apm-install-dir-118729-16292-1ce92tv.za671oflxr\npm-debug.log
npm ERR! code 1


C:\Users\Emily>
```

**Comment by canglangshushu** [comment]
Installing julia-client to C:\Users\11422\.atom\packages failed

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to https://registry.npmjs.org/atom-space-pen-views failed, reason: connect ETIMEDOUT 104.16.24.35:443
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/physical-cpu-count failed, reason: connect ETIMEDOUT 104.16.24.35:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\11422\.atom\.apm\_logs\2018-10-29T00_52_22_279Z-debug.log

**Comment by pfitzseb** [comment]
> This is a problem related to network connectivity.

It seems to be a problem related to network connectivity.

**Comment by jandehaan** [comment]
This solved the issue for me:
In Windows open a command window, enter the following and press the Enter key.
`apm config set strict-ssl false`

**Comment by krcabrer** [comment]
This is what I got.

 node-pty-prebuilt-multiarch@0.9.0 install /tmp/apm-install-dir-120417-50091-1ll2a66.426k/node_modules/julia-client/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


Aborted (core dumped)
Aborted (core dumped)
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.4.0-28-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-120417-50091-1ll2a66.426k/node_modules/julia-client/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted (core dumped)
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-120417-50091-1ll2a66.426k/package.json'
npm WARN apm-install-dir-120417-50091-1ll2a66.426k No description
npm WARN apm-install-dir-120417-50091-1ll2a66.426k No repository field.
npm WARN apm-install-dir-120417-50091-1ll2a66.426k No README data
npm WARN apm-install-dir-120417-50091-1ll2a66.426k No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kenneth/.atom/.apm/_logs/2020-05-17T19_37_18_079Z-debug.log
