### ISSUE TITLE
Add Integrations to the Gitter Page?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Juno.jl#17]
I think it would be nice to have the integrations panel in Gitter follow the activity of the JunoLab packages. It helps for keeping up to date while a conversation is occurring.

**Comment by MikeInnes** [comment]
Happy to have this, can you set it up?

**Comment by ChrisRackauckas** [comment]
Yup, will do

**Comment by ChrisRackauckas** [comment]
I think you might have to do it (looks like it needs owner permissions). You should now be able to click on the Activity bar on the right (you might need to click the arrow on the top right to see it) and then click "Configure Your Integrations", then in Add An Integration click on Github, choose the repositories and what to show, and then hit done. The repos which show up for me are only ones I have admin access to.

**Comment by MikeInnes** [comment]
ok this should be set up now
