### ISSUE TITLE
Inconsistent behaviour when precompiling in Juno REPL vs terminal REPL

### ISSUE THREAD

**Issue by brenhinkeller** [JunoLab/Juno.jl#171]
I ran into some strange inconsistency while attempting to precompile an unregistered package in the Juno REPL:

```julia
julia> using SomeUnregisteredPackage
ERROR: MethodError: no method matching shouldlog(::Atom.Progress.JunoProgressLogger, ::Base.CoreLogging.LogLevel, ::Module, ::Symbol, ::Symbol)
The applicable method may be too new: running in world age 27557, while current world is 27577.
Closest candidates are:
  shouldlog(::Atom.Progress.JunoProgressLogger, ::Any, ::Any, ::Any, ::Any) at /Users/cbkeller/.julia/packages/Atom/WSz3/src/progress.jl:72 (method too new to be called from this world context.)
  shouldlog(::Base.CoreLogging.NullLogger, ::Any...) at logging.jl:83
  shouldlog(::Base.CoreLogging.SimpleLogger, ::Any, ::Any, ::Any, ::Any) at logging.jl:507
  ...
Stacktrace:
 [1] compilecache(::Base.PkgId) at ./logging.jl:306
 [2] _require(::Base.PkgId) at ./loading.jl:942
 [3] require(::Base.PkgId) at ./loading.jl:838
 [4] require(::Module, ::Symbol) at ./loading.jl:833
```
Oddly enough, the same package precompiled without any error in the Julia REPL as run in a bash terminal (albeit with a few v0.7 deprecation warnings) -- after which,`using` the now-precompiled package in the Juno REPL worked just fine. 

In both cases, this was running Julia Version 0.7.0-beta2.0 /  x86_64-apple-darwin14.5.0 with
```
  [c52e3926] Atom v0.7.6
  [e5e0dc1b] Juno v0.5.3
```
I was subsequently able to reproduce the same problem with different package, each time recieving the same error in the Juno Julia REPL and none in the plain Julia REPL -- but I don't know enough about Atom.jl or Juno.jl to debug the root problem.

**Comment by pfitzseb** [comment]
That actually was a bug in Julia itself, which should be fixed in one of the more recent betas (or, indeed, Julia 1.0).

**Comment by brenhinkeller** [comment]
Ok! Workaround is simple enough until then.

**Comment by pfitzseb** [comment]
I can't remember which beta has it, but every version after [this PR](https://github.com/JuliaLang/julia/pull/28290) should work fine. Might be easiest to update to that or even Julia 0.7 release.

**Comment by brenhinkeller** [comment]
Thanks!
