### ISSUE TITLE
Feature request: Syntax highlighting with isa

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#177]
![image](https://user-images.githubusercontent.com/19669089/47094294-3c2fea80-d22b-11e8-8354-e592e7b6cee0.png)

Is it possible for the second case to also apply to the first?

**Comment by pfitzseb** [comment]
You mean highlighting `MagneticParticle` as a type? In theory yes, but I'm not sure how good a heuristic we can find for this.

**Comment by Datseris** [comment]
The same you use in `<:`, which I guess is "what is followed by `<:` gets highlighted" ?

**Comment by pfitzseb** [comment]
Right, but the heuristic already is pretty bad :D
Wanna reopen the issue [here](https://github.com/JuliaEditorSupport/atom-language-julia/issues)?
