### ISSUE TITLE
Module name different when evaluated at different line

### ISSUE THREAD

**Issue by xgdgsc** [JunoLab/Juno.jl#179]
## Details
- Atom version: 1.28.1 
- Julia version: 1.0.1
- OS: ubuntu 18.04
- Package versions:
  - Atom.jl:  v"0.7.8"
  - julia-client: 0.7.8
  - ink: 0.9.11

### Steps to reproduce

1. Use julia client inside atom and write a module
2. as the following image shows, when you press ctrl+enter at line 2, the module would be Main.Test2.Test2, with duplicated level of module name. While if you press ctrl+enter at line 1 or 3, it would give the correct result of Main.Test.

![image](https://user-images.githubusercontent.com/1189869/47352516-a691d080-d6ec-11e8-89a5-7f5605acb349.png)

**Comment by pfitzseb** [comment]
That's working as intended (mostly) -- try with
```
module Test
1+1
end
```
instead. If you have the cursor on line 2 we'll eval `1+1` inside of `Main.Test`.

**Comment by xgdgsc** [comment]
When I declare some types in the module and evaluates, it isn' t what I expect, though.

**Comment by pfitzseb** [comment]
![image](https://user-images.githubusercontent.com/6735977/47355400-90bae600-d6c1-11e8-8322-8b02e2659a90.png)

What do you expect?

**Comment by xgdgsc** [comment]
![image](https://user-images.githubusercontent.com/1189869/47363985-b8826c00-d70a-11e8-821c-a200a9e0e287.png)
Thanks. I'm new to julia. I don' t get the rationality when I click ctrl+enter inside the module struct and get the Main.Test.Test thing. I thought I could just change things inside the module and it would all go to the updated Main.Test.

**Comment by pfitzseb** [comment]
Just re-eval the module again so that it looks like this:
![image](https://user-images.githubusercontent.com/6735977/47365507-0469ec80-d6dc-11e8-9903-d40b8f883119.png)

**Comment by xgdgsc** [comment]
But I have to move cursor to the end of top, which can be unproductive for large modules, is it possible to do that in the middle?
