### ISSUE TITLE
No Response using PyCall with Juno Console

### ISSUE THREAD

**Issue by davidgaut** [JunoLab/Juno.jl#180]
Hello everyone, 
I have an issue using PyCall in Atom using the console (Legacy in the Juno settings). 
While everything works fine when using the REPL and the fact that the package seems to install fine, "using PyCall" gets the console stuck indefinitely.

This occurs for different versions of Julia (0.7 and 1.0.1) and seems to concern only the PyCall package.

**Comment by pfitzseb** [comment]
Can you reproduce this with the REPL-based console?

**Comment by davidgaut** [comment]
I cannot, the issue seems specific to the Juno console, using the REPL works fine both in Atom or directly in Julia console.

**Comment by pfitzseb** [comment]
Alright, I don't think I want to spend time on fixing the legacy console -- I'd heavily recommend using the REPL based console for anyways.

**Comment by yha** [comment]
Note that the legacy console is still necessary to workaround the `winpty` bug (rprichard/winpty#142) which makes the Juno REPL unusable in the presence of antivirus software (JunoLab/atom-julia-client#443).
I still use it for this reason on a machine with McAfee where I have no permissions to add an exception for `winpty` in McAfee settings.
