### ISSUE TITLE
Segfault on a multithreading printing with locks only when moving text cursor in the IDE

### ISSUE THREAD

**Issue by IsaacTay** [JunoLab/Juno.jl#183]
## Details
- Atom version: 1.31.2
- Julia version: 1.0.0
- OS: Windows 10 Home 64-bit (IDE & Julia) & Ubuntu 18.04.1 LTS (Remote Julia)
- Package versions:
  - Atom.jl: 0.7.8
  - julia-client: 0.7.8
  - ink: 0.9.11

### Steps to reproduce

1. Run File (Shift + Cmd + Enter) on this code
```
import Random

function locked_run(f::Function, print_lock)
    lock(print_lock)
    results = f()
    unlock(print_lock)
    return results
end

function main()
    print_lock = Threads.SpinLock()
    println("Starting Threads")
    Threads.@threads for i in 1:10000
        locked_run(print_lock) do
            println(i)
        end
        for _ in 1:10000 # To delay the cycles
            ones(10, 10) * ones(10, 10)
        end
    end
    println("Done Threads")
end

println("Load Done")
```
2. Move the text cursor in the editor (Clicking, Arrow Keys, etc.)

This cause the Julia program to segfault. I've tested running it both on my own machine, and the remote server I have Julia on, both resulted in a segfault the moment the text cursor was moved.

**Comment by pfitzseb** [comment]
The code you have isn't really threadsafe anyways, so you could get segfaults even outside of Juno. Two possible reasons you're only seeing this in Juno:
- You didn't start Julia with multiple threads outside of Juno.
- The multiple `Task`s Juno uses exacerbates the problem.

You should use `Core.println` instead, as per [here](https://discourse.julialang.org/t/print-functions-in-a-threaded-loop/12112/8?u=pfitzseb) (or only print on the main thread, I guess).

Definitely not a bug with Juno though.

**Comment by IsaacTay** [comment]
Ah, sorry about that. `Core.println` works just fine.

**Comment by pfitzseb** [comment]
No worries :)
