### ISSUE TITLE
Permissions Error / Path Error

### ISSUE THREAD

**Issue by togo59** [JunoLab/Juno.jl#184]
I've been using Julia and Atom for about two years without hassle. Since yesterday, depending on how I use Atom, I get: 

From Atom menu Julia -> Start Julia
`We tried to launch Julia from:
/home/rpowell/julia-1.0.1/bin/
This path can be changed in the settings.
Details:
  /bin/sh: 1: /home/rpowell/julia-1.0.1/bin/: Permission denied`

If I try to open a julia program I get:
`Failed to spawn command julia. Make sure julia is installed and on your PATH`

I have `/home/rpowell/julia-1.0.1/bin/:` in my Julia path in settings. If I cut and paste this into the Linux shell it finds Julia. I have not changed the file permissions, the files are local. Probably irrelevant, but I also have the correct path in my PATH environment variable.

I have uninstalled packages "uber-juno", "julia-client", "julia-lint", "language-julia", "linter-julia" and re-installed. If I type "using Atom" at the Julia prompt there are no errors.

OS is Kubuntu. What am I missing?

**Comment by pfitzseb** [comment]
You actually have to specify the binary there, not just the dir that contains the binary.

Also see https://discourse.julialang.org/t/juno-permission-denied/16941 for a very similar question.

**Comment by togo59** [comment]
Thanks I had the reference to binary in originally. As one of the options I took it out. Something else I've done may have changed things. Now with the binary pointed to it seems to work again. Weird. Thank you though!

**Comment by pfitzseb** [comment]
Great, glad you got it working now! :)

**Comment by togo59** [comment]
Spoke to soon. See attached.
![atomerror](https://user-images.githubusercontent.com/4964667/47722360-2d453100-dc4a-11e8-838f-52b5a9e9a176.png)

**Comment by pfitzseb** [comment]
Can you try restarting Atom and see if it still errors? I don't see why we should throw that error at all, but maybe there's some weird old state cached somewhere.

**Comment by togo59** [comment]
Every time I make a change I restart Atom. In fact it was only when I restarted it that I realised the error had not gone away.

**Comment by togo59** [comment]
This is what I have been doing before the behavior changed: Using Documenter.jl, setting up my own Julia package structure (sort of required by Documenter). I have always used git but I have had to rebuild the directory structure.  I am in the middle of restructuring a lot of Julia code. But obviously none of this affects the location of the binary.

**Comment by pfitzseb** [comment]
The error message you're getting is some internal error which Juno should never get to. Are you sure that the error is thrown by Juno?

**Comment by togo59** [comment]
I'm sure as I can be. The same behavior happens with all the packages/Julia files I'm working on, even stuff I haven't touched for years. I thought it might be that I use terminator (Juno doesn't seem to like launching this) so I uninstalled it. No change. I'll start trying more radical things. The problem doesn't seem to occur on Solus linux but then I am not pointing it at the same files but that shouldn't matter. Clearly it's something unique to me. I have to use Kubuntu because I'm also working with ROS ( Robot OS). I'll reinstall Atom.

**Comment by togo59** [comment]
Reinstalling: sudo apt-get remove atom; sudo apt-get purge atom; rebooting(!) and then reinstalling atom had no effect. BTW I don't use snap. Then I find if I start atom, in say folder X, from the command prompt it's fine, whereas if I navigate to said folder X using the file manager (currently PCManFM 1.2.4) I get the above errors. The file permissions don't look weird but I tried opening them up, to no avail. So it only works from the command prompt. That's not a big issue for me.

**Comment by togo59** [comment]
rm -rf .atom 
sudo apt-get remove --purge atom 
re-install 
and ONLY install uber-juno seems to have fixed it. :)
