### ISSUE TITLE
REPL in Juno doesn't work and the Julia can't sart

### ISSUE THREAD

**Issue by GiAbreu** [JunoLab/Juno.jl#187]
I was using Julia version 0.6.4, but yesterday the REPL console in Juno stopped working. It shows the message "Press Enter to start Julia", but nothing happens. I already did a clean uninstallation and I try to install the versions 0.7 and them 1.0, but it still doesn't work.

**Comment by Kleptine** [comment]
I'm having the exact same issue with a fresh install of both Atom and then immediately Juno. 

julia-client itself won't install properly: see:
`Installing “julia-client@0.7.11” failed.Hide output…
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, open 'C:\Users\LocalUser\.atom\packages\julia-client\script\spawnInterruptible.ps1'`

**Comment by pfitzseb** [comment]
That probably is a problem with your antivir -- you could try disabling that for the installation.

**Comment by Kleptine** [comment]
Well I'll be damned -- never had AVG have issues installing anything else on this computer in the last 5 years, but so it was. 

This would be a great thing to add to the FAQ. And alternatively, I'm pretty confused why this is getting flagged repeatedly.

**Comment by pfitzseb** [comment]
Good idea, I'll add it to the FAQ.
