### ISSUE TITLE
[FR] Shortcut to run current line

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#191]
It would be great to have the following functionality: a shortcut that runs the current line the cursor is located, _irrespectively_ of the surrounding code and code block. 

This is extremely helpful in interactively doing science. For example, in the following code:
```
for m in 1:M
        reduced = dropdims(sum(huphi[:, m, :], dims=2), dims=2)[positive]
        # make it a distribution
        distribution = reduced ./ step(φs) ./ sum(reduced)

        means[m] = sum( positive .* distribution .* step(φs) ) / length(distribution)
        maxs[m] = positive[argmax(distribution)]
```
Let's say that my cursor is in the last line. I would like to have a way to just run this line by itself (i.e. automatically un-indent it, run it, and then indent it again).

**Comment by ChrisRackauckas** [comment]
Shift down -> Ctrl enter? Basically, highlight the line and Ctrl enter does it. Though it would be nice for a more standardized way here.

**Comment by Datseris** [comment]
Both `Shift Down` and `Shift Home` have their respective flaws. The first requires the cursor to be at the _start_ of a line and not a random position. The latter requires the cursor to be at the end of the line (and Home button is super far away as well).

If it could work with a "random" cursor position it would be nice :) Otherwise, if I have to go to the start of the line it is already the same as just double clicking the line .

**Comment by pfitzseb** [comment]
Actually, `Ctrl-L Ctrl-Enter` is the "correct" way to do this. Not sure if this warrants its own shortcut given then...

**Comment by Datseris** [comment]
Its only flaw is that it skips a line: if you ctrl+enter then you don't move forward, if you shift+enter you skip the next line

but seems like you are right, this is not worh its own short cut, since one can just press right and then again cntrl+L
