### ISSUE TITLE
In-line evaluation failing with valid syntax in while loop

### ISSUE THREAD

**Issue by rharper2** [JunoLab/Juno.jl#192]
## Details
- Atom version: 1.32.2
- Julia version: 0.7 (although syntax also valid in 1.0)
- OS: Mac-OSX
- Package versions:
  - Atom v0.7.9
  - Juno v0.5.3
  
### Steps to reproduce

1. Place the following minimal code example  in a test.jl file and have the file open in the editor.

```
function checkIt()
    state = []
    while(true)
        break
    end
    return state
end

```

2. with the cursor 'in' the function, shift-enter to evaluate.

One gets an “incomplete: “function” at … test.jl requires end” error.

The problem is the “while(true)”, it needs to be written as “while (true)”, or better I suppose “while true"

However the "while(true)" is accepted by the REPL and if you directly just include the file etc.

**Comment by pfitzseb** [comment]
Hm, while this actually is valid syntax (which I didn't think it was), I'm not sure whether I actually want to support this case.

Fun fact: Syntax highlighting here on github shows the difference as well:
```julia
while(true)
end
```
vs
```julia
while true
end
```
