### ISSUE TITLE
Cannot read property of 'children' of undefined

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#195]
Screenshot:
![image](https://user-images.githubusercontent.com/19669089/49013716-fc3f1a00-f17d-11e8-91d6-2083cbf4ae45.png)

## Details
- Atom version: Latest stable
- Julia version: 1.02
- OS: Windows 1064bt
- Atom/Juno/etc,: latest stable

## Steps to reproduce
I have no idea. The issue pops up randomly. I don't know how to reproduce.

**Comment by Datseris** [comment]
Big problem, as the console becomes unusable once this occurs. You have to restart Atom, which is bad.

**Comment by pfitzseb** [comment]
Yeah, that's an upstream bug... you can try disabling the fallback renderer in the julia-client settings for now though.

**Comment by Datseris** [comment]
Your suggestion doesn't fix it.

**Comment by pfitzseb** [comment]
Hm, I haven't seen it happen either with or without the fallback renderer. If neither work fine for you then we'll need to wait until a new xterm.js version is out (or use master).
