### ISSUE TITLE
Problems in Installing Juno

### ISSUE THREAD

**Issue by ale111111** [JunoLab/Juno.jl#196]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.32.2
- Julia version:  0.6.4
- OS: Windows 10
- Package versions:
  - Atom.jl:
  - julia-client: julia-client@0.7.10
  - ink:

### Description

Hello,
I am trying to install the Juno package so to use Julia from Atom.
However: I get the following error message:
Error: Installing “julia-client@0.7.10” failed.
I followed the suggestions in https://github.com/JunoLab/Juno.jl/issues/165 , but with no success. In particular, when trying  "apm install julia-client", I get the following error message(s). Could anyone explain to me what it means? I am also surprised to see python mentioned. Does Juno have anything to do with it? By the way, Python is not installed in my computer right now.

H:\>apm install julia-client
Installing julia-client to C:\Users\my_name\.atom\packages failed

>node-pty-prebuilt@0.7.6 install C:\Users\my_name\AppData\Local\Temp\apm-install-dir-1181027-9852-1pfjml6.v1i1h\node_modules\julia-client\node_modules\node-pty-prebuilt
>prebuild-install || node scripts/install.js

C:\Users\my_name\AppData\Local\Temp\apm-install-dir-1181027-9852-1pfjml6.v1i1h\node_modules\julia-client\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
This program is blocked by group policy. For more information, contact your system administrator.
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\my_name\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\Users\\my_name\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--build_v8_with_gn=false' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\my_name\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\my_name\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\my_name\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\my_name\AppData\Local\Temp\apm-install-dir-1181027-9852-1pfjml6.v1i1h\node_modules\julia-client\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\my_name\AppData\Local\Temp\apm-install-dir-1181027-9852-1pfjml6.v1i1h\package.json'
npm WARN apm-install-dir-1181027-9852-1pfjml6.v1i1h No description
npm WARN apm-install-dir-1181027-9852-1pfjml6.v1i1h No repository field.
npm WARN apm-install-dir-1181027-9852-1pfjml6.v1i1h No README data
npm WARN apm-install-dir-1181027-9852-1pfjml6.v1i1h No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\my_name\.atom\.apm\_logs\2018-11-27T09_19_24_903Z-debug.log

**Comment by pfitzseb** [comment]
Dup of https://discourse.julialang.org/t/problems-in-installing-juno-installing-julia-client-0-7-10-failed/18009/.
