### ISSUE TITLE
Initialization issues using Juno and Atom with julia

### ISSUE THREAD

**Issue by huckl3b3rry87** [JunoLab/Juno.jl#2]
I am trying to use Atom with julia 0.5.0-rc2 by following the developer instructions here:
[(https://github.com/JunoLab/atom-julia-client/tree/master/docs)]
I followed the instructions, but Julia cannot be started **from Atom** with the following error:
`
Julia could not be started.
We tried to launch Julia from:
julia
This path can be changed in the settings.
Details:
  /bin/sh: 1: julia: not found
`
But when I type `julia` into my terminal (on Ubuntu 16.04), julia starts up without an issue. 

I then tried to change the folder in the in the config.cson file to the path where the julia binaries are:
`  juliaPath: "/opt/julia-0.5.0/bin" `
then I got:
`
Julia could not be started.
We tried to launch Julia from:
/opt/julia-0.5.0/bin
This path can be changed in the settings.
Details:
  /bin/sh: 1: /opt/julia-0.5.0/bin: Permission denied
`
Also, there seems to be an issue on the **julia side** as well after I followed the instructions, when I run julia in the terminal and run a `Pkg.update()`, I get:
`
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of DataFrames...
INFO: Updating cache of DataFrames...
INFO: Updating GR master...
INFO: Updating ImageMagick master...
INFO: Updating Atom master...
INFO: Computing changes...
ERROR: unknown package Juno required by Atom
 in requirements(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at ./pkg/query.jl:11
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:477
 in update(::String, ::Set{String}) at ./pkg/entry.jl:458
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
 in update() at ./pkg/pkg.jl:210
`
I then tried to remove Atom as per this post:
[(https://github.com/JunoLab/atom-julia-client/issues/191)]
`
julia> Pkg.rm("Atom")
INFO: Removing Atom (unregistered)

julia> Pkg.clone("http://github.com/JunoLab/Atom.jl")
INFO: Cloning Atom from http://github.com/JunoLab/Atom.jl
INFO: Computing changes...
ERROR: unknown package Juno required by Atom
 in requirements(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at ./pkg/query.jl:11
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:477
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at ./pkg/entry.jl:476
 in edit(::Function, ::SubString{String}) at ./pkg/entry.jl:30
 in clone(::String, ::SubString{String}) at ./pkg/entry.jl:203
 in clone(::String) at ./pkg/entry.jl:221
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#clone,Tuple{String}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#clone,Tuple{String}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
 in clone(::String) at ./pkg/pkg.jl:151
`
But there were some issues. I noticed that the issue is related to Tuples and can't help but wonder if it is related to this bug in 0.5.0-rc2:
[https://github.com/JuliaLang/julia/issues/18385]

**Comment by MikeInnes** [comment]
I know the [uber-juno](https://github.com/JunoLab/uber-juno/blob/master/setup.md) instructions said that we didn't support 0.5 until recently, but that was out of date – so chances are you don't need the dev setup. My suggestion is to `Pkg.rm` both the Julia packages and `apm remove` both the Atom packages, then follow those instructions instead.

Also, the path must be the Julia binary rather than the folder containing Julia. So it probably needs to end in `/bin/julia` in your case.

**Comment by huckl3b3rry87** [comment]
Thank you for your help Mikelnnes, you were correct about the path and that it needs to end in /bin/julia.

Otherwise, I followed what you suggested, but I ran into an issue when running 2+2 in the Console:
`
ERROR: LoadError: ArgumentError: Juno not found in path.
Run Pkg.add("Juno") to install the Juno package
 in require(::Symbol) at ./loading.jl:346
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/febbo/.atom/packages/julia-client/script/boot.jl, in expression starting on line 36
Julia has stopped: 1`

then in the window that pops up, I get:
`Error loading Atom.jl package
Go to the Packages → Julia → Open Terminal menu and
run `Pkg.update()`in Julia, then try again.
If you still see an issue, please report it to:
    http://discuss.junolab.org/`
After doing a `Pkg.update()` and closing both programs, I ran thorough this again with the same result. 
Any ideas? Thank you very much!

**Comment by pfitzseb** [comment]
Either `Pkg.clone("https://github.com/JunoLab/Juno.jl")`, or do waht Mike suggested.

**Comment by huckl3b3rry87** [comment]
@pfitzseb thank you for your suggestion, what you said worked like a charm!

**Comment by huckl3b3rry87** [comment]
also, why does this pop up each time I enter something into the console? 
WARNING: Atom.jl: unrecognised message clearLazy.

**Comment by huckl3b3rry87** [comment]
Also, on the install page [https://github.com/JunoLab/atom-julia-client/tree/master/docs](url), you guys might want to add the line, `Pkg.clone("https://github.com/JunoLab/Juno.jl")` so that nobody else has this issue. I had first tried the basic install and when that did not work, I tried the developer install before taking the advice from @MikeInnes and going back to the basic install

**Comment by cuichenpei** [comment]
I met similar issue in ATOM when launching Julia. and the issue was fixed by adding Julia Path in Setting. 
you can have a try. Juno --> Setting --> Julia Path. (specify your Julia binary path)
