### ISSUE TITLE
Auto complete try to print nothing for `Tuple`

### ISSUE THREAD

**Issue by Roger-luo** [JunoLab/Juno.jl#200]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.33.0 x64
- Julia version: v.1.0.1
- OS: OS X
- Package versions:
  - Atom.jl: master branch
  - julia-client: 0.7.11
  - ink: 0.9.13

### Steps to reproduce

1. type `Tuple()`
2. you will get:

![image](https://user-images.githubusercontent.com/8445510/49542755-67869b80-f8a4-11e8-90d3-f8370095c92a.png)

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/Atom.jl/commit/dd533c39f3281b6aaea4341ac7dd341ba7642946.

That error is soooooooooooooooo annoying tho.
