### ISSUE TITLE
Autocomplete stops working in editor when REPL is running

### ISSUE THREAD

**Issue by ndinsmore** [JunoLab/Juno.jl#203]
I am having an issue where autocomplete filtering stops working as soon as the julia REPL starts running.   If I stop the REPL the Autocomplete starts working again.   It seems to effect both the code completion and the Latex completion.   Below are images that should help explain.

## Details
- Atom version: 1.33
- Julia version:1.0.2
- OS: OSX 10.13.6
- Package versions: 
  - Atom.jl: 0.7.10
  - julia-client: 0.7.11
  - ink:0.9.13

### Steps to reproduce

1.Test showing Autocomplete works before REPL has started:
![image](https://user-images.githubusercontent.com/45537276/49759678-5537a380-fc90-11e8-9c5f-fbc1462b2025.png)

2.Start the REPL and Autocomplete no longer works:
![image](https://user-images.githubusercontent.com/45537276/49760315-363a1100-fc92-11e8-91dd-f8309533a2a1.png)

3.) . Stop the REPL and it works again:
![image](https://user-images.githubusercontent.com/45537276/49760369-51a51c00-fc92-11e8-88cd-0482c779b2b7.png)

**Comment by ndinsmore** [comment]
I have done a test by downgrading to julia-client 0.7.10 and confirmed that the issue is not present in that release.   The only change was made through `apm install julia-client@0.7.10`

![image](https://user-images.githubusercontent.com/45537276/49761028-e2c8c280-fc93-11e8-8c9f-9f9256fc8d8b.png)

**Comment by pfitzseb** [comment]
What's the output of `pkg> status` in the REPL? I suspect you're on an old version of Atom.jl.
