### ISSUE TITLE
Having Juno installed independantly from Atom baseline

### ISSUE THREAD

**Issue by Akaban** [JunoLab/Juno.jl#204]
Hello,

Juno looks pretty cool but I have an issue with it, I'd like to keep my baseline Atom (which I use for developping in Python) separated from Juno (and its Julia plugins), is this possible?

Thanks by advance,

Bryce.

**Comment by ChrisRackauckas** [comment]
Juno only "happens" when a file is saved as a .jl or .jmd.

**Comment by Akaban** [comment]
Hello,

Indeed I don't have the "Plots" window + debugger enabled when I open a Python project. But I still have the left dock from Juno + the Julia menu on the top.

Not a big issue though but I'd like to completely disable Juno when developping in Python :) If not possible then no big deal !

Cheers

**Comment by Akaban** [comment]
I see, thanks a lot. I managed to close the toolbar with right click but could not reopen it though.

Anyways that's not a big issue, I'm closing it ;)

**Comment by pfitzseb** [comment]
You can toggle the toolbar manually with `Tool Bar: Toggle`:
![image](https://user-images.githubusercontent.com/6735977/50209915-2cd93480-0375-11e9-8c43-2fe69e52bb7b.png)
