### ISSUE TITLE
Running profiler from Juno REPL gives wrong result. 

### ISSUE THREAD

**Issue by aviks** [JunoLab/Juno.jl#205]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.33.0
- Julia version: 1.0.2
- OS: MacOS Mojave
- Package versions:
  - Atom.jl: 0.7.11
  - julia-client: 0.7.11
  - ink: 0.9.13

### Steps to reproduce

run `@profile MyPackage.my_function()` in command line REPL and in Juno REPL

<img width="742" alt="screenshot 2018-12-14 at 09 44 14" src="https://user-images.githubusercontent.com/378918/49996388-c922c600-ff86-11e8-919f-e4c1416d3482.png">

In the image, the top half is profiler running from the command line, and the bottom half is the profiler running in the Juno REPL. Running `@profiler` (instead of `profile`) also shows an incorrect output. 

One additional symptom is that the profiler complains about the buffer being full when run in Juno, but not on the command line.

**Comment by pfitzseb** [comment]
Does this happen when you use inline evaluation in an editor?

**Comment by pfitzseb** [comment]
Ok, so I was playing around with this a bit and the main difference is that Juno runs multithreaded by default whereas the REPL does not. With `JULIA_NUM_THREADS=12 julia` things look pretty similar all in all.
Can you try the "global" option in the julia-client settings? There should be no major differences anymore I think.

Juno's profile viewer is also a bit different from ProfileView.jl in the sense that it hides stackframes with only one child and instead displays the child directly.

**Comment by pfitzseb** [comment]
Should be fixed on master, where we filter profile traces much better.
