### ISSUE TITLE
[FR] Clickable way to activate current project

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#206]
Would be really cool to have a clickable way to set the current project.
This could be done like:

1. Exactly like one selects current module at the moment.
2. Like one adds a project folder in Atom, where a window explorer opens.
3. Automatically or with some user defined automatic way. ...?

**Comment by BeastyBlacksmith** [comment]
Having right-click on `Project.toml` being able to activate that environment would be very helpful.
