### ISSUE TITLE
Defaulting to remote Julia connection

### ISSUE THREAD

**Issue by staticfloat** [JunoLab/Juno.jl#207]
It would be very helpful to be able to set remote Julia connections as the default, so that when I attempt to evaluate something with no running Julia session it automatically starts the remote Julia session.

**Comment by pfitzseb** [comment]
You can set the `Boot Mode` to `Remote`:
![grafik](https://user-images.githubusercontent.com/6735977/50052449-6404d700-0124-11e9-80d1-b7abe4096160.png)
