### ISSUE TITLE
Julia Client - Internal Error

### ISSUE THREAD

**Issue by staticfloat** [JunoLab/Juno.jl#209]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.33.0
- Julia version: 1.0
- OS: OSX (local) Linux (remote)
- Package versions:
  - Atom.jl: 0.7.11
  - julia-client: 0.7.11
  - ink: 0.9.13

### Steps to reproduce

I'm not sure how to reproduce, this just seemed to pop up while I was typing.

```
Julia Client – Internal Error
BoundsError: attempt to access 1-element Array{Any,1} at index [2]
getindex at array.jl:731 [inlined]
get_value_getfield(::Expr, ::Function) at REPLCompletions.jl:355
get_value_getfield(::Expr, ::Module) at REPLCompletions.jl:357
try_get_type(::Expr, ::Module) at REPLCompletions.jl:399
try_get_type(::Expr, ::Module) at REPLCompletions.jl:411
get_type(::Expr, ::Module) at REPLCompletions.jl:420
complete_symbol(::String, ::getfield(REPL.REPLCompletions, Symbol("##21#25")), ::Module) at REPLCompletions.jl:123
completions(::String, ::Int64, ::Module) at REPLCompletions.jl:699
basecompletionadapter(::String, ::Module) at completions.jl:21
(::getfield(Atom, Symbol("##189#191")){String,String})() at completions.jl:11
withpath(::getfield(Atom, Symbol("##189#191")){String,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:46
(::getfield(Atom, Symbol("##188#190")))(::Dict{String,Any}) at completions.jl:7
handlemsg(::Dict{String,Any}, ::Dict{String,Any}) at comm.jl:164
(::getfield(Atom, Symbol("##19#21")){Array{Any,1}})() at task.jl:259
```

**Comment by pfitzseb** [comment]
Hm, this looks like a bug in Base's autocompletions to me. 
I didn't have any luck finding a way to repro this yet, so please paste the line of code the cursor was on should you come across this again. Apparently Base parsed a `getfield` call where `ex.args` is of length 1 (which doesn't make any sense)...

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/Atom.jl/commit/4af4d3e877aaf0ee7819c4ad1a1a961dc3309a9a on our end.
