### ISSUE TITLE
Feature Request: Find/search within the console output

### ISSUE THREAD

**Issue by NHDaly** [JunoLab/Juno.jl#212]
Feature Request:

Related to: https://github.com/JunoLab/atom-julia-client/issues/330

One of the only reasons I ever switch back to a terminal and the regular julia REPL is when i want to _search_ through my REPL's terminal output. (As one example, when printing the `@code_typed` of a big function, and i want to find a specific function call within it, i find myself switching back to the terminal, opening Julia, and rerunning all the commands I need to get me back to that output.)

It'd be super great if the default Atom `find-and-replace` pane was able to search the contents of the Console! But if that's not possible, I guess having our own searchbox that opens on <kbd>cmd</kbd><kbd>f</kbd> would also work.

**Comment by NHDaly** [comment]
I wasn't sure if this belongs here or in https://github.com/JunoLab/atom-julia-client.  I would've guessed it belongs in the other repo, but the "New Issue" page says:

> Please open your issue at https://github.com/JunoLab/Juno.jl/issues/new unless you've been explicitly pointed here by a Juno developer.

😁

**Comment by pfitzseb** [comment]
xterm.js has a addon for this [here](https://github.com/xtermjs/xterm.js/tree/master/src/addons/search), but we'll still need to write our own UI for that. Re-using Atom's `find-and-replace` panel is probably not super easy.

> I wasn't sure if this belongs here or in https://github.com/JunoLab/atom-julia-client. I would've guessed it belongs in the other repo

Yeah, I'd rather have all user issues/feature requests here so I don't lose track of them spread across 5 repos :)

**Comment by NHDaly** [comment]
Ah okay cool! So Xterm.js is the package we use to implement the terminal in the Console pane? Neat. I can look at that and see what i can do..

**Comment by NHDaly** [comment]
Fwiw, here's how the the `find-and-replace` sets which `Pane` it's looking in when it does the searching:
https://github.com/atom/find-and-replace/blob/71a80c0b793423e7166fd26c2f39e932b9b5cd14/lib/find.coffee#L34

It calls [`observeActivePaneItem`](https://atom.io/docs/api/v1.9.4/Workspace#instance-observeActivePaneItem) on the `workspace` to set up a callback where every time a `Pane` is _activated_, the `Model` in the find-and-replace package is updated to point to the newly activated Pane's `TextEditor`. (I don't really understand how the `Pane` is being converted into a `TextEditor` there, though...)

So, maybe we could hook into the `find-and-replace` package by creating a fake `TextEditor` -- a class that implements the  `TextEditor` interface but calls `xterm.js` for its [`scan`](https://atom.io/docs/api/v1.9.4/TextEditor#instance-scan) function -- and adding it to the Pane that contains the Console? :)

**Comment by NHDaly** [comment]
Cool! So i think the `find-and-replace` integration might not be too hard! :)

I have a first-pass rough implementation here: https://github.com/NHDaly/atom-ink/commit/6c006fe96e140c183a93e5d0302cea9357947cd7

Next I'm going to look into the `xterm.js` search functionality you pointed out, and try to hook that up to the search API! :)
