### ISSUE TITLE
Can't uninstall package from Atom

### ISSUE THREAD

**Issue by cesar-rodriguez92** [JunoLab/Juno.jl#213]
Trying to uninstall throws this error: 

- **Failed to delete julia-client: EPERM** (see pic)

![image](https://user-images.githubusercontent.com/15166883/50381772-49b78580-065d-11e9-90f3-ccf867a3cd57.png)

**Comment by pfitzseb** [comment]
Try closing Atom and typing `apm uninstall julia-client` into a terminal. Otherwise you might get around this issue by the REPL pane, restarting Atom, and clicking `Uninstall` again.
