### ISSUE TITLE
BoundsError: attempt to access 2-element Array

### ISSUE THREAD

**Issue by Roger-luo** [JunoLab/Juno.jl#216]
## Details
- Atom version: 1.33.1
- Julia version: 1.0.1
- OS: Mac OS
- Package versions:
  - Atom.jl: v0.7.11
  - julia-client: 0.7.11
  - ink: 0.9.13

### Steps to reproduce

1.  run the following

```julia
ex = :(function foo(::Int) end)
```

2. type the following

```
ex.args[1].args[2].
```

**Comment by pfitzseb** [comment]
Seems like a bug in Base:
```
julia> ex = :(function foo(::Int) end)
:(function foo(::Int)
      #= REPL[6]:1 =#
  end)

julia> ex.args[1].args[2].┌ Error: Error in the keymap
│   exception =
│    BoundsError: attempt to access 2-element Array{Any,1} at index [3]
│    Stacktrace:
│     [1] getindex at ./array.jl:731 [inlined]
...
```

**Comment by yha** [comment]
A similar error, thrown from the same function in `REPLCompletions.jl`, two lines earlier:
After `using Plots`, typing
```
plot(log.(x),
```
produces
```
BoundsError: attempt to access 1-element Array{Any,1} at index [2]
getindex at array.jl:731 [inlined]
get_value_getfield(::Expr, ::Function) at REPLCompletions.jl:355
get_value_getfield(::Expr, ::Module) at REPLCompletions.jl:357
[...]
```

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/Atom.jl/commit/4af4d3e877aaf0ee7819c4ad1a1a961dc3309a9a on our end.

**Comment by pfitzseb** [comment]
Upstream fix is included in https://github.com/JuliaLang/julia/pull/30569.
