### ISSUE TITLE
Move "Additional Julia Startup Arguments" textfield up

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/Juno.jl#219]
I've made this mistake at least twice now, and today someone else did also and was asking in slack:

I want to add a command-line flag to julia's startup, so I open preferences, see the "Arguments" field, and add them there, which doesn't throw any error but just doesn't do what I want. The help text says it sets `ARGS`, but without thinking carefully it's an easy mistake to make.

I propose that the "Additional Julia Startup Arguments" config field be moved to right below the "Julia Path" config, as it seems like a more common operation than setting `ARGS`, and is more related to how julia is invoked.

**Comment by pfitzseb** [comment]
Done with https://github.com/JunoLab/atom-julia-client/commit/d19a1db872c5d145ba6fd4d61a03547562ed46a8.
