### ISSUE TITLE
Extend "run cell" to recognize Weave chunk

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/Juno.jl#224]
It would be handy to extend the "Run Cell" command so that it recognized a Weave.jl chunk. e.g. If I have the following `.jmd` file:

    some explanation

    ```julia
    x = 2
    y = 4
    run_some_code(x, y)
    ```

    some more explanatory info

And I ran the "Run cell" command with the cursor on `x = 2`, it would run the whole code block.

**Comment by ssfrr** [comment]
awesome! Thanks for looking into this.

**Comment by pfitzseb** [comment]
New release is out and should give a much nicer workflow together with language-weave@0.4.5.
