### ISSUE TITLE
"Open Startup File" not working

### ISSUE THREAD

**Issue by daschw** [JunoLab/Juno.jl#225]
As reported on slack, in Juno, if I click in the menu bar on `Julia` > `Open Startup File`, nothing happens.

**Comment by pfitzseb** [comment]
Fixed in https://github.com/JunoLab/atom-julia-client/commit/7882cec8fe463941fe3fe04c734afb8c9855316e. Until that release is out you can just use the `Open Julia startup file` and `Open Juno startup file` commands.

**Comment by daschw** [comment]
Great, thanks!
