### ISSUE TITLE
Uncaught (in promise) INFO --> Julia has exited. Press Enter to start a new session -->powershell not found

### ISSUE THREAD

**Issue by sloggers** [JunoLab/Juno.jl#227]
Press Enter to start Julia. 
Julia has exited. Press Enter to start a new session.
-------------------------------------------------------------
No error message except above
atom = 1.34.0 x64
Julia version = Version 1.0.3 (2018-12-18)
all packages are up to date
Julia REPL does start from cmd.exe
What is the 'right' combination of atom/Julia if above combo isn't compatible?
Would be ideal if atom can show what command with flags that failed.
thanks

**Comment by sloggers** [comment]
More info: found out Atom's control-shift-i :
local.coffee:105 Julia exited with INFO: Could not find files for the given pattern(s).
.
(anonymous) @ local.coffee:105
_tickCallback @ internal/process/next_tick.js:188
Promise rejected (async)
start @ local.coffee:98
_boot @ connection.coffee:41
boot @ connection.coffee:56
(anonymous) @ connection.coffee:18
terminal.startRequested @ console2.js:54
InkTerminal.enterhandler @ console.js:108
(anonymous) @ console.js:158
Terminal._keyDown @ C:\Users\John\.atom\packages\ink\node_modules\xterm\lib\Terminal.js:985
(anonymous) @ C:\Users\John\.atom\packages\ink\node_modules\xterm\lib\Terminal.js:392
internal/process/next_tick.js:188 Uncaught (in promise) INFO: Could not find files for the given pattern(s).

not sure if related but I found 3 different apm.cmd files
content of the one in app-1.3.4.0\resources\app\apm is below: 
@echo off
setlocal enabledelayedexpansion

:: Try to find git.exe in path
for /f "tokens=*" %%G in ('where git 2^>nul') do set "apm_git_path=%%~dpG"
if not defined apm_git_path (
  :: Try to find git.exe in GitHub Desktop, oldest first so we end with newest
  for /f "tokens=*" %%d in ('dir /b /s /a:d /od "%LOCALAPPDATA%\GitHub\PortableGit*" 2^>nul') do (
    if exist "%%d\cmd\git.exe" set "apm_git_path=%%d\cmd"
  )
  :: Found one, add it to the path
  if defined apm_git_path set "Path=!apm_git_path!;!PATH!"
)

set "maybe_node_gyp_path=%~dp0\..\node_modules\node-gyp\bin\node-gyp.js"
if exist "%maybe_node_gyp_path%" (
  set "npm_config_node_gyp=%maybe_node_gyp_path%"
)

if exist "%~dp0\node.exe" (
  "%~dp0\node.exe" "%~dp0/../lib/cli.js" %*
) else (
  node.exe "%~dp0/../lib/cli.js" %*
)

**Comment by pfitzseb** [comment]
You either don't have the correct Julia binary selected or your `PATH` is messed up and we can't find `powershell.exe` -- try disabling the `Powershell Wrapper´ option and if it works afterwards check that `where powershell` returns something like `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe` when executed in `cmd`.

**Comment by sloggers** [comment]
You hit the nail on the head: no path to powershell.exe
I see julia now inside atom.
Suggestion: something like "... powershell.exe .. line failed"
thanks

**Comment by sloggers** [comment]
thanks for the help

________________________________
