### ISSUE TITLE
REPL stops responding to keys after Ctrl-evaluation

### ISSUE THREAD

**Issue by KristofferC** [JunoLab/Juno.jl#228]
## Details
- Atom version: 1.34.0
- Julia version: 1.0.3
- OS: Windows 10
- Package versions:
  - Atom.jl: 0.7.13
  - julia-client: 0.7.13
  - ink: 0.9.14

### Steps to reproduce

1. Type something in the REPL, it works.
2. Ctrl evaluate an expression.
3. Typing something in the REPL stops working.

Video:

![vid](https://user-images.githubusercontent.com/1282691/51437864-3de2d180-1ca4-11e9-86dd-42c4b7dd00e9.gif)

**Comment by pfitzseb** [comment]
Should be fixed with https://github.com/JunoLab/Atom.jl/commit/ad450df5d7b917f842aec3768cb1b1e6dd9dd60b -- can you try Atom.jl#master real quick to confirm?

**Comment by pfitzseb** [comment]
https://github.com/JunoLab/Atom.jl/releases/tag/v0.7.14

**Comment by KristofferC** [comment]
Yep, works now. Thanks for speedy fix.

**Comment by Davidxu2016** [comment]
> Yep, works now. Thanks for speedy fix.

Hi KristofferC, I use Juno on Window and have the same bug you experienced. Could you let me know how you fixed it?

**Comment by KristofferC** [comment]
I didn't do anything, the bug just got fixed (https://github.com/JunoLab/Juno.jl/issues/228#issuecomment-455859335).
