### ISSUE TITLE
Error about iterating Pkg.Types.PackageEntry

### ISSUE THREAD

**Issue by KristofferC** [JunoLab/Juno.jl#229]
Atom version: 1.34.0
Julia version: 1.1.0
OS: Windows 10
Package versions:
Atom.jl: 0.7.14
julia-client: 0.7.13
ink: 0.9.14

### Steps to reproduce

Not sure

Error message:

```
MethodError: no method matching iterate(::Pkg.Types.PackageEntry)
Closest candidates are:
  iterate(!Matched::Core.SimpleVector) at essentials.jl:568
  iterate(!Matched::Core.SimpleVector, !Matched::Any) at essentials.jl:568
  iterate(!Matched::ExponentialBackOff) at error.jl:199
  ...
first(::Pkg.Types.PackageEntry) at abstractarray.jl:288
finddevpackages() at utils.jl:36
(::getfield(Atom, Symbol("##208#209")))() at misc.jl:26
handlemsg(::Dict{String,Any}) at comm.jl:164
(::getfield(Atom, Symbol("##19#21")){Array{Any,1}})() at task.jl:259
```

**Comment by pfitzseb** [comment]
This is probably triggered by the `Open Package in New Window` command. Happens because the internal `Pkg.Types.read_manifest` API changed with Julia 1.1 -.-

Not sure how to best handle something like this, but there probably is no way around manual version checks...

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/Atom.jl/commit/7549d6f77f778e10eed45d72b3493fea571b30ac.
