### ISSUE TITLE
Where is `render(::Inline, ::Table)` defined?

### ISSUE THREAD

**Issue by jkroso** [JunoLab/Juno.jl#23]
I see @MikeInnes submitted a PR to dataframes.jl which shows the `Table` type being rendered but Its not working for me

**Comment by pfitzseb** [comment]
[Here](https://github.com/JunoLab/Atom.jl/pull/68). I guess Mike forgot to merge this, but should be good to go now.

**Comment by jkroso** [comment]
Thanks
