### ISSUE TITLE
Installed Juno, but Julia exits upon starting

### ISSUE THREAD

**Issue by TayoEXE** [JunoLab/Juno.jl#232]
I'm just trying to run Julia scripts and use a Julia IDE for development. julia.exe works just fine as intended by itself, and the path to julia.exe is correct. I've checked several times. When I try to start Julia in any way including when the REPL says "Press Enter to start Julia," it never gives an error message, just exits. Most other problems dealt with it lagging, not responding, or giving an error upon starting up Julia. But this only happens in Atom, not when I run Julia directly. What is going on? I've tried downloading the language-julia package, julia-client package, and uber-juno package.

## Details
- Atom version: 1.34.0 x64
- Julia version: 1.1.0
- OS: Windows 7 64-bit
- Package versions:
  - Atom.jl: 
  - julia-client: 0.7.13
  - ink: 0.9.14

### Steps to reproduce

1. Install the latest version of Atom and Julia
2. Look at the REPL. Should say "Please Enter to start Julia."
3. Press Enter, and it will only say "Julia has exited. Press Enter to start a new session."

**Comment by pfitzseb** [comment]
This might be similar to https://github.com/JunoLab/Juno.jl/issues/227#issuecomment-455897669 -- can you try that and report back? 
The next release will have some logic to handle this kind of error gracefully.

**Comment by TayoEXE** [comment]
I actually found out what the issue was. For some reason all I had to do to fix this was go to Packages->Julia->Settings and untick Enable Powershell Wrapper. Perhaps this option should be looked at more closely. So the problem is solved, but thanks for answering!

**Comment by t-pollington** [comment]
I think it may occur when choosing to install Julia to PATH during the installation process, so I just choose to leave that box unchecked.
