### ISSUE TITLE
Problems closing and reopening Atom

### ISSUE THREAD

**Issue by ale111111** [JunoLab/Juno.jl#235]
## Details
- Atom version: 1.34.0
- Julia version: 0.6.4
- OS: Windows 10 Education
- Package versions:
  - Atom.jl:  
  - julia-client: 0.7.13
  - ink:

### Steps to reproduce

Hi everyone, I have been having the following issue with Atom/Juno/Julia lately. I will try do describe it in 3 points:

1) Let's assume everything is working. Then I close Atom, and reopen it. 
Many times, it happens that inside Atom's window on my desktop there is nothing: the window is completely grey. This means: no most recent project, no side menu (where I can normally select, among the other things: New Julia File, Save, Open File, REPL,...), etc.
The toolbar menu on the window top is still present, I can still click on the different buttons, even though nothing seems to happen. For example, I can click on Settings, but settings won't be shown. I can try to reopen the project I was working on, but nothing happens. 
Still, Atom seems to be opened on the correct project path (if I look at the one specified on the window top), but as you can understand it is completely unusable in this condition.

2) However, if I right click on the Atom icon in the Windows task bar (the one at the bottom of the desktop), and select new window, a new window pops up, and - good news - Atom seems to work perfectly fine. It is open on a new blank .jl file, there is again the side menu (with New Julia File, Save, Open File, REPL,...), and generally speaking Atom is again responsive to what I do. Including going back to the project folder I was working on.

3) In conclusion, the situation is not catastrophic, however it is extremely annoying and time consuming to repeat this procedure. In fact, right now I am debugging a long code and I need to close and reopen Atom (and thus Julia) very frequently to make sure that when I run a new piece of code no previous variables are saved, etc.

Can anyone explain me if there is any solution to this problem?
I am not even sure it is related to Juno or Atom or Julia.

Thank you very much in advance.

**Comment by pfitzseb** [comment]
This _seems_ like an Atom problem (which doesn't mean that Juno isn't a contributing factor).

Couple of things you could try:
1. When you get the blank window, try opening the Atom dev tools with <kbd>Ctrl-Shift-I</kbd> and look for errors in the console.
2. Delete `C:\Users\<you>\AppData\Roaming\Atom`. You shouldn't lose any settings from that, except maybe your project list (not 100% sure though, so make a backup if you're worried).
3. Delete `C:\Users\<you>\.atom\compile-cache` and `blob-store`.
4. If neither of those work and step 1 doesn't give any new info, try completly reinstalling Atom and Juno. This is the nuclear option, and I'm not sure if it'd even help...

**Comment by ale111111** [comment]
@pfitzseb Thank you very much!
