### ISSUE TITLE
Standard Layout should be in settings

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/Juno.jl#237]
Can remove the `First Boot` option from the shown settings and instead have `Standard Layout` visible.

**Comment by sschuldenzucker** [comment]
This setting is hard to overlook! I was just about opening a new issue for this, then fortunately found this issue. Especially for something that interferes with atom's default functionality, putting it at the *bottom* of the *second* section of the options may not be the best.

**Comment by pfitzseb** [comment]
It is something you explicitly have to opt into (unless you're using JuliaPro, I guess). But I tend to agree it should maybe be higher up.
