### ISSUE TITLE
Julia has exited. Press enter to start a new session.

### ISSUE THREAD

**Issue by Tolfin** [JunoLab/Juno.jl#238]
I've got the same problem as in #227. I've unticked Enable Powershell Wrapper but it didn't helped. The Julia binary also seems correct to me.
Some details:
* Atom version: 1.34.0 x64
* Julia version: 1.1.0
* OS: Windows 10 64-bit
I'm not very well in computer science, so please be patient with me. I'm also not a native speaker, as you may already noticed.

**Comment by pfitzseb** [comment]
Did you try what I suggested in https://github.com/JunoLab/Juno.jl/issues/227#issuecomment-455897669?

**Comment by Tolfin** [comment]
Did you mean, try disabling the `Powershell Wrapper` option what you said to sloggers? Is there more to do, then just untick `Enable Powershell Wrapper`?

**Comment by pfitzseb** [comment]
I meant the "What happens if you type `where powershell` into a cmd terminal" part.

**Comment by Tolfin** [comment]
I've just typed where powershell into a cmd terminal. And this is the response: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Is there anything wrong?

**Comment by pfitzseb** [comment]
No, that looks correct. If you open the Atom dev tools with <kbd>Ctrl-Shift-I</kbd> and navigate to the console tab, do you see any errors when trying to start Julia?

**Comment by Tolfin** [comment]
These are the errors:

Julia exited with Error: Error
C:\Users\Admin\.atom\packages\julia-client\lib\connection\local.coffee:158
launching WinPTY agent: agent executable does not exist: '\\?\C:\Users\Admin\.atom\packages\julia-client\node_modules\node-pty-prebuilt\build\Release\winpty-agent.exe'.

Uncaught (in promise) Error: 
C:\Users\Admin\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\windowsPtyAgent.js:25
Error launching WinPTY agent: agent executable does not exist: '\\?\C:\Users\Admin\.atom\packages\julia-client\node_modules\node-pty-prebuilt\build\Release\winpty-agent.exe'
    at new WindowsPtyAgent (C:\Users\Admin\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\windowsPtyAgent.js:25:24)
    at new WindowsTerminal (C:\Users\Admin\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\windowsTerminal.js:45:24)
    at Object.spawn (C:\Users\Admin\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\index.js:27:12)
    at file:///C:/Users/Admin/.atom/packages/julia-client/lib/connection/process/basic2.js:46:24
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by pfitzseb** [comment]
That error either means that julia-client didn't install correctly or your antivir deleted that file. You'll need to add an exception to your antivirus software for `C:\Users\Admin\.atom\packages\julia-client\` or `node_modules\node-pty-prebuilt\build\Release\winpty-agent.exe` and re-install julia-client.

**Comment by Tolfin** [comment]
I've uninstalled julia-client and then installed it via Avast Secure Browser and now it works. But what is this, when I started Julia for the first time?
Error: Error building `MbedTLS`:
│ ┌ Warning: On Windows, creating file symlinks requires Administrator privileges
│ └ @ Base.Filesystem file.jl:794
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ [ Info: Downloading https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.17.0/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz to C:\Users\Admin\.julia\packages\MbedTLS\XkQiX\deps\usr\downloads\MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.17.0/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz to C:\Users\Admin\.julia\packages\MbedTLS\XkQiX\deps\usr\downloads\MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #download#93(::Bool, ::Function, ::String, ::String) at C:\Users\Admin\.julia\packages\BinaryProvider\4F5Hq\src\PlatformEngines.jl:498
│  [3] #download at .\none:0 [inlined]
│  [4] #download_verify#94(::Bool, ::Bool, ::Bool, ::Function, ::String, ::String, ::String) at C:\Users\Admin\.julia\packages\BinaryProvider\4F5Hq\src\PlatformEngines.jl:567
│  [5] #download_verify at .\none:0 [inlined]
│  [6] #install#133(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at C:\Users\Admin\.julia\packages\BinaryProvider\4F5Hq\src\Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\none:0
│  [8] top-level scope at C:\Users\Admin\.julia\packages\MbedTLS\XkQiX\deps\build.jl:48
│  [9] include at .\boot.jl:326 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1038
│  [11] include(::Module, ::String) at .\sysimg.jl:29
│  [12] include(::String) at .\client.jl:403
│  [13] top-level scope at none:0
│ in expression starting at C:\Users\Admin\.julia\packages\MbedTLS\XkQiX\deps\build.jl:44
│ Ausnahme beim Aufrufen von "DownloadFile" mit 2 Argument(en):  "Ausnahmefehler w�hrend einer
│ WebClient-Anforderung."
│ In Zeile:5 Zeichen:1
│ + $webclient.DownloadFile("https://github.com/JuliaWeb/MbedTLSBuilder/r ...
│ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
│     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
│     + FullyQualifiedErrorId : WebException
│ 
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075

**Comment by Tolfin** [comment]
Thanks for the help.

**Comment by pfitzseb** [comment]
Not entirely sure why that's happening (maybe a firewall issue), but it's unrelated to Juno. Try reporting it [here](https://github.com/JuliaWeb/MbedTLS.jl/issues/172).

**Comment by frawas** [comment]
Try installing this https://docs.microsoft.com/en-us/powershell/wmf/overview and re-installing Julia

**Comment by hafez-ahmad** [comment]
i did not figure out 
Julia has exited.
Press Enter to start a new session.

**Comment by amburosesekar** [comment]
In my system(Windows 10), same issue, i have just go to setting in atom 

> uninstall and install the **julia-client** package. 

then restart atom. it's work fine :)
