### ISSUE TITLE
[BUG] Current working directory equals system directory in first few moments of kernel's existence

### ISSUE THREAD

**Issue by krcools** [JunoLab/Juno.jl#239]
Please search existing issues to avoid duplicates.

## Details
- Atom version: v0.7.14
- Julia version: v1.0.3
- OS: Win10-x64

I want to configure my `juno_startup.jl` script to automatically activate the local environment when the Atom project directory happens to be a Julia project. However, the first few moments the Julia kernel is alive, the `pwd()` equals `C:\Windows\System32`. It is only after a fraction of a second that the working dir is changed to the project folder.

As a temporary fix I included a `sleep(0.2)` in my `juno_startup.jl` but I was hoping for a more robust solution.

### Steps to reproduce

1. Use the following `julia_startup.jl`:

```
using Pkg
if isfile("Project.toml")
    Pkg.activate(".")
end
```

2. Spin up a new kernel from within Atom

**Comment by anj00** [comment]
same problem. 

- Atom v0.8.2
- Juno v0.7.0
- OS: Win10-x64

below loop
```
for i = 1:10
    @show pwd()
    sleep(1)
end
```
typically outputs `"C:\\Users\\<user>\\AppData\\Local\\atom\\app-1.35.1"` first couple of seconds. later switches to project folder

IF I don't have Julia running AND start script using `Ctrl+Shift+Enter`.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/9ed2eb5eb4cf684b107cc40ebe6c037213b8eee3.
