### ISSUE TITLE
[BUG] Don't autostart Juno on non-Julia files

### ISSUE THREAD

**Issue by tbenst** [JunoLab/Juno.jl#240]
I frequently get various errors from Juno due to it starting when I am not editing Julia files:
for example,
1.  start Juno session in one window 
2. open non-Julia file in another window 
3. save file => "Julia could not be started. Port 45100 is already in use"

**Comment by pfitzseb** [comment]
Right, you can just switch the Boot Mode to Basic -- this will only start a Julia process when you try to evaluate something (at the cost of higher startup times).

**Comment by tbenst** [comment]
Ah thanks! I see there's now a description in julia-client now but hasn't been released yet

**Comment by tbenst** [comment]
@pfitzseb As of 0.7.13, julia still tries to run on Boot Mode - basic. I get the following error while editing a python file:

```
We tried to launch Julia from:
julia
This path can be changed in the settings.
Details:
  /bin/sh: julia: command not found
```

**Comment by pfitzseb** [comment]
What did you do before that happened? I can't reproduce that issue if I enter an incorrect Julia path.

**Comment by tbenst** [comment]
@pfitzseb I moved to a chroot where julia is not available. If I do not move to a chroot and julia is available, the error does not occur, presumably because julia is being called
