### ISSUE TITLE
[BUG] Resuming remote sessions gives error if session is in package mode

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/Juno.jl#245]
It looks like on a reconnect Juno attempts to run `Juno.connect(portnum)` unconditionally. If the REPL is in a nonstandard mode (like pkg mode), the command will fail.

## Details
- Atom version: 1.34.0
- Julia version: 1.1.0
- OS: Arch Linux
- Package versions:
  - Atom.jl: 0.7.14
  - julia-client: 0.7.13
  - ink: 0.9.14

### Steps to reproduce

1. Start a remote session
2. press `]` to go into pkg mode
3. exit Atom
4. restart Atom
5. reconnect to the remote session
6. observe the error

**Comment by pfitzseb** [comment]
Yeah, that's a bit unfortunate. Best way to handle this is probably to send a bunch of backspace key presses first; `Ctrl-C` seems like a spectacularly bad idea and I don't know how else to escape REPL modes.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/fa630b1af4f852600295a119bd1a77aea7e8591c.
