### ISSUE TITLE
[BUG] repl can freeze when output lines look like file paths

### ISSUE THREAD

**Issue by daviehh** [JunoLab/Juno.jl#248]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.34.0
- Julia version: 1.0.1
- OS: mac
- Package versions:
  - Atom.jl: 0.7.14
  - julia-client: 0.7.13
  - ink: 0.9.14

### Steps to reproduce

1. using the run file button in the toolbar, run a long-time script which may print a lot of info as it runs via `println()`, at the end of script, there's a `println("done")`. [not sure if it helps but the return data from the function can be tuples of big matrices]
2. after seeing the `done` output, console hangs, julia is still running with almost 100% cpu, the `julia>` prompt in repl is not showed, and no complete notification is displayed, after up to minutes, then the notification shows, the `julia>` prompt get displayed and things get back to normal
3. no such behavior when run by typing into repl `include("script.jl")`: after seeing the `done` output, both notification and the `julia>` prompt in the repl shows up immediately.

- I have tried fallback renderer, etc, and no other packages are installed. 
- the develop console/Electron dev tools  (opt-cmd-I on mac) does not show any warning/error

maybe related to https://github.com/JunoLab/Juno.jl/issues/103, and I'm not using `addprocs()`; (and issue still happens when limiting thread to 1)

Is there a verbose mode of juno so that I can find what it's doing?

**Comment by daviehh** [comment]
update: possible something like "race" condition?

I have this block in my function:

```
for i in 1:iter_n
      #doing calculations...
        if rem(i, output_every) == 0
            println("...")  #print some long stuff with calculation results, etc
        end
end
```

e.g. `iter_n = 1000`, if I set `output_every=1`, i.e. print something every iteration, then this problem does not exist, or `output_every=100`, this problem also does not exist. If `output_every = 10`, etc, this issue happens.

**Comment by pfitzseb** [comment]
Hm, this seems kinda weird -- no idea what's going on there, really.

Couple of things:
1. Can you share your code? 
2. What happens if you hide the output of your function invocation with a `;`?
3. Do you have any async constructs that might block or something like that?

**Comment by daviehh** [comment]
@pfitzseb Thanks! Sorry, I'm unable to share the code at the moment;

- no async stuff, just a loop (~500 to 1000 iterations) that does some linear algebra/differential equation solving for different parameters, return value can be deeply nested big array of matrices, but the issue still persists when I change the return value to `nothing`, and workspace pane is off.
- No issue when suppressing all print()/println()
- No issue when print()/println() every iteration
- No issue when run in atom repl with `include("script.jl")`, and obviously no issue when run outside atom (directly from terminal)
- only happens when printing, e.g. every 10 iterations through (iter_n=500 or higher, `output_every =10`)

```
for i in 1:iter_n
      #doing calculations...
        if rem(i, output_every) == 0
            println("...")  #print some long stuff with calculation results, etc
        end
end 
```

also, the problem is not so severe if I put sleep(.1) after the print,

```
for i in 1:iter_n
      #doing calculations...
        if rem(i, output_every) == 0
            println("...")  #print some long stuff with calculation results, etc
            sleep(0.1)
        end
end 
```

**Comment by daviehh** [comment]
@pfitzseb using the profiling tool, I took a snapshot of the run, eg. with 500 iterations, there's a ~10s lag between the last output from script to repl responding/run complete notification. I've put a red arc between the frames where the script finishes and the lag begins (slightly after 50,000ms), there's a clear change in the function call pattern/js memory heap:

<img width="1792" alt="screen shot 2019-03-07 at 11 00 23 am" src="https://user-images.githubusercontent.com/25255906/53970548-f89a2800-40c8-11e9-90c1-08c34f20f507.png">

**Comment by daviehh** [comment]
As comparison, this is a snapshot of when I print every iteration and see no lag between script finishing and repl responsive

<img width="1792" alt="screen shot 2019-03-07 at 11 28 48 am" src="https://user-images.githubusercontent.com/25255906/53972266-73187700-40cc-11e9-98a7-c394cab2ad5b.png">

**Comment by pfitzseb** [comment]
Can you upload the first profile somewhere for me so I can take a closer look?

I don't really see any reason why anything would be different in Atom when running in the REPL vs running in the editor, except if something's happening with the returned values. Very weird all in all.

**Comment by daviehh** [comment]
@pfitzseb my thoughts precisely, I've changed the return value to `0` and it still lags. Here's a link to the profile, script finishes/lag starts around 34000ms

https://www.dropbox.com/s/cnvqo8hn17o3cpt/Profile-20190307T111846.json.zip?dl=0

**Comment by daviehh** [comment]
@pfitzseb I think I found where the problem might be. By making some changes to my fork of `Atom.jl` to print the time: https://github.com/daviehh/Atom.jl/commit/8d664b4b9951ebb563dc6cf81decf67db9bbf34f

the output is:

```
2019-03-07T14:51:17.925 atom.jl include_string done.
2019-03-07T14:51:18.834 atom.jl invokelatest done.
2019-03-07T14:51:18.848 hide prompt: r=f()
2019-03-07T14:51:18.924 hide prompt: flush and sleep
2019-03-07T14:51:45.078 hide prompt: rpc cursorpos
2019-03-07T14:51:45.078 hide prompt: println
julia> 2019-03-07T14:51:45.078 hide prompt: restore
2019-03-07T14:51:45.078 hide prompt: trunc
2019-03-07T14:51:45.078 hide prompt: restore input buffer
julia> 2019-03-07T14:51:45.078 hide prompt done.
2019-03-07T14:51:45.078 atom.jl unlock done.
```

somehow, the `@rpc cursors()` line [here](https://github.com/JunoLab/Atom.jl/blob/cacb63e17ed7775231670a9111b1806144b822f1/src/repl.jl#L93) takes ~26 seconds to complete, causing the lag. Still not sure how to make this happen with simple code though. Might be off-topic but the cursor style setting (block/underline/bar) is not respected (did restart terminal/atom, always displays block).

**Comment by pfitzseb** [comment]
Yeah it kinda makes sense that is the culprit when I look at your Atom profile, but I still don't have any clue what would block Atom for that long...

Can you try replacing [those lines](https://github.com/JunoLab/Atom.jl/blob/cacb63e17ed7775231670a9111b1806144b822f1/src/repl.jl#L93-L94) with
```julia
  ch = Channel(2)
  @async put!(ch, @rpc cursorpos())
  @async begin
    sleep(0.1)
    put!(ch, [1])
  end
  pos = take!(ch)
  pos[1] != 0 && println()
```
That should kinda work around the hang on the Julia side, but still doesn't solve anything (probably).

One idea is that [these two handlers](https://github.com/JunoLab/Atom.jl/blob/cacb63e17ed7775231670a9111b1806144b822f1/src/repl.jl#L54-L60) are causing trouble (bit of a long shot, but the best idea I have at the moment -- it's possible that our link recognition regex catches something in your output and makes lots of calls to Julia to validate them). Try replacing them with
```julia
handle("fullpath") do uri
  lock(evallock) do
    return fullREPLpath(uri)
  end
end

handle("validatepath") do uri
  lock(evallock) do
    return isfile′(fullREPLpath(uri)[1]) # or just always return false here
  end
end
```
Or, if you want to take the nuclear option, delete [this](https://github.com/JunoLab/atom-julia-client/blob/6ebd13ebbc8415fd6f161bc2ebc552e7a5d30a1b/lib/runtime/console2.js#L105) and [this](https://github.com/JunoLab/atom-julia-client/blob/6ebd13ebbc8415fd6f161bc2ebc552e7a5d30a1b/lib/runtime/console2.js#L122) line.

>  Might be off-topic but the cursor style setting (block/underline/bar) is not respected (did restart terminal/atom, always displays block).

That's a separate [bug](https://github.com/JunoLab/atom-julia-client/issues/552).

**Comment by daviehh** [comment]
@pfitzseb Thanks a lot! Looks like you are right in that the link recognition regex can be causing the trouble. My output lines look like
```
390/500 [0 r/0 f], ETA~Thu, 07 Mar 2019 16:31:27, z~0.067, 0:0:7 to go
```
there're a couple of `/` in them, (and `:`) by changing the slashes to another symbol
```
890|1000 [0 retry], ETA~Thu, 07 Mar 2019 17:06:59, z~0.064, 0:0:7 to go
```
the issue disappears.
But it also depends on the "speed"/frequency of the output: no lags when printing every iteration even though in that case the output size is larger; lags when printing every 10 iterations, and lags more when the total number of iteration is higher (more output).

The issue https://github.com/JunoLab/atom-julia-client/issues/552 may affect this since it appears that it may be caused by "fall-back renderer" not picking up by `ink`. Is there a way to check? cursor styles are easy to see but not sure how to check whether renderer is dom or canvas. Without changing any code, just by reinstalling ink/re-ticking "fall-back renderer", I may also solve this issue.

**Comment by daviehh** [comment]
I can reproduce it with the code below, `svdval` is there to make sure julia is busy during the loop:

```
using LinearAlgebra

function f(iter_n)
    for i in 1:iter_n
        x = rand(100:9999)
        y = rand(100:9999)
        z = rand(100:9999)
        b = [svdvals(rand(100,100)) for j in 1:100]
        if i<10 || rem(i,10)==0
            println("$i/$iter_n /$x /$y /$z")
        end
    end
    return 0
end

out = f(500)

println("\ndone")
```

[here the rpc call can take mimutes]:

> done
> 2019-03-08T11:13:22.446 atom.jl include_string done.
> 2019-03-08T11:13:22.488 atom.jl invokelatest done.
> 2019-03-08T11:13:22.495 hide prompt: r=f()
> 2019-03-08T11:13:22.626 hide prompt: flush and sleep
> 2019-03-08T11:16:29.041 hide prompt: rpc cursorpos
> 2019-03-08T11:16:29.041 hide prompt: println
> julia> 2019-03-08T11:16:29.041 hide prompt: restore
> 2019-03-08T11:16:29.041 hide prompt: trunc
> 2019-03-08T11:16:29.042 hide prompt: restore input buffer
> julia> 2019-03-08T11:16:29.042 hide prompt done.
> 2019-03-08T11:16:29.042 atom.jl unlock done.


output using https://github.com/daviehh/Atom.jl/commit/8d664b4b9951ebb563dc6cf81decf67db9bbf34f

Changing `/` to `|` and repl is responsive immediately. Not sure what's the best way for a fix though, as clicking in the output with `filepath:linenumber` when there's an error is very helpful.

**Comment by pfitzseb** [comment]
Thanks so much for providing a MWE -- I should have a fix very soon now that I can repro this.

**Comment by daviehh** [comment]
Thanks a lot!

**Comment by pfitzseb** [comment]
New version is out and should fix this issue. Feel free to reopen this issue if that is not the case.
