### ISSUE TITLE
stepping through stdlib code while debugging hangs editor

### ISSUE THREAD

**Issue by StefanKarpinski** [JunoLab/Juno.jl#25]
Not sure what the best way to report the circumstances for this is. JuliaPro 0.5.0.2 build.

**Comment by pfitzseb** [comment]
Does that happen in any Base function in particular? I can't reproduce this with e.g. `@step gcd(12, 15)`.
Also, are the Atom packages (and Atom itself) up-to-date for you, especially `ink`?

**Comment by StefanKarpinski** [comment]
I'll try to come up with a repro later. It may also be fixed, according to @MikeInnes.

**Comment by MikeInnes** [comment]
I'm seeing an editor crash if I try to close an editor (or the whole Atom window) when it's in debug mode. Not sure if it's the same issue though.
