### ISSUE TITLE
[BUG] Start Julia failed with MKL error

### ISSUE THREAD

**Issue by chengchingwen** [JunoLab/Juno.jl#254]
I run a Julia that I build with the intel MKL and failed to start inside Juno.
But it can be started in the terminal and also the remote Julia process from my laptop.
I guess it might be due to the missing environment variable but I'm not sure how to add it. 

## Details
- Atom version:1.34.0
- Julia version: custom build 1.1.0 with intel MKL
- OS:ubuntu 18.04
- Package versions:
  - Atom.jl:0.7.14
  - julia-client:0.7.14
  - ink:0.9.15

### Steps to reproduce

1.Press enter to start Julia at the REPL session
2.Press enter
the  result
```
Press Enter to start Julia. 
Intel MKL FATAL ERROR: Cannot load libmkl_core.so.

Julia has exited. Press Enter to start a new session.
```

**Comment by pfitzseb** [comment]
Can you try starting Atom from a terminal? That should make sure the `PATH` is correct, I think.

**Comment by chengchingwen** [comment]
You are right, but it seems that I must run Atom from the terminal every time. if I run Atom from the application menu, there is  still the same bug.

**Comment by chengchingwen** [comment]
Is it possible to set the variable permanently?

**Comment by pfitzseb** [comment]
You can put something like
```
process.env["blah"] = "foo"
```
in your Init Script (Ctrl-Shift-P, type in "init script"), but you'll need to figure out what you need to set.

**Comment by chengchingwen** [comment]
Oh, that works. I set the `LD_LIBRARY_PATH` in the Init Script. Thanks.
Just wondering, would it be better to copy the environment variable from the shell?

**Comment by pfitzseb** [comment]
Where do you set `LD_LIBRARY_PATH`? In `.bashrc`?

**Comment by chengchingwen** [comment]
Original the `LD_LIBRARY_PATH` is set in `.bashrc` and  in order to make Atom work, I set 
```coffee
process.env["LD_LIBRARY_PATH"] = #the value I get from the terminal
```
in the Init Script

**Comment by chengchingwen** [comment]
Can we run a shell with it's init script(like `.bashrc`) and dump all the environment variable with `env` to Atom?
