### ISSUE TITLE
[BUG] Editor execution with `run` hangs when requesting input

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JunoLab/Juno.jl#255]
## Details
- Atom version: 1.34.0
- Julia version: 1.1
- OS: Fedora 24
- Package versions:
  - Atom.jl: 0.7.14
  - julia-client: 0.7.14
  - ink: 0.9.15

### Steps to reproduce
```julia
touch("test.txt")
run(`rm -i test.txt`) # running this in the editor will hang. Running in the REPL is fine.
```

**Comment by pfitzseb** [comment]
Probably a dup of https://github.com/JunoLab/Juno.jl/issues/118.
