### ISSUE TITLE
[FR] Disable auto-completion for strings?

### ISSUE THREAD

**Issue by Roger-luo** [JunoLab/Juno.jl#256]
When I try to type `primitive` inside a string, e.g

```
"primi"
```

I still get auto completion, maybe disable it when inside a string?

**Comment by pfitzseb** [comment]
This is surprisingly hard/impossible, since those "completions" are actually snippets that can't be disabled based on the scope. You can however disable all `snippet`-related packages :)

**Comment by Roger-luo** [comment]
Okay... does it I should give vscode a try when it is functional for 1.1?
