### ISSUE TITLE
[BUG] REPL whitelisted keybindings don't work for key sequences

### ISSUE THREAD

**Issue by Oblynx** [JunoLab/Juno.jl#258]
## Details
- Atom version: 1.35.1
- Julia version: 1.1.0
- OS: linux
- Package versions:
  - Atom.jl: 0.7.15
  - julia-client: 0.7.14
  - ink: 0.9.15

### Steps to reproduce

* Follow-up to https://github.com/JunoLab/atom-julia-client/issues/458

Although the whitelisted keybindings work for single keybindings like `Ctrl-w`, they don't work for sequences like `Ctrl-w right`.

I tried adding both `Ctrl-w` and `Ctrl-w right` to the REPL whitelist. The result is that `Ctrl-w` is interpreted by Atom as intended, but the sequence isn't. I use `Ctrl-w <direction>` to change windows in Atom.

**Comment by pfitzseb** [comment]
Yup. This isn't really possible without duplicating lots of logic in Atom, as far as I can tell. You could whitelist `Ctrl-W` and `Ctrl-Right` separately, which would allow the sequence `Ctrl-W Ctrl-Right` to work properly.

**Comment by kilikilikid** [comment]
> ## Details
> * Atom version: 1.35.1
> * Julia version: 1.1.0
> * OS: linux
> * Package versions:
>   
>   * Atom.jl: 0.7.15
>   * julia-client: 0.7.14
>   * ink: 0.9.15
> 
> ### Steps to reproduce
> * Follow-up to [JunoLab/atom-julia-client#458](https://github.com/JunoLab/atom-julia-client/issues/458)
> 
> Although the whitelisted keybindings work for single keybindings like `Ctrl-w`, they don't work for sequences like `Ctrl-w right`.
> 
> I tried adding both `Ctrl-w` and `Ctrl-w right` to the REPL whitelist. The result is that `Ctrl-w` is interpreted by Atom as intended, but the sequence isn't. I use `Ctrl-w <direction>` to change windows in Atom.

I added both `Ctrl-Left` and `Ctrl-left` in the Julia Client whitelist for REPL as my repl is on the right side, and it's working now.

**Comment by Oblynx** [comment]
The same workaround works for me.
