### ISSUE TITLE
[BUG] incorrect hightlighting

### ISSUE THREAD

**Issue by Roger-luo** [JunoLab/Juno.jl#259]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.34.0
- Julia version: 1.1.0
- OS: MacOS 10.14.3
- Package versions:
  - Atom.jl: 0.7.15
  - julia-client: 0.7.13
  - ink: 0.9.14

### Steps to reproduce

```julia
ex = [
    :(function foo end),
    :(foo(x) = x),
    :(foo(x, y::T) where T),
    :(foo(x, y::T) where T = x)]
```

this `end` is not in the same color with function.

PS. seems whatever github uses has this error as well.

**Comment by pfitzseb** [comment]
Very similar to https://github.com/JuliaEditorSupport/atom-language-julia/issues/140, so closing this. And yes, github uses the exact same syntax highlighting rules (just like VSCode).
