### ISSUE TITLE
Feature Request: PyPlot plots in the plots window

### ISSUE THREAD

**Issue by aviks** [JunoLab/Juno.jl#26]

**Comment by ChrisRackauckas** [comment]
It should already do this if you use Plots.jl

**Comment by yha** [comment]
I would still like to see this feature, since Plots.jl is missing a lot of matplotlib features. 
In theory, you can create a plot with Plots.jl and tweak it using PyPlot commands, but in practice I tried this route several times and always failed and fell back on using PyPlot.
