### ISSUE TITLE
[BUG] Debug tooltips obscure the next expression

### ISSUE THREAD

**Issue by timholy** [JunoLab/Juno.jl#264]
It's lovely that the Debugger pane has tooltips---perfect for newcomers. Unfortunately, if you're using them to step repeatedly through several lines of code, your mouse pointer will stay in about the same spot and the tooltip activates. This obscures the also-useful display of the next expression. Now, the same info also appears in the edit window. So I am of two minds:

- one option would be to remove it from the right. Here I worry something would be lost, particularly for source code with long lines (where I don't know what happens to the expression display)
- another would be to insert a little blank space below the controller
- maybe best would be to have the tooltips appear above the bar, if possible?

## Details
- Atom version: 1.33.1
- Julia version: 1.1.0
- OS: Linux
- Package versions:
  - Juno.jl: 0.7.0
  - Atom.jl: 0.8.2
  - julia-client: 0.8.1
  - ink: 0.10.1

**Comment by pfitzseb** [comment]
Good point. I've moved the tooltips to the top with https://github.com/JunoLab/atom-ink/commit/3b68573c551438ebdca737a44431076cbdc87510:

![image](https://user-images.githubusercontent.com/6735977/54870369-ec3eec00-4da5-11e9-8348-a822251e960b.png)
