### ISSUE TITLE
[BUG] First line results not displayed in editor

### ISSUE THREAD

**Issue by braamvandyk** [JunoLab/Juno.jl#268]
## Details
- Atom version: 1.35.1 x64
- Julia version: Version 1.1.0 (2019-01-21)
- OS: Windows 10 Enterprise
- Package versions:
  - Atom.jl: 0.8.2
  - julia-client: 0.8.1
  - ink: 0.10.1

### Steps to reproduce

1. Any two lines of Julia code
2. Execute each with Shift-Enter

Results / check mark is displayed only from second line on down. The first line executes - packages load etc, but the result is not displayed next to the line in the editor. This started with latest update of ink / julia-client.

**Comment by pfitzseb** [comment]
Can't repro this:
![image](https://user-images.githubusercontent.com/6735977/54981175-f4667980-4fa7-11e9-9de7-7e6d6f1542ec.png)
but will try to make the result hiding a bit more lenient.

**Comment by braamvandyk** [comment]
A strange solution to what seems to be an Atom, not Juno bug: closing/re-opening Atom and then clearing the *search* history fixed the problem... I am perplexed, to put it mildly.

**Comment by braamvandyk** [comment]
The problem is back. I can open a saved script. Running the first line with Shift-Enter shows no results, but as soon as I insert a blank line above it, the results are shown. I tested this on a second machine and it seems local to my machine only. I'll uninstall/reinstall julia-client and ink and see if that helps. After that, I think this issue can be closed, since this is apparently not a general problem.

**Comment by pfitzseb** [comment]
Might be fixed with https://github.com/JunoLab/atom-ink/commit/075d6fc48eafd581fe3298144bd2684699e362f1.

**Comment by braamvandyk** [comment]
That does seem to do the trick. Thanks!
