### ISSUE TITLE
Juno seems to aggressively truncate the printing of floating-point values

### ISSUE THREAD

**Issue by Gickle** [JunoLab/Juno.jl#27]
Hello,

Using the Juno's console, summation of two float numbers

`12.5 + 0.00640`

gives the wrong result 

`12.5`

On the over hand,

`print(12.5 + 0.00640)`

gives the correct answer. 

However, in terminal everything is fine.

I asked about this on discord, and I was suggested to make an issue-thread about this. Here is the [link](https://discourse.julialang.org/t/rounding-problem-in-summing-up-to-numbers/815/4) to discord thread.

**Comment by StefanKarpinski** [comment]
Just to clarify, the computation is correct – the issue is with the printing of floating-point values in the console.

**Comment by ChrisRackauckas** [comment]
Yes, just click the number. Things which are rendered via Juno.jl can be interactive.

**Comment by StefanKarpinski** [comment]
In cases where there's no shortage of space, I don't think that truncating output is a good idea. I also feel that when numbers are truncated it would be good to indicate that somehow – e.g. with an ellipsis character.

**Comment by ChrisRackauckas** [comment]
I like the ellipsis idea. But I think this was to help prettify the array and type rendering: otherwise it would get out of hand really quickly. I think having uniformity to the way everything renders is really good too, but  always having visual indicators for things which are clickable is necessary and I would say should be the first goal.

**Comment by pfitzseb** [comment]
https://github.com/JunoLab/atom-julia-client/commit/331fadbd680ce5a6a72b1fe37a94d5d7720970c1:
![trunc](https://cloud.githubusercontent.com/assets/6735977/21063980/bab7e2b0-be58-11e6-91c7-ffd637d0c3ae.gif)
Should be sufficient until someone comes up with something better (not that that'd be very hard...).

**Comment by StefanKarpinski** [comment]
I like this since it can be used in an array display so that you can click a number and see the whole thing (presumably in some sort of overlay box).
