### ISSUE TITLE
[FR] Navigate the callstack in debug-prompt `eval_code`

### ISSUE THREAD

**Issue by timholy** [JunoLab/Juno.jl#270]
It would be nice to be able to move up and down the call stack in a manner that allows commands you enter at the debug prompt to reflect that scope. What about replacing the current `Callstack` with a popup menu?

**Comment by pfitzseb** [comment]
What do you think about making the stack level clickable? That would then also change the prompt to e.g. `3|debug>`. 
I'm not entirely sure how this would interact with stepping though -- changing to a different callstack level should presumably move the stepper widget to the right place, but you couldn't actually step on from there (that should only be possible from the lowest level).

**Comment by timholy** [comment]
Right. Before you step you call `leaf(frame)`, if your internal storage of `frame` reflects what the user clicked.

**Comment by pfitzseb** [comment]
Implemented in https://github.com/JunoLab/atom-ink/commit/ba17078c7fe60a9a87582b249fb54a6107efd456, https://github.com/JunoLab/Atom.jl/commit/ea9c1f1df1f2d15cb0a845371a7c4624aa5100fc, and https://github.com/JunoLab/atom-julia-client/commit/9ad603db777b1a2e7746a9bed5f38dbdb6e5cc27.
