### ISSUE TITLE
Console breaks after using custom module

### ISSUE THREAD

**Issue by MikeInnes** [JunoLab/Juno.jl#272]
The current module can't be found, so it just gets set to `nothing`, and eval breaks. Easy to fix by changing back to main, but confusing.

```julia
julia> using Zygote
ERROR: MethodError: no method matching eval(::Nothing, ::Expr)
Closest candidates are:
  eval(::Module, ::Any) at boot.jl:319

julia> 2+2
ERROR: MethodError: no method matching eval(::Nothing, ::Expr)
Closest candidates are:
  eval(::Module, ::Any) at boot.jl:319
```

Ideally it'd behave the same as an editor, i.e. just be greyed out and eval in `Main` temporarily.

**Comment by pfitzseb** [comment]
Should be fixed by https://github.com/JunoLab/Atom.jl/commit/47202cec2ac17ba7b1a4878b4e67bc4dc7d972af.

**Comment by MikeInnes** [comment]
Great, does that change the UI as well? (When I tried this earlier there was no indication that Zygote wasn't loaded).

**Comment by pfitzseb** [comment]
You shouldn't actually be able to select modules that aren't loaded. That commit makes sure that we correctly find the module from the name, regardless of where it's loaded.

**Comment by MikeInnes** [comment]
The chosen module is sticky between sessions, so the issue comes up once you've chosen one and restarted. That commit fixes the eval issue (though not for the reason you suggest: it just happens to default to `Main` when the module isn't found). Still, though, there's an inconsistency between editor and terminal.

<img width="516" alt="Screenshot 2019-03-28 18 43 25" src="https://user-images.githubusercontent.com/2234614/55184280-a6a96700-5189-11e9-9892-1233d22a2bc0.png">

<img width="514" alt="Screenshot 2019-03-28 18 43 46" src="https://user-images.githubusercontent.com/2234614/55184284-aa3cee00-5189-11e9-8aea-3400f9cd0f89.png">

**Comment by pfitzseb** [comment]
Ah, right, I just didn't know how to repro that.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/4e38c576a91f8a25f5ef4a487dd2c179fd67dff5.

![image](https://user-images.githubusercontent.com/6735977/56076363-8952da80-5dd0-11e9-9562-22cd0d0229c5.png)
