### ISSUE TITLE
[FR] Debugger - Break at Exception - show exception details

### ISSUE THREAD

**Issue by BioTurboNick** [JunoLab/Juno.jl#275]
When using "break on exception", it would be useful for the REPL and/or interface to indicate that an exception caused the break, and to show the exception that triggered the break.

Based on the documentation I guess that the intention is that by advancing you'll find out, but it looks like the debugger just gets stuck if you aren't paying close attention.

It would at least help to turn the next expression red I think.

**Comment by pfitzseb** [comment]
Kinda fixed with https://github.com/JunoLab/Atom.jl/commit/3b8bbe1dfb3343604373b38b85b480ab3ac101a8.
