### ISSUE TITLE
[FR] Make option for console cursor to blink

### ISSUE THREAD

**Issue by benninkrs** [JunoLab/Juno.jl#276]
I know it's just a little thing, but I would like the option to make the console cursor blink (as it does in the editor and in the Julia terminal).  Thanks

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/b627c50942e9c016faada49f538b3f804fc971c3.

**Comment by benninkrs** [comment]
Wow!  That’s some speedy service. Thanks
