### ISSUE TITLE
[BUG] Attempting recurssive debugging breaks debugger.

### ISSUE THREAD

**Issue by BioTurboNick** [JunoLab/Juno.jl#277]
Trying to `@enter` while at the `debug>` prompt leads to the error "ERROR: unlock count must match lock count", and breaks the active debugging session (e.g. the UI buttons no longer work, unable to exit the debugging prompt).

If recurssive debugging isn't intended to be possible, a graceful error that doesn't disrupt the active debugging session would be helpful.

**Comment by pfitzseb** [comment]
Fixed by https://github.com/JunoLab/Atom.jl/commit/f073c8bf5f22f357811ca22186a1dd1cd2d6e6c0
