### ISSUE TITLE
[BUG] Profiler bars missing when editing remotely

### ISSUE THREAD

**Issue by SebastianM-C** [JunoLab/Juno.jl#280]
## Details
- Atom version:1.35.1
- Julia version:1.1.0
- OS:Linux (x86_64-pc-linux-gnu)
- Package versions:
  - Atom.jl:v0.8.3
  - julia-client:0.8.2
  - ink:0.10.2

### Steps to reproduce

1. Connect to a remote server
2. Profile something and click on one of the blocks in the profile view

The correct file is opened on the remote server, but the bars in the source code indicating the time spent per line are missing.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-ink/commit/e1edf1ef024d94973cd84d60af8ce43dab9547af (which also fixes the stepper widget not showing up correctly when debugging in a remote session).
