### ISSUE TITLE
[BUG] Debugger assigment expression just runs

### ISSUE THREAD

**Issue by BioTurboNick** [JunoLab/Juno.jl#282]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.35.1
- Julia version: 1.1.0
- OS: Win10 x64
- Package versions:
  - Atom.jl: 0.8.3
  - julia-client: 0.8.2
  - ink: 0.10.2

### Steps to reproduce

`Juno.@enter a = <expression>` or `@run` fails to start debugging. <expression> executes outside the debugging context.

### Expected behavior

Debugger should operate on <expression>.

### Workaround

Just remove the assignment.

### Suggestion

Either produce a warning or error (if entering <expression> is undesirable for some reason; ambiguity etc.), or treat as equivalent to `a = Juno.@enter <expression>`, which does enter the debugger.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/Atom.jl/commit/f9f098fce6b5c356cc273f33eacfb7c2cabf3e54.
