### ISSUE TITLE
[BUG] "Cannot step after breaking on error" with Break on Exceptions and Ctrl+C interrupt

### ISSUE THREAD

**Issue by BioTurboNick** [JunoLab/Juno.jl#283]
The fix for #275 introduced a check whether the debugger was broke_on_error, which prevents further stepping.

It appears this state is not always cleaned up, as currently every time I enter the debugger, I am unable to step with the error "Cannot step after breaking on error". Stopping and restarting Julia clears it.

The condition appears to occur when I have "Break on Exceptions" turned on, use Juno.@run on some long-running function, and then use Ctrl+C to interrupt it. The code file that was in the middle of executing will appear. Then I am no longer be able to step, and this state remains until Julia is restarted.

An interrupt when stepping with Juno.@enter doesn't seem to have the same issue.

Atom 1.35.1, Julia 1.1, Atom.jl 0.8.3, Win10 x64

**Comment by pfitzseb** [comment]
Sorry about that. Fixed with https://github.com/JunoLab/Atom.jl/commit/57230ad044da5fd34df9c574b627f021b10f30b0.
