### ISSUE TITLE
[BUG] Debugger don't activate innermost stackfram automatically

### ISSUE THREAD

**Issue by baggepinnen** [JunoLab/Juno.jl#287]
Ref https://discourse.julialang.org/t/have-to-click-on-stack-frame-when-debugging-in-juno/

I’m trying out the debugger in Juno for the first time. I notice that when a breakpoint is hit and the prompt turns to `debug>`, the prompt is not automatically in the innermost stack frame, even though this is highlighted in the callstack in the debugger pane. Consequently, I can not evaluate any expressions in the prompt. If I manually click the little number to the left of the innermost stack frame in the callstack, I can evaluate expressions at the debug prompt.

This also happens sometimes when I enter a function, I have to manually click the new innermost stackframe to be able to evaluate code in it.

## Details
- Atom version: 1.35.0
- Julia version: v"1.2.0-DEV.647"
- OS: Fedora 28
- Package versions:
  - Atom.jl: 0.8.4
  - julia-client: 0.8.2
  - ink: 0.10.3

### Steps to reproduce

1. Hit a breakpoint

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/Atom.jl/commit/e80b88b369e251bca1e715da773076993c62a21a.
