### ISSUE TITLE
triple quotes not working correctly in Juno[BUG]

### ISSUE THREAD

**Issue by llbook** [JunoLab/Juno.jl#291]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.35.1 64x
- Julia version:  1.1.0 (2019-01-21)
- OS: windows 8.1
- Package versions:
  - Atom.jl: Atom v0.8.3
  - julia-client: Juno v0.7.0
  - ink:

### Steps to reproduce

1.the following works fine when run in a script or if included in Juno from an external file:

s = """
two
lines"""

but inside Juno it fails to compile. See the included screendump "triple.png" and script/include file triple.jl
[triple.jl.txt](https://github.com/JunoLab/Juno.jl/files/3080708/triple.jl.txt)
![triple](https://user-images.githubusercontent.com/37903417/56142355-d2588980-5f9e-11e9-8f0a-7881c318d75e.png)

2.

**Comment by pfitzseb** [comment]
Juno's mechanism for finding out which code blocks to execute is based on indentation at the moment, so try
```
s = """
  two
  bar
  """
```
instead.
```
