### ISSUE TITLE
[BUG] Autocomplete works in editor but not REPL

### ISSUE THREAD

**Issue by benninkrs** [JunoLab/Juno.jl#294]
### Details
- Atom version: 1.36.0. x64
- Julia version: 1.0.0
- OS: Windows (x86_64-w64-mingw32)
- Package versions:
  - Atom.jl:  0.8.4
  - julia-client: 0.8.3
  - ink: 0.10.4
  - autocomplete-plus: 2.42.0

### Steps to reproduce

1. Open Atom
2. Open Console
3. Start typing in console

Expected behavior:  autocomplete suggestions appear
Actual behavior:  no suggestions appear

**Comment by pfitzseb** [comment]
Just press <kbd>Tab</kbd> to get autocomplete suggestions.

**Comment by benninkrs** [comment]
Hah. Of course. I was just thrown off since the editor behaves differently.

**Comment by pfitzseb** [comment]
Yes, you just get the standard REPL experience. In the future we'll maybe look into providing the same autocompletion menu you get in an editor.
