### ISSUE TITLE
[FR] Bugreport version printing

### ISSUE THREAD

**Issue by baggepinnen** [JunoLab/Juno.jl#297]
When submitting a bugreport for Juno, one should submit versioninfo for a number of packages. It would be nice if there was a Juno command to print all the relevant version info, e.g.,
- Atom version
- Juno version
- julia-client version etc.
- Julia version
Maybe even print the link to the page to create a new issue.

The command could potentially issue a warning if some of the packages (like julia-client etc.) are not up to date and that a new version exists.

**Comment by StevenLi-DS** [comment]
I would suggest adding such a command to the Command Palette and toggle it to copy all the info to the clipboard.

**Comment by pfitzseb** [comment]
Implemented with https://github.com/JunoLab/atom-julia-client/commit/934137659be091eb73d1b4a9141f364cf8884f86 and https://github.com/JunoLab/Atom.jl/commit/a8629b94ce8c95b3d29dc299c950cd5c74b9398a.
