### ISSUE TITLE
[BUG] Missing last tick for @progress

### ISSUE THREAD

**Issue by theogf** [JunoLab/Juno.jl#298]
When using `@progress`, the last iteration is just ignored. 
For example, when having nested loops with `@progress`, the progress for the outside loop will disappear first, before the inside nested loops are over.
Not a big problem in itself but aesthetically unpleasant. :stuck_out_tongue: 

## Details
- Atom version: 1.36.0 x64
- Julia version: 1.1.0
- OS: Linux x64
- Package versions:
  - Atom.jl: v0.8.5
  - julia-client: 0.8.3
  - ink: 0.10.4

### Steps to reproduce
```julia
@progress for i in 1:3
    @progress name="$i" for j in 1:3
    sleep(0.5)
    end
end
```

**Comment by Infi-Knight** [comment]
- OS: Macos Mojave 10.14.4 
- Julia version: 1.1.0 
- Atom version: 1.36.1 x64
- julia-client: 0.8.3
- ink: 0.10.5
- Atom.jl: v0.8.4
I was able to reproduce this on my system too (You have an extra $ sign in string interpolation BTW).
