### ISSUE TITLE
[FR] Compiled mode while debugging

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/Juno.jl#299]
Sometimes I'm stepping through some code where some lines I'm stepping over take a really long time when interpreted. It would be great to support something like [Debugger.jl's Compiled Mode](https://github.com/JuliaDebug/Debugger.jl#compiled-mode). Perhaps a "next line  (compiled)" button in the toolbar that would compile and run the next line (obv. breakpoints wouldn't work).

**Comment by pfitzseb** [comment]
I feel like a checkbox would make more sense, no?

**Comment by ssfrr** [comment]
I guess it depends on how often one would be switching between the two evaluation modes. If the compilation overhead is high then I can imagine using interpreted stepping most of the time and then just doing a compiled step for things that take a long time, which takes more clicks if it's a mode checkbox.

I'd be happy either way though.

**Comment by pfitzseb** [comment]
Implemented a toggle in https://github.com/JunoLab/atom-julia-client/pull/558.
