### ISSUE TITLE
Integration with Weave.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Juno.jl#30]
@mpastell 's Weave.jl is a great framework for literate programming in Julia. I think both Juno and Weave can be made even better by pairing up together, kind of like RMarkdown/KnitR. If creating a Weave file was easy and it could evaluate to some rendered pane (instead of a separate browser window) as a preview, and then buttons from Juno could save it out as a PDF, it could be a really nice system for generating papers from Julia projects.

**Comment by mpastell** [comment]
I agree that this is a good idea. I have written https://atom.io/packages/language-weave which does syntax highlighting for Weave documents and supports running code using `ctrl-enter`.

**Comment by cdsousa** [comment]
I suggest that current cell evaluation/navigation shortcuts could be also used to evaluate/navigate the document code blocks.

**Comment by pfitzseb** [comment]
Yeah, that's a good idea. I do think we should create a separate atom package for the more sophisticated features (live preview comes to mind, but toolbar buttons for `weave` and maybe `tangle` as well) that integrates with Juno.

**Comment by MikeInnes** [comment]
Yeah, that would be the right idea. Juno is meant to be built on and this would make a good test case.

I should check out Weave in more detail and see what we can do, but in general if folks want to try this out and we can help with Juno integration, let us know.
