### ISSUE TITLE
[BUG] No stack traces with Julia 1.2

### ISSUE THREAD

**Issue by marius311** [JunoLab/Juno.jl#305]
Sorry if I'm getting ahead of myself, but have been using the 1.2 release branch and thought I'd just point out that when you guys eventually get to upgrading to that, stack traces don't seem to be working. E.g. here is Julia release-1.2/8a84ba5018, Atom.jl v0.8.5, atom-julia-client v0.8.3:

![image](https://user-images.githubusercontent.com/1510968/58438052-ae9a6000-8081-11e9-8b66-d490e633e761.png)

and the expected behavior, with Atom/atom-julia-client same as above but Julia 1.1.0

![image](https://user-images.githubusercontent.com/1510968/58438104-ff11bd80-8081-11e9-827a-f64af3c2b2cc.png)

**Comment by pfitzseb** [comment]
Dup of https://github.com/JunoLab/Juno.jl/issues/242.
