### ISSUE TITLE
Plots through ssh port forwarding throws an error

### ISSUE THREAD

**Issue by Balinus** [JunoLab/Juno.jl#31]
Hello, 

I'm now using mainly Juno through a ssh external process. Everything's working fine except for plotting. When I'm trying the plot I get: 

```julia
julia> junoC() #function that does the using "Juno;Juno.connect(port)"

julia> using Plots
WARNING: Method definition show(IO, Base.Multimedia.MIME{:text/plain}, Plots.Plot{#B<:Any}) in module Plots at /home/proy/.julia/v0.5/Plots/src/output.jl:195 overwritten in module Main at /home/proy/.julia/v0.5/Plots/src/output.jl:288.

julia> plot(randn(400,1))
WARNING: No working GUI backend found for matplotlib.
```
The plot exists, it just can't be shown.

I can provide more info (just don't know which one you need). Packages are all up-to-date (tagged versions only though). On my local machine, Juno/Atom is also up-to-date.

**Comment by ChrisRackauckas** [comment]
Do you get this on the remote machine when not through Juno? This is a very common problem for PyPlot on clusters. Using GR gets around this problem.

**Comment by Balinus** [comment]
oh....thanks!

you made me remember that I used a small bash script to semi-automate the connection to the external process. In the script I forgot to forward the X session with the "-X" option on the ssh connection. 

Solved by adding the appropriate flag:
`ssh -X -R portServer:localhost:localport server.net`

It now works with pyplot() backend and gr() backend. Haven't tested with other backends.
