### ISSUE TITLE
[BUG] Working directory not set at kernel start

### ISSUE THREAD

**Issue by yha** [JunoLab/Juno.jl#316]
Similar to #239.

### Details
- Atom version: 1.38.2
- Julia version: 1.1.1
- OS: Windows 10
- Package versions:
  - Atom.jl: 0.8.7
  - julia-client: 0.8.9
  - ink: 0.10.10

### Steps to reproduce

In a new script/cell:
```
println(pwd())
println(pwd())
```
execute cell (alt-enter) when *no* Julia kernel is running. First line shows atom's executable path. Only second line shows the first project's path.
It looks like it's actually the printing that triggers the path change, e.g.,
```
pwds = [(pwd()) for _=1:10]
foreach(println, pwds)
println(pwd())
```
Prints the atom's path 10 times, then the project's path. The path is also correctly set after a call to `sleep` or `yield`, but not after other long-running commands like `using Plots`.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/52f2e74475bffef8f9043cd2cffd66a0e8bcbc67.
