### ISSUE TITLE
[BUG] Evaluation in Editor freezes Atom occasionally

### ISSUE THREAD

**Issue by CarpeNecopinum** [JunoLab/Juno.jl#320]
## Details
- Atom version: 1.34, 1.39.0
- Julia version: 1.1.1 (2019-05-16)
- OS: Linux 4.19, Debian 10
- Package versions:
  - Atom.jl: v"0.8.7"
  - julia-client: 0.8.9
  - ink: 0.10.10

### Steps to reproduce

1. Create a julia script with: 
```
import GLFW
win = GLFW.CreateWindow(1920, 1080, "Foo")
```

2. run both lines with Ctrl-Enter

### Alternative:

1. Connect an external julia REPL to Juno

This freezes the Editor for ~20 seconds. Similar freezes occasionally occur on running other code lines, but the GLFW example above turned out to be the most reliable in freezing Atom. Entering them into the REPL and running them there works just fine.

- The Julia process itself runs just fine in the background (tested by rendering an animation).
- adding `;` to the end of the second line to suppress outputs doesn't help
- removing revise from my startup.jl didn't help
- while atom is frozen, there is no unuasual CPU load (everything still in single-digit percentages)
- deleting `~/.atom` and `~/.julia` and setting up everything fresh didn't help

**Comment by pfitzseb** [comment]
Do you have the workspace pane open? If so, try closing that as well. But yeah, I think I'll just implement some straightforward output size limiting.

**Comment by CarpeNecopinum** [comment]
Not sure which one is the "workspace pane", but I have closed everything besides the REPL and the script itself and it's still freezing.

Also forgot to mention before, but while atom is frozen, there is no unuasual CPU load (everything still in single-digit percentages).

**Comment by pfitzseb** [comment]
Hm, interestingly enough I can't repro this, neither on Linux nor on Windows.

**Comment by CarpeNecopinum** [comment]
Setting everything up on a different machine rn, maybe some system update broke everything.

**Comment by CarpeNecopinum** [comment]
Okay, so it worked on the other machine. Not sure why, in theory they should be running the same software (both Debian 10.0, same selection of installed packages), so I'm still wondering how that difference comes to be.

**Comment by CarpeNecopinum** [comment]
Connecting an external julia REPL also freezes Juno while leaving the REPL itself responsive. The freeze takes its regular ~20 seconds, even when the REPL is immediately killed after connecting, so the issue appears to be fully on the side of the atom plugin.

**Comment by CarpeNecopinum** [comment]
Okay, found the issue. I noticed that what was hanging atom was when a computation finished while atom was not in focus (GLFW.CreateWindow automatically gives focus to the new window), which usually triggers the "Evaluation finished"-notification. Then I found that `notify-send` also hangs. Apparently the freeze was due to the notification timing out.

**Starting a notification-daemon (`dunst` in my case) fixed the issue.**

Thanks a lot for your quick help!

**Comment by pfitzseb** [comment]
Cool, glad you figured it out!

**Comment by pfitzseb** [comment]
OS level notifications are disabled completly in the latest Juno release because they were causing crashes on Mac and didn't really seem to work on other platforms.

**Comment by VolkerSmits** [comment]
> 
> 
> Okay, found the issue. I noticed that what was hanging atom was when a computation finished while atom was not in focus (GLFW.CreateWindow automatically gives focus to the new window), which usually triggers the "Evaluation finished"-notification. Then I found that `notify-send` also hangs. Apparently the freeze was due to the notification timing out.
> 
> **Starting a notification-daemon (`dunst` in my case) fixed the issue.**
> 
> Thanks a lot for your quick help!

I think I have a similar problem. When I hit SHIFT + ENTER to evaluate a single code line, Juno sometimes freezes. Could you explain me your solution in a bit more detail? Because I´m quite new in Julia and I didn´t understand your solution.

**Comment by CarpeNecopinum** [comment]
Juno used to send a notification that says "evaluation finished" or something similar. On Linux notifications are handled by a notification-daemon (dunst is an example for one). When no notification daemon is running, Juno used to time out (after a long wait).

You can check if your notification daemon works using `notify-send` on the console.

Though as pfitzseb mentioned, notifications are now disabled in Juno, so this really shouldn't be the issue.

**Comment by VoSiLk** [comment]
Ok thanks. I have opened a new issue #405

**Comment by szcf-weiya** [comment]
Thanks for the hints by @CarpeNecopinum and @pfitzseb, I had a similar problem when I use `Ctrl+Enter` to run `imshow()`, which freezes at
```julia
Dict{String,Any} with 4 entries:
```
while the normal output should be 
```julia
Dict{String,Any} with 4 entries:
  "gui"         => Dict{String,Any}("window"=>GtkWindowLeaf(name="", parent, wi…
  "roi"         => Dict{String,Any}("redraw"=>50: "map(clim-mapped image, input…
  "annotations" => 3: "input-2" = Dict{UInt64,Any}() Dict{UInt64,Any} 
  "clim"        => 2: "CLim" = CLim{RGB{Float64}}(RGB{Float64}(0.0,0.0,0.0), RG…
```
and it would be OK if I copy the `imshow()` into the REPL. Inspired by 
> OS level notifications are disabled completly in the latest Juno release because they were causing crashes on Mac and didn't really seem to work on other platforms.

then I updated Juno.jl from v0.7.2 to the latest v0.8.1, and Atom.jl from v0.12.8 to v0.12.9, the problem disappeared. 

BTW, I want to mention an interesting/weird phenomenon, the output is still
```julia
Dict{String,Any} with 4 entries:
```
instead of the complete info like in the normal case, although I do not care about the output.

**Comment by CarpeNecopinum** [comment]
> BTW, I want to mention an interesting/weird phenomenon, the output is still
> Dict{String,Any} with 4 entries:
> instead of the complete info like in the normal case, although I do not care about the output.

There should be a little `>` before the output. When you click it, it "unfolds" the output and then you should be able to see the entries.

**Comment by szcf-weiya** [comment]
@CarpeNecopinum I would say there is nothing because I set the result display mode as "Display results in the REPL", not in the code file (I have used such feature before). But if I change the display mode to appear in the code file, there is indeed a little `>` before the output, and I can see the entries by clicking it.
