### ISSUE TITLE
[BUG] Debugger pane does not seem to work

### ISSUE THREAD

**Issue by TorkelE** [JunoLab/Juno.jl#321]
## Details
- Atom version: 1.37.0
- Julia version: 1.1.1
- OS: Ubuntu 18
- Package versions:
  - Atom.jl: v0.8.7
  - Juno v0.7.0
  - Debugger v0.5.0
  - julia-client: (Unable to find instruction on how to determine this)
  - ink: (Unable to find instruction on how to determine this)

### Steps to reproduce

1. Click "Show Debugger Pane" to the left to get it to show up.
2. Write `using Debugger` into the console
3. Write `Juno.@enter split("Hello, world", isspace)` into the console
4. Write `o` to get the util.jl window to show up.
5. Press any of the blue bottons in the Debugger Pane.
6. A red window saying "You need to be debugging to do that." shows up
(I am basically following the instructions in https://docs.junolab.org/latest/man/debugging/)
Here I think I have entered the debugger, but that does not seem to be the case, probably it is I that have done something wrong, but I do believe I have followed the instructions correctly.
![debugger_error](https://user-images.githubusercontent.com/18099310/60530335-6b6e8500-9cf0-11e9-87c5-8846acd38574.png)

**Comment by pfitzseb** [comment]
You're not supposed to use Debugger.jl at all, which is why the docs explicitly mention `Juno.@enter`.

So instead leave out steps 2 and 4 and actually do what you said you're doing in step 3, and you should be good to go.

**Comment by TorkelE** [comment]
Thank you,
I have also tried simply entering `Juno.@enter split("Hello, world", isspace)` (full text, including the `Juno.` in the beginning) into the Juno Console. However, nothing happens. I've waited for several minutes and the screen still looks  like this:
![debugger_error_2](https://user-images.githubusercontent.com/18099310/60591021-6283bf00-9d95-11e9-8818-bc5820867af7.png)
From here I've tried to writing `o` and `n`, or click on the buttons in the debugger pane, to no avail.

**Comment by pfitzseb** [comment]
Can you go to the Atom settings and take a look at the `Packages` tab? You should see `julia-client` and `ink` under the `Community Packages` header, complete with version numbers. If there's an update button for either of those packages then use that or type `apm update` into a terminal.

**Comment by TorkelE** [comment]
I updated both packages and now it works well.
Thanks a lot.

**Comment by pfitzseb** [comment]
Cool, glad that this is solved now.
