### ISSUE TITLE
[BUG] Julia no longer running in Atom

### ISSUE THREAD

**Issue by tueboesen** [JunoLab/Juno.jl#323]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.38.2
- Julia version: 1.1.1
- OS: Windows 10

### Steps to reproduce

0. I'm fairly new in Julia, so this might be a trivial issue and I just can't figure it out
1. I had julia/juno/atom all installed and working, but decided to update them all to the latest version. After the installation my .jl files got greyed out (looks like atom no longer recognizes .jl files) and my julia console is gone. (See picture for how it looks now)

I still have julia installed and can run it, so that doesn't seem to be the issue, and since atom is also running I'm posting this here since that seems to be the most likely cause of the problem. Note that I have tried to uninstall both julia and atom and reinstalling them again, but the problem still persists.

![ss](https://user-images.githubusercontent.com/22527117/60748509-9866a600-9f43-11e9-9ee3-ce5dd1f347e6.png)

Any help would be greatly appreciated

**Comment by pfitzseb** [comment]
You're running into [this](http://docs.junolab.org/latest/man/faq/#Juno-doesn't-work-properly-after-some-Atom-packages-were-updated.-What-do-I-do?-1), so please try the steps described there (or simply try uninstalling and installing the julia-client package through Atom's settings, although I'm not 100% sure that'll work).
