### ISSUE TITLE
[BUG] no string displayed in the editor but printed in REPL

### ISSUE THREAD

**Issue by StevenLi-DS** [JunoLab/Juno.jl#324]
## Details
- Atom version: 1.38.2
- Julia version: 1.1.1
- OS: Windows 10
- Package versions:  
  - Atom.jl: 
  - julia-client: 0.8.9
  - ink: 0.10.10

### Steps to reproduce

In a self-defined function, I wanna the function to print out the strings, but when I run the function only a check mark appeared and no strings displayed in the editor but in the REPL

``` julia
function printlyrics()
    println("I'm a lumberjack, and I'm okay.")
    println("I sleep all night and I work all day.")
end

printlyrics()

```
![image](https://user-images.githubusercontent.com/33796896/60761387-5148e580-a015-11e9-81a4-63818ca0da20.png)

**Comment by StevenLi-DS** [comment]
Ok it seems like it has something to do with how `println` behaves in the IDE, which does not display any strings at all. This might be undesirable when you need to print out some results.

**Comment by pfitzseb** [comment]
This is just the difference between *returning* a string and *printing* it. The inline results only display returned values (and `println` returns `nothing`, which is represented by a checkmark in the editor), and everything you print goes to `stdout`.
There's a [feature request](https://github.com/JunoLab/Juno.jl/issues/302)  for adding a setting to change this behavious, so I'm closing this issue.
