### ISSUE TITLE
[BUG] Format Code creates wrong function name

### ISSUE THREAD

**Issue by feanor12** [JunoLab/Juno.jl#331]
Formatting changes the function name and removes T.

## Details
- Atom version: 1.38.2
- Julia Version 1.1.1 Commit 55e36cc308 (2019-05-16 04:10 UTC)
- OS: Win 10
## Packages:
- Atom v0.8.8
- Juno v0.7.0
- julia-client 0.8.10
- ink 0.10.11
- language-julia: 0.19.1

### Steps to reproduce

1. open a file with:
``` julia
struct PolarComplex{T<:Real} <: Number
    R::T
    θ::T
    PolarComplex(R::T, θ::T) where T <: Real =
        new{T}(R, mod(θ,2π))
end
```

2. click format code on the toolbar
3. get:
``` julia
struct PolarComplex{T <: Real} <: Number
    R::T
    θ::T
    PolarComplex(R::T, θ::T) where T <: Real =
        new{}(R, od(θ, 2π))
end
```

**Comment by aviatesk** [comment]
Umm I can't reproduce this.

And it doesn't even seems to be from DocumentFormat.jl, which we use internally.
```julia
using DocumentFormat
"""
struct PolarComplex{T <: Real} <: Number
    R::T
    θ::T
    PolarComplex(R::T, θ::T) where T <: Real =
        new{T}(R, mod(θ, 2π))
end
""" |> format |> println
```
```
struct PolarComplex{T <: Real} <: Number
    R::T
    θ::T
    PolarComplex(R::T, θ::T) where T <: Real =
        new{T}(R, mod(θ, 2π))
end
```

**Comment by feanor12** [comment]
If I take the file [format.txt](https://github.com/JunoLab/Juno.jl/files/3421909/format.txt), rename it to format.jl, open it in Juno and select Run All i get 
``` 
struct PolarComplex{T <: Real} <: Number
    R::T
    θ::T
    PolarComplex(R::T, θ::T) where T <: Real =
        new{T(R, md2pi(θ))
end
```

When I select the content and paste it into the REPL I get
```
struct PolarComplex{T <: Real} <: Number

    R::T

    θ::T

    PolarComplex(R::T, θ::T) where T <: Real =

                  new{T}(R, mod2pi(θ))

end
```

**Comment by pfitzseb** [comment]
Our new code formatter makes sure that the original and reformatted code parse the same, so things like this shouldn't happen anymore.
