### ISSUE TITLE
``Error: Installing “julia-client@0.8.10” failed.''

### ISSUE THREAD

**Issue by AndrewQuinn2020** [JunoLab/Juno.jl#332]
I created a new installation of Atom and tried to install the `uber-juno` package. What pops up is this dialogue:

```
Juno: Error installing package julia-client

Please check your internet connection, or report this to
    http://discuss.junolab.org
and we'll try to help.
    –––
Error: Installing “julia-client@0.8.10” failed.
```

Trying to install `Julia-client` by itself results in the following failed output:

```
Installing “julia-client@0.8.10” failed.Hide output…

> node-pty-prebuilt@0.7.6 install C:\Users\Andre\AppData\Local\Temp\apm-install-dir-119623-19380-aqs276.k216m\node_modules\julia-client\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\Andre\AppData\Local\Temp\apm-install-dir-119623-19380-aqs276.k216m\node_modules\julia-client\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\Andre\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\Andre\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false ) 

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Python37\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Andre\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Andre\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Andre\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Andre\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Andre\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\Andre\AppData\Local\Temp\apm-install-dir-119623-19380-aqs276.k216m\node_modules\julia-client\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Andre\AppData\Local\Temp\apm-install-dir-119623-19380-aqs276.k216m\package.json'
npm WARN apm-install-dir-119623-19380-aqs276.k216m No description
npm WARN apm-install-dir-119623-19380-aqs276.k216m No repository field.
npm WARN apm-install-dir-119623-19380-aqs276.k216m No README data
npm WARN apm-install-dir-119623-19380-aqs276.k216m No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Andre\.atom\.apm\_logs\2019-07-23T16_42_35_752Z-debug.log
```

**Comment by AndrewQuinn2020** [comment]
Looking at the line

```
gyp ERR! stack Error: Can't find Python executable "C:\Python37\python.EXE", you can set the PYTHON env variable.
```

suggests I need Python installed to do this.

I installed [Python 3.7.4](https://www.python.org/downloads/), making sure to check the PATH option in the executable.

![2019-07-23 11_46_02-Python 3 7 4 (32-bit) Setup](https://user-images.githubusercontent.com/53230903/61730758-a720cb80-ad3f-11e9-9caf-2ed9d2bb28f1.png)

I then closed and reopened Atom. This was unsuccessful in fixing the `uber-juno` issue, as I still saw the same error message pop up.

![2019-07-23 11_48_18-untitled — Atom](https://user-images.githubusercontent.com/53230903/61730834-d7686a00-ad3f-11e9-8571-ca58cd05a111.jpg)

**Comment by AndrewQuinn2020** [comment]
After this, I attempted to reinstall `julia-client` by itself, at which point I saw the same error message pop up:

`gyp ERR! stack Error: Can't find Python executable "C:\Python37\python.EXE", you can set the PYTHON env variable.`

Going to this location, however, shows that `C:\Python37\python.EXE` was indeed installed at the right location. I decided to restart my computer and see if that helped any.

**Comment by AndrewQuinn2020** [comment]
Restarting did not seem to help. 😒

```
> node-pty-prebuilt@0.7.6 install C:\Users\Andre\AppData\Local\Temp\apm-install-dir-119623-7048-dtd4pz.32zr\node_modules\julia-client\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\Andre\AppData\Local\Temp\apm-install-dir-119623-7048-dtd4pz.32zr\node_modules\julia-client\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\Andre\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\Andre\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false ) 

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Python37\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Andre\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Andre\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Andre\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Andre\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Andre\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\Andre\AppData\Local\Temp\apm-install-dir-119623-7048-dtd4pz.32zr\node_modules\julia-client\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Andre\AppData\Local\Temp\apm-install-dir-119623-7048-dtd4pz.32zr\package.json'
npm WARN apm-install-dir-119623-7048-dtd4pz.32zr No description
npm WARN apm-install-dir-119623-7048-dtd4pz.32zr No repository field.
npm WARN apm-install-dir-119623-7048-dtd4pz.32zr No README data
npm WARN apm-install-dir-119623-7048-dtd4pz.32zr No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Andre\.atom\.apm\_logs\2019-07-23T17_03_26_101Z-debug.log
```

**Comment by aviatesk** [comment]
Hi, can you try the same process with Python v2.7 ?
It would help the build succeed.

**Comment by AndrewQuinn2020** [comment]
I then decided to search the line

`gyp ERR! configure error`

and came across [this post by David Sottimano](https://davidsottimano.com/fix-windows-npm-node-gyp-error-for-various-npm-modules/), which suggests running the following two lines from the command line:

```
npm install --global --production windows-build-tools
npm install --global node-gyp
```

So I tried that.

I got the error message

```
npm' is not recognized as an internal or external command,
operable program or batch file.
```

So I went to [NodeJS](https://nodejs.org/en/download/) and installed using their Windows executable, with standard settings.

![2019-07-23 12_10_12-Microsoft Edge](https://user-images.githubusercontent.com/53230903/61732303-ebfa3180-ad42-11e9-8d87-2ca312789d8a.jpg)

Apparently, if you wish to use Juno on Windows 10, you must first invent the universe. 😂

After installing NodeJS, I closed and re-opened the Command Line, and used ``node --version`` and ``npm --version`` to double check that they were both installed correctly.

```
C:\Users\Andre>node --version
v10.16.0

C:\Users\Andre>npm --version
6.9.0
```

Bingo.

Now, `npm install --global --production windows-build-tools` seems to be working correctly. However, I had to close the CMD and re-open it as an administrative PowerShell:

```

C:\Users\Andre>npm install --global --production windows-build-tools

> windows-build-tools@5.2.2 postinstall C:\Users\Andre\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js



Downloading python-2.7.15.amd64.msi
[============================================>] 100.0% of 20.25 MB (13.5 MB/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\Andre\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[============================================>] 100.0% of 1.12 MB (1.12 MB/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\Andre\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Please restart this script from an administrative PowerShell!
The build tools cannot be installed without administrative rights.
To fix, right-click on PowerShell and run "as Administrator".
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-build-tools@5.2.2 postinstall: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@5.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Andre\AppData\Roaming\npm-cache\_logs\2019-07-23T17_14_28_462Z-debug.log
```

I opened PowerShell as an administrator.

![2019-07-23 12_15_40-Microsoft Edge](https://user-images.githubusercontent.com/53230903/61732636-a2f6ad00-ad43-11e9-860c-997ddbcd5ace.jpg)

I then ran

`npm install --global --production windows-build-tools`

... Which ended up installing Python 2.7 along with a bunch of other stuff, just like @aviatesk suggested! Maybe I should have just listened 🤦‍♂️

I am now waiting for the NPM installation to finish up. **Once I've figured this out, I'm going to post a cleaned-up step by step of what I did.** Please be patient.

**Comment by pfitzseb** [comment]
While it's really cool you figured this out so far, this *really* should not be necessary and is only a fallback solution.
One of our dependencies *should* be downloaded as a binary, but that seems to have failed for you (maybe because of your antivir software). As a fallback we'll try the dependency on your machine, but you obviously need to have the necessary build tools, and we can't realistically expect anyone to have those.

**Comment by AndrewQuinn2020** [comment]
`npm install --global --production windows-build-tools` finished up, so I then ran `npm install --global node-gyp` and then opened Atom. **It worked!**

> [T]his really should not be necessary and is only a fallback solution.

True, but I'm still going to write a step-by-step for the fallback solution, because it worked.

**Comment by pfitzseb** [comment]
Awesome! We should maybe put that up on docs.junolab.org for now, until I've figured out the build problems.

**Comment by AndrewQuinn2020** [comment]
# Problem

You're on Windows 10, and you are trying to install the `uber-juno` package for Atom. But it fails with this message:

```
Juno: Error installing package julia-client

Please check your internet connection, or report this to
    http://discuss.junolab.org
and we'll try to help.
    –––
Error: Installing “julia-client@0.8.10” failed.
```

Furthermore, when you try to install `julia-client` by itself, you get error messages similar to what is occurring in the first part of my post.

# Fallback Solution

As @pfitzseb stated, this is a fallback solution. But it worked for me, so I'm going to post it here anyway.

1. [Install NodeJS](https://nodejs.org/en/download/).
2. Open Windows PowerShell **as an administrator.**
3. In PowerShell, type in `npm --version``. If you get a version number like `6.9.0`, then NPM installed correctly, and you may proceed.
4. In PowerShell, run `npm install --global --production windows-build-tools`. This will take some time; go get some coffee and come back in 10 or 15 minutes. You might have to hit Enter a few times to make the installation proceed.
5. Run `npm install --global node-gyp`. This should be considerably faster. 🙂
6. Close and reopen Atom. If the `uber-juno` installation restarts and completes successfully, you're done.
7. If not, go to Settings > Install (you can open Settings with `Ctrl+,`), uninstall and reinstall `uber-juno` manually. If it completes successfully, you're done.

**Comment by yha** [comment]
I now encountered a similar error, which happened suddenly after Atom restart. The `julia-client` package had already been working fine before this restart (apart from #326).
After restart, Atom prompted to rebuild `julia-client`, claiming something was compiled against a different version of node. Rebuild failed due to not finding python; uninstalling and reinstalling the package failed with the same error.

Is there any way to try working around it without admin permissions, which are unfortunately a bit of a hassle to get in my work machine? Installing Atom and `uber-juno` didn't require admin privileges so far.

**Comment by pfitzseb** [comment]
Yeah, the workaround is to revert to Atom 1.38. Sorry about that -- one of our dependencies broke with the new Atom version (and I thought I had more time to fix that).
Will try to fix this asap (also see e.g. [here](https://discourse.julialang.org/t/atom-1-39-wont-build-julia-client/26696)).

**Comment by yha** [comment]
Thanks. Installing 1.38 did the trick after a full Atom uninstall (uninstalling from the control panel and deleting `%HOMEPATH%/.atom`, `%HOMEPATH%/AppData/Local/atom` and `%HOMEPATH%/AppData/Roaming/Atom`).

**Comment by asprionj** [comment]
You can just download the ZIP version (e.g. atom-windows.zip) from [release 1.38.2](https://github.com/atom/atom/releases/tag/v1.38.2), unzip it somehwere and run atom.exe. It will use your config (packages, settings, etc.) as a "native" installation, but not auto-update itself :wink:

And, once the problem is fixed, you can switch back to your actually installed Atom without re-installing anything.

**Comment by tfburns** [comment]
Thanks, this worked for me on Windows 10 Home X64 (Version 10.0.17134 Build 17134).
One thing to note was that after running `npm install --global --production windows-build-tools` my PowerShell hanged with the last output saying "installing Python 2.7" or some such thing. I force quite the PowerShell and re-run the command, which it did and then completed with 1 extra update.

**Comment by holgerteichgraeber** [comment]
Any news on this? I seem to have a similar problem (haven't used atom for the past few weeks, and now got suddenly this error). Would love to have this fixed for good instead of relying on a fallback solution.

**Comment by holgerteichgraeber** [comment]
Cross-tagging this from juliadiscourse: https://discourse.julialang.org/t/update-on-julia-client-0-9-4-fails/27653 
Is this the same issue?

**Comment by asprionj** [comment]
> Cross-tagging this from juliadiscourse: https://discourse.julialang.org/t/update-on-julia-client-0-9-4-fails/27653
> Is this the same issue?

Nope, this one here was with julia-client 8.10 and Atom 1.38 to 1.39 upgrade. But probably the same temporal workaround does the job as well?

**Comment by Ifihanolusheye** [comment]
@AndrewQuinn2020 thanks so much, it worked!

**Comment by Impulse98** [comment]
@AndrewQuinn2020 thank you so much. I have been struggling to get it to work since February and ended up using Visual Studio Code.
