### ISSUE TITLE
[BUG] Custom keybinding for julia-client:run-file not working

### ISSUE THREAD

**Issue by lnacquaroli** [JunoLab/Juno.jl#333]
When I change the `keymap.cson` for `julia-client:run-file` with another specific keybindings it does not work. It does work for the `julia-client:run-block` though.

## Details
- Atom version: 1.39.0
- Julia version: 1.1.1
- OS: Debian testing
- Package versions:
  - Atom.jl: 0.8.8
  - julia-client: 0.8.10
  - ink: 0.10.11

**Comment by aviatesk** [comment]
The command was migrated into `julia-cliant: run-all` after Juno v0.8.10.

Please refer to this PR for why, and setting keybindings for it should work.

https://github.com/JunoLab/atom-julia-client/pull/563

**Comment by lnacquaroli** [comment]
Thanks, sorry for the noise.
