### ISSUE TITLE
[BUG] Cannot open atom with julia-client 0.8.12-alpha enabled

### ISSUE THREAD

**Issue by gerycruz** [JunoLab/Juno.jl#334]
Cannot open atom 1.39.1 x64 on OSX Mojave 10.14.5 with julia-client 0.8.12-alpha enabled. 

Atom window hangs and reloading doesn't fix the issue. 

Disabling julia-client using apm fixes the problem.

**Comment by pfitzseb** [comment]
0.8.12-beta2 should fix this.
