### ISSUE TITLE
Debugger not working properly

### ISSUE THREAD

**Issue by ntjess** [JunoLab/Juno.jl#335]
From the 'Juno' documentation page, I saw the following:
Open a console and type Juno.@enter split("Hello, world", isspace). You should see something like the following (without the red annotations):
![image](https://user-images.githubusercontent.com/23620506/61973567-506ef800-afb2-11e9-9790-e184abc4939e.png)

However, this does not happen for me. I can run the command, but I don't see any debugging interface. The only noticeable difference is a new set of variables in my workspace, but I can't set breakpoints in my own functions or use debugging controls. See the attached .gif.

The tutorial doesn't indicate I needed to do something else first to make debugging behave properly.
![1554d4ce-825c-42ea-b2bf-b25d7a7f0967](https://user-images.githubusercontent.com/23620506/61974163-df304480-afb3-11e9-9571-0141ed8f5de2.gif)

**Comment by pfitzseb** [comment]
Did you make sure all packages are up-to-date? It's kinda suspicious that the `@enter` call never returns.

**Comment by ntjess** [comment]
I performed a fresh install of [Julia Pro](https://juliacomputing.com/products/juliapro.html) which included the Juno component. Updating my packages made no difference.

I believe a related issue is keeping me from being able to set breakpoints in any files. Doing so gives the error:
![image](https://user-images.githubusercontent.com/23620506/61980778-b2852880-afc5-11e9-9eef-fb42e95ed3ed.png)

**Comment by pfitzseb** [comment]
I expect this is happening because JuliaPro ships with a fairly old version of Juno, which does still have a couple of bugs.

**Comment by ntjess** [comment]
You were right, after installing Juno separately I encountered no problems.
