### ISSUE TITLE
Editor crash while installing julia-client from uber-juno on macOS 10.14.6

### ISSUE THREAD

**Issue by mrkite92** [JunoLab/Juno.jl#336]
Systematic crash while attempting to install uber-juno and dependencies in Atom.

Crash report attached
[Atom Helper_2019-07-26-164641_macprojb.crash.gz](https://github.com/JunoLab/Juno.jl/files/3441134/Atom.Helper_2019-07-26-164641_macprojb.crash.gz)

**Comment by pfitzseb** [comment]
Can you try to manually install the latest version of julia-client (should be 0.8.12-beta2)?

**Comment by mrkite92** [comment]
Hi,
From the Atom installer (after complete reinstall of Atom from scratch), I tried to install that version of julia-client. Then failed into the dependency ink install, related to issue https://github.com/JunoLab/atom-ink/issues/207

**Comment by pfitzseb** [comment]
What you link is an error with using `ink`, not with installing it. Try closing Atom and typing
```
apm uninstall ink
apm uninstall julia-client
apm install ink
apm install julia-client
```
in a terminal.

**Comment by mrkite92** [comment]
OK, it works, thanks for the hint. 
Package update in REPL works in Atom for Julia 1.1.1.
apm install uber-juno did fine from termlnal, Atom now properly set after some automatic dependency installs.
Thanks for the workaround!
JB
