### ISSUE TITLE
[BUG] Toolbar popups show mac shortcuts keys on Windows

### ISSUE THREAD

**Issue by adamsiembida** [JunoLab/Juno.jl#339]
I installed Juno on Windows 10 using the 64-bit binary for the latest (non-beta) release. Even although I am on Windows, I am getting mac shortcuts using `Cmd` instead of `Ctrl` when I mouse over the sidebar. Windows doesn't have a `Cmd` key so I believe this is a bug.

## Details
- Atom version: 1.39.1
- Julia version: 1.1.1, 64-bit
- OS: Windows 10, 64-bit
- Package versions:
  - Atom.jl: 0.8.8
  - julia-client: 0.8.12-beta2
  - ink: 0.10.11

### Steps to reproduce

1. Install Julia, Windows 10, 64-bit binary.
2. Install Juno.
3. Mouse over the shortcuts in the toolbar.

Shortcuts like Save and Open correctly show `Ctrl+S` and `Ctrl+O`, while most of the julia specific shortcuts show `Cmd` instead of `Ctrl`.

For example, Stop Julia shows `Cmd+J Cmd+K`, Show Console shows `Cmd+J Cmd+O`, however Interrupt Julia correctly shows `Ctrl+C`.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/f545fcdaf18b87eaba7f88979a264e2856822701.
