### ISSUE TITLE
[FR] expose command to activate/deactivate the whole julia-client interface

### ISSUE THREAD

**Issue by daviehh** [JunoLab/Juno.jl#345]
For people who use atom other than julia, it could be helpful to include such command so that one can call it from the atom command palette (or programatically) to show/hide the julia-client-specific ui elements, etc. when switching between languages other than julia. 

Currently, temporarily disabling julia-client only removes the toolbar (if enabled) but does not close open panes such as repl/plot/workspace etc.

**Comment by pfitzseb** [comment]
So you'd want something like "Close all Juno specific pane items" as a command? That seems easy enough to implement. We already have the opposite of that (`Restore Default Layout`).

**Comment by pfitzseb** [comment]
There isn't. I suppose we could try adding that though.
