### ISSUE TITLE
Julia Client REPL not working[BUG]

### ISSUE THREAD

**Issue by Cavenfish** [JunoLab/Juno.jl#347]
When I try to use julia-client in Atom this error pops up in the REPL console. 
```
At line:1 char:159
+ ... 657 -jlpath "julia" -jlargs --depwarn=yes,-O3,--color=yes,-i,,"`"C:\U ...
+                                                                  ~
Missing expression after ',' in pipeline element.
At line:1 char:159
+ ... 57 -jlpath "julia" -jlargs --depwarn=yes,-O3,--color=yes,-i,,"`"C:\Us ...
+                                                                 ~
Missing argument in parameter list.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpression
```
It used to work fine until recently.

**Comment by pfitzseb** [comment]
Can you give the debug info from 
![](https://aws1.discourse-cdn.com/business5/uploads/julialang/original/2X/6/693a6e7d47f33916960b676c0ee114d7d349c05d.png)
?

**Comment by Cavenfish** [comment]
```
# Atom:
Version: 1.40.1
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.2.0",
  "v8": "6.6.346.32",
  "uv": "1.20.3",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "64",
  "nghttp2": "1.29.0",
  "napi": "3",
  "openssl": "1.1.0h",
  "electron": "3.1.10",
  "chrome": "66.0.3359.181"
}
# julia-client:
Version: 0.9.4
Config:
{
  "firstBoot": false,
  "juliaOptions": {
    "bootMode": "Basic",
    "startupArguments": [
      ""
    ]
  },
  "uiOptions": {
    "docsDisplayMode": "inline",
    "enableMenu": true,
    "layouts": {
      "defaultPanes": {
        "documentation": false
      },
      "openDefaultPanesOnStartUp": false
    }
  }
}


# ink:
Version: 0.10.12
Config:
undefined


# uber-juno:
Version: 0.2.0
Config:
{
  "disable": true
}


# language-julia:
Version: 0.19.1
Config:
undefined


# language-weave:not installed


# indent-detective:not installed


Could not connect to Julia.
```

**Comment by pfitzseb** [comment]
I think you have a single space in `julia-client > Settings > Julia Options > Additional Julia Startup Arguments`. Make sure to clear that and you should be good to go.

**Comment by Cavenfish** [comment]
It was already empty. I tried to use that option to override the automatic startup commands but still use the same default ones (ie: i wrote the default commands there) and it worked. 

I'm not sure why but i think the default startup commands for my installed julia-client had an empty command argument in it that was causing problems.

**Comment by pfitzseb** [comment]
Can you try putting e.g. `-i` in there, just to be sure?

**Comment by Cavenfish** [comment]
That's what I did. It only has `-i` there now, and it works fine.

So more likely than the default settings being the root cause of the bug I think its my computer not recognizing the `-O` or `--depwarn` commands.

**Comment by pfitzseb** [comment]
https://github.com/JunoLab/atom-julia-client/commit/f1b6c516e06b91ebcfa6f75d73918e36c3ea3f7b should help with this.
