### ISSUE TITLE
`@progress` macro does not work with given name

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#35]
The documentation for `@progress` macro is :
`@progress [name] for i = ...` (from the Juno documentation webpage)

However this does not work for me. I've tried the combinations `"particle loop"`, `["particle loop"]` and the problem is that the progress bar, even though it works, it doesn't show a name. It shows a blank instead. See the attached figure to understand better what I mean.

It is important to tell you that I've tried `Pkg.checkout("Juno")` at 2/2/2017 and this did not solve the problem.
![Issue](https://cloud.githubusercontent.com/assets/19669089/22549568/3af442d4-e94c-11e6-8054-0bb2dffc5ec8.PNG)

EDIT: The length of the given string does not matter.

**Comment by pfitzseb** [comment]
Right, this was fixed with https://github.com/JunoLab/atom-julia-client/commit/6a1ce81610b0615f5126900d592d18e8e1d6da7d, so it should work on julia-client master.
