### ISSUE TITLE
[BUG] Minor syntax highlight bug

### ISSUE THREAD

**Issue by marius311** [JunoLab/Juno.jl#355]
- Atom version: 1.40.1
- Julia version: 1.2
- OS: Ubuntu 19.04
- Package versions:
  - Atom.jl: 0.10.1
  - julia-client: 0.10.1
  - ink: 0.11.0

### Steps to reproduce

The following seems to syntax highlight incorrectly (on Github as well!):

```julia
if true
    py"""
    1+2
    """
end
```

It works if the py string is not indented.

**Comment by pfitzseb** [comment]
I think this is fixed on atom-language-julia#master:
![image](https://user-images.githubusercontent.com/6735977/65408798-8a0f8400-dde6-11e9-8eb7-48ba92fbc2aa.png)
