### ISSUE TITLE
[BUG] String spanning multilines is not correctly evaluated

### ISSUE THREAD

**Issue by aviatesk** [JunoLab/Juno.jl#367]
## Details
- Atom version: v1.40.1
- Julia version: 1.2.0
- OS: Windows
- Package versions:
  - Atom.jl: master
  - julia-client: master
  - ink: master

### Description

```jl
str = """
I can't be evaluated
"""
```

select the code above and run it via e.g. `julia-client: run-block`, and it produces a syntax error `syntax: incomplete: invalid string syntax`, even though this code is valid in Julia syntax.
(actually `str = """` is only sent to julia)

Well, obviously https://github.com/JunoLab/atom-julia-client/pull/611 changed the behaviour and skips multiline strings even when it's supposed to be evaluated.

**Comment by bilderbuchi** [comment]
@aviatesk @pfitzseb I fear this bug has regressed (or I have found another trigger) using julia-client 0.11.3, julia 1.3.1.

The bottom code snippets all work correctly when pressing "run all".
However, the following fails with
```
syntax: incomplete: invalid string syntax
```
when pressing shift-enter in the line with `minimal_breaks`:
``` 
minimal_breaks = """
#dfdf
#bla"""
```
I have narrowed the trigger condition down to the last line with the `"""` starting with `#` like here.

The following works (notice the line break before the triple quote) and gives `"#bla\n"` as expected.
```
minimal_works = """
#dfdf
#bla
"""
```

Curiously, in the faulty string, a shift-enter is _only_ registered when pressed in the first line of the string definition of `minimal_breaks`, but it is registered in any line of the`minimal_works` definition.

Is this the correct place or should I open a new issue?

**Comment by aviatesk** [comment]
hm we're retrying to improve this in [another PR](https://github.com/JunoLab/atom-julia-client/pull/661) but still haven't found a valid solution yet.

**Comment by bilderbuchi** [comment]
OK, thanks. I hope the two examples I gave at least can be used as good test cases to verify the changes against. I'd offer to help, but I don't speak JS/CS, and really basic Julia at this point. :-/
