### ISSUE TITLE
[BUG] collapsed array summary is misleading

### ISSUE THREAD

**Issue by JeffBezanson** [JunoLab/Juno.jl#371]
## Details
- Atom version: 1.39.1
- Julia version: 1.2.0
- OS: linux
- Package versions:
  - Atom.jl: 0.9,1
  - julia-client:
  - ink:

When an inline-evaluated expression yields an array, the collapsed summary is something like `Pair{Int64,Char}[3]` (because the length is 3). However that is misleading, because we never use that syntax in julia. In fact it gives an error that 3 can't be converted to a Pair. Instead, I would suggest just using the type, or the result of `summary(x)`, which in this case is
```
3-element Array{Pair{Int64,Char},1}
```

**Comment by aviatesk** [comment]
I don't think we need to show (exactly) syntactically correct things in the inline results in general, but atst I agree with `Pair{Int64,Char}[3]` can appear weird to someone (the same would go for `Set` as well under the current implementation).

As for the consistency with the actual syntax, we may want to replace `→` with `=>` in `Dict`s renderings.

**Comment by pfitzseb** [comment]
Yeah, I think people have criticized that before. https://github.com/JunoLab/Atom.jl/pull/182 should make things more consistent.
