### ISSUE TITLE
[BUG] Inline evaluation very slow with some workspace pane contents

### ISSUE THREAD

**Issue by yha** [JunoLab/Juno.jl#372]
## Details
- Atom version: 1.40.1 x64
- Julia version: 1.1.1
- OS: Windows 10
- Package versions:
  - Atom.jl: 0.10.1
  - julia-client: 0.10.1
  - ink: 0.11.0

### Steps to reproduce

The smallest reproducing example I could find is still pretty complex. Step through the following with the workspace pane open:
```
using TestImages

n = 100    # no bug for n = 10
lighthouse = testimage("lighthouse");
frames = [lighthouse for _=1:n]
function f()
    cache = Dict()
    i -> get!(cache, i) do
        try
            frame = frames[i]
        catch e
            e
        end
    end
end

g = f()
e = g(n+1);
"foo"
```
The inline display of "foo" takes about a minute to show, and subsequent inline displays are equally slow.

**Comment by yha** [comment]
I can reproduce here with `Atom#master` as well.

> So is `frames` the problem here?

The problem disappears when `frames` is smaller. But it also disappears with various other changes, such as if the exception is not triggered (`g(n)` instead of `g(n+1)`), or if a different exception is returned which doesn't point into `frames`, or if the closure is not assigned to a variable (`e=f()(n+1)`) (or when the workspace pane is closed, as I mentioned).

**Comment by pfitzseb** [comment]
Hm, weird. This is what it looks like for me with `n = 1000`:
![Peek 2019-09-25 12-29](https://user-images.githubusercontent.com/6735977/65593244-5bcda800-df90-11e9-97fa-c6047e4d4132.gif)

**Comment by yha** [comment]
Here's what I see. Evaluation of `"foo"` takes about 40 seconds here. If I don't stop at the `g=f()` line, it's stuck already at the next line.

![out](https://user-images.githubusercontent.com/4170948/65621132-d5cf5280-dfcb-11e9-9870-c4c19df6a94d.gif)

I've also reproduced this on another machine.

**Comment by pfitzseb** [comment]
Ok, turns out this problem is very specific to Julia 1.1. Turns out that `string(g)` prints everything it closes over, including `frames`...

Fixed with https://github.com/JunoLab/Atom.jl/commit/0d5ec769a8590d869965b0755d8a6e8e4e3eb1ff.
