### ISSUE TITLE
Methods list display is out of order

### ISSUE THREAD

**Issue by mbauman** [JunoLab/Juno.jl#375]
When viewing a list of methods (`methods(f)`), the displayed list is out of order from within the pop-up result display.

I’m on my phone right now, but I can get a MWE later if needed.

**Comment by aviatesk** [comment]
What did you mean by "the pop-up result display" ?
The datatips that would appear on hover ?

**Comment by pfitzseb** [comment]
Fixed by https://github.com/JunoLab/Atom.jl/pull/189.
