### ISSUE TITLE
[BUG] Toolbar icons missing

### ISSUE THREAD

**Issue by AndiMD** [JunoLab/Juno.jl#380]
Hi,

I am not sure if this is an issue with uber-juno or the toolbar.
After a fresh install of Atom with uber-juno, the toolbar has 4 icons missing: Start Remote Julia Process, Interrupt Julia, Stop Julia, Run All

The missing spaces are still clickable, so this is just a visual problem, not a functional one.

Thanks.

## Details
- Atom version: 1.40.1
- Julia version: 1.2.0 x64
- OS: Kubuntu 18.04
- Package versions:
  - Atom.jl: 0.10.1
  - julia-client: 0.10.1
  - ink: 0.11.1

### Steps to reproduce

1. Install Julia, Atom, uber-juno
2. Agree to change the layout

![image](https://user-images.githubusercontent.com/24719218/66141733-78a75280-e604-11e9-8f73-4c47beeb1b2a.png)

**Comment by humanfactors** [comment]
I'm having the same issue on a fresh install on Windows 10 1903.

Atom versoin 1.40.1
Julia version: 1.2.0 x64

**Comment by pfitzseb** [comment]
Fixed by https://github.com/JunoLab/atom-julia-client/pull/626.
