### ISSUE TITLE
[FR] Print errors in console for in-line evaluation

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#381]
Inline evaluation is super cool. The only problem I Have is when the evaluation errors. I've come to realize that reading the error messages from the inline floating buble is not so easy, and I constantly copy paste the command to the console so that I can read the error message better.

It would be very helpful if you allow an option that errors are printed in both inline as well as console. Something similar exists but for *notifications* instead of the console. I don't like notifications at all though, and they are totally not convenient since they actually dissapear once read!

**Comment by pfitzseb** [comment]
> I've come to realize that reading the error messages from the inline floating buble is not so easy, and I constantly copy paste the command to the console so that I can read the error message better.

Why is that? Could we just improve the inline errors instead?

> It would be very helpful if you allow an option that errors are printed in both inline as well as console. Something similar exists but for notifications instead of the console. I don't like notifications at all though, and they are totally not convenient since they actually dissapear once read!

Should be easy enough to implement an option for this, I think.

**Comment by Datseris** [comment]
> Why is that? Could we just improve the inline errors instead? 

Hm, I don't know. Probably you can't:

I always have my inline evaluation to be floating to the right instead of below (because doing it below changes the height of my document). But then, it is only visible once I have my mouse over it, which is not helpful given that to fix the error I obviously have to type in a different window.

Then the error is completely hidden, like so:

![hidden](https://user-images.githubusercontent.com/19669089/66201864-a348e800-e6a4-11e9-810d-8d0e5d9b0290.PNG)

**Comment by Datseris** [comment]
Notice that hidding the error is even worse, in fact I recall the the suggestion to hide this came from me :P
