### ISSUE TITLE
[BUG] Invoking `workspace` handler on Lazy.jl package never stops running

### ISSUE THREAD

**Issue by aviatesk** [JunoLab/Juno.jl#382]
Please search existing issues to avoid duplicates.

### Details
- Atom version: master
- Julia version: v1.2
- OS:
- Package versions:
  - Atom.jl: master
  - Lazy.jl: v0.14.0
  - julia-client: master
  - ink: master

### notes

Once this happens, this will continue to happen even after restarting Julia process.

**Comment by pfitzseb** [comment]
Dup of https://github.com/MikeInnes/Lazy.jl/issues/90

**Comment by aviatesk** [comment]
oops, sorry.
