### ISSUE TITLE
[BUG] SVG plots look weird

### ISSUE THREAD

**Issue by aviatesk** [JunoLab/Juno.jl#386]
Atom.jl, julia-client, ink: v0.11.0
Plots.jl: v0.27.0

```jl
using Plots
gr()
plot(rand(10, 3), fmt = :svg)
```
will yield something like

![image](https://user-images.githubusercontent.com/40514306/66390506-c1487c80-ea05-11e9-8d93-ab3bf043ecff.png)

**Comment by pfitzseb** [comment]
Fixed by https://github.com/JunoLab/atom-julia-client/commit/24fc0748528a40b06ce1983737895184c14b5bed -- turns out `decaffeinate` removed that semi-colon for some reason...

**Comment by aviatesk** [comment]
Thanks ;)

> turns out decaffeinate removed that semi-colon for some reason...

haha, any kind of decaffeinate is always hard
