### ISSUE TITLE
[BUG] `input` hangs in Atom

### ISSUE THREAD

**Issue by heliosdrm** [JunoLab/Juno.jl#387]
`Juno.input()` gets stuck when called from Atom. In the REPL it works.

The code of `Juno.input` is:

```julia
input(prompt = "") = (print(prompt); isactive() ? Main.Atom.input() : readline())
```

This makes me think that the issue is actually with `Atom.input`, since `readline` works both in Atom and REPL, whereas `Atom.input()` hangs in both.

## Details
- Atom version: 1.40.1
- Julia version: 1.1.0
- OS: Windows 10
- Package versions:
  - Atom.jl: v0.10.2
  - julia-client: 0.11.0
  - ink: 0.11.2

**Comment by pfitzseb** [comment]
Fixed by https://github.com/JunoLab/atom-julia-client/commit/22a723cedcefcffcae0f75e14a49711f365949ea.
