### ISSUE TITLE
[BUG] Revise not loaded on latest version

### ISSUE THREAD

**Issue by SebRollen** [JunoLab/Juno.jl#389]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.40.1
- Julia version: 1.2.0
- OS: osX
- Package versions:
  - Atom.jl: 0.11.0
  - julia-client: 0.11.1
  - ink: 0.11.2

### Steps to reproduce

1. Have `using Revise` in your `~/.julia/config/startup.jl` file
2. run `Revise` in your Juno REPL

If I open Julia from a terminal, `Revise` gets loaded from my startup file, but after the latest updates to `Atom.jl`, the same doesn't work in Juno

**Comment by SebRollen** [comment]
Strangely, other things defined in my `startup.jl` such as `OhMyREPL` and some `ENV` declarations _are_ loaded

**Comment by SebRollen** [comment]
Apologies, managed to solve this issue myself. Using the [recommended](https://timholy.github.io/Revise.jl/stable/config/#Using-Revise-by-default-1) 
```julia
atreplinit() do repl
    try
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
    catch
    end
end
```
does not work for me, but if I switch to just using `using Revise`, everything works

**Comment by SebRollen** [comment]
On further testing, it seems like even though the name `Revise` is now available in my repl, the revise functionality isn't actually working. Re-opening

**Comment by aviatesk** [comment]
You have some error log ? If you wrap it in `try` block, please remove that and report back to us.

But most probably, the error you're facing is already fixed https://github.com/timholy/Revise.jl/pull/369 and/or https://github.com/JunoLab/Atom.jl/commit/81167e6e17f6033d664122c5e2fc08fff393c92c.
Then the temporal fix is to `] add Revise#master`

**Comment by SebRollen** [comment]
I modified my startup file to look like
```julia
atreplinit() do repl
    try
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
    catch e
        rethrow(e)
    end
end
```
and the error message I get is 
```julia
InitError: KeyError: key "evalrepl" not found
during initialization of module Revise
```
which does indeed look like that second link you sent. Will try to update to the master branch of `Revise`

**Comment by SebRollen** [comment]
@aviatesk, that worked, thank you for your help!
