### ISSUE TITLE
[FR] Save Tabs Position

### ISSUE THREAD

**Issue by Jahyrm** [JunoLab/Juno.jl#390]
Every time I open the Atom IDE again.

The tabs of the juno packages are somewhere else and not where I left them.

It would be great if they stay in the place of the last session. Because it is very annoying to fix the workplace every time.

**Comment by aviatesk** [comment]
We already have an option to do that.
Go and remove the checkmark under `julia-client` -> `UI Options` -> `Layout` 
![image](https://user-images.githubusercontent.com/40514306/66447926-c4398080-ea8a-11e9-8786-0a67db436aef.png)
