### ISSUE TITLE
[BUG] Internal Error: UndefVarError: st not defined

### ISSUE THREAD

**Issue by KSepetanc** [JunoLab/Juno.jl#391]
I have just installed everything completely fresh. (Atom, Julia, Juno, Ipopt, JuMP and PowerModels)
I get error when running code:

Julia Client – Internal Error

UndefVarError: st not defined
(::getfield(Atom, Symbol("##137#142")){String,String,Module})() at eval.jl:135
withpath(::getfield(Atom, Symbol("##137#142")){String,String,Module}, ::String) at utils.jl:30
withpath at eval.jl:47 [inlined]
#136 at eval.jl:130 [inlined]
with_logstate(::getfield(Atom, Symbol("##136#141")){String,String,Module}, ::Base.CoreLogging.LogState) at logging.jl:395
with_logger at logging.jl:491 [inlined]
#135 at eval.jl:129 [inlined]
hideprompt(::getfield(Atom, Symbol("##135#140")){String,String,Module}) at repl.jl:85
macro expansion at eval.jl:128 [inlined]
macro expansion at dynamic.jl:24 [inlined]
(::getfield(Atom, Symbol("##134#139")))(::Dict{String,Any}) at eval.jl:117
handlemsg(::Dict{String,Any}, ::Dict{String,Any}) at comm.jl:164
(::getfield(Atom, Symbol("##19#21")){Array{Any,1}})() at task.jl:268

## Details
- Atom version: 1.40.1
- Julia version: 1.2 64bit
- OS: Windows 10 64bit
- Package versions:
  - Atom.jl: 0.11
  - julia-client: 0.11.1
  - ink: 0.11.2

-Juno: 0.7.2
-PowerModels: 0.12.5
-Ipopt: 0.6.0
-JuMP: 0.20.0

### Steps to reproduce

1. Install fresh

**Comment by aviatesk** [comment]
https://github.com/JunoLab/Atom.jl/commit/e741e96a960d0c21a8370a1f877dac5a154302dc should fix this.
