### ISSUE TITLE
[BUG] With Juno 0.11 plots no longer scale to plot pane

### ISSUE THREAD

**Issue by Sleort** [JunoLab/Juno.jl#392]
After updating to Juno 0.11 (Juno.jl v0.7.2), plots no longer scale to the plot pane, but rather to the "global" Atom window size. I.e. only a fraction of the plot is shown by default:

![Screenshot from 2019-10-09 11-15-00](https://user-images.githubusercontent.com/29743212/66447079-14fbaa00-ea88-11e9-9c60-05af98abb89d.png)
![Screenshot from 2019-10-09 11-28-46](https://user-images.githubusercontent.com/29743212/66447084-175e0400-ea88-11e9-8146-3d32496edbac.png)

## Details
- Atom version: 1.40.1
- Julia version: 1.2.0
- OS: Ubuntu 19.04
- Package versions:
  - Atom.jl: v0.11.0
  - julia-client: 0.11.1
  - ink: 0.11.2

### Steps to reproduce

1. Start Juno and make sure that the plot pane is some fraction of the program window.
2. Run 
```
using Plots
plot(sin)
```
either in the REPL or in a .jl file.

**Comment by aviatesk** [comment]
Can't repro this. Which version of Plots.jl are you using, exactly ?

**Comment by Sleort** [comment]
That's strange... I'm using Plots.jl v0.27.0

**Comment by pfitzseb** [comment]
Probably solved by https://github.com/JunoLab/atom-ink/pull/233.

**Comment by Sleort** [comment]
Yes, that solved the problem. Thank you!

A minor annoyance, though: contrary to previously, the rescaling to the plot plane is now rather visible on my computer:
![Peek 2019-10-10 09-46](https://user-images.githubusercontent.com/29743212/66530527-176f0a00-eb43-11e9-827f-62c78e0750e6.gif)
Would it be possible to render the plot only after it has been scaled, thus avoiding this glitch?

**Comment by pfitzseb** [comment]
Possibly. My priority was to get the fix out as soon as possible though.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-ink/commit/e1e3074d3b8dca91aca766eb9d72d4459ba20b67. Still a bit janky, but whatever.
