### ISSUE TITLE
[BUG] Juno: Error installing package julia-client

### ISSUE THREAD

**Issue by vietanhle0101** [JunoLab/Juno.jl#394]
Please search existing issues to avoid duplicates.
Juno: Error installing package julia-client

## Details
- Atom version:
- Julia version:
- OS:
- Package versions:
  - Atom.jl:
  - julia-client:
  - ink:

### Steps to reproduce

1.
2.

**Comment by zahrano** [comment]
Had the same issue recently and updating atom fixed it.

**Comment by pfitzseb** [comment]
Juno explicitly requires Atom 1.40.1 or 1.39.
