### ISSUE TITLE
[FR] Decouple progress frontend

### ISSUE THREAD

**Issue by tkf** [JunoLab/Juno.jl#400]
IIUC, due to Juno-specific check in `@progress` macro implementation, code using `@progress` can only work inside Juno:

https://github.com/JunoLab/Juno.jl/blob/554707e93034b847621b8df7236d59f7718dc778/src/progress.jl#L105-L106

The specification in [`Juno.progress` docstring](http://docs.junolab.org/latest/man/juno_frontend/#Progress-Meters-1) also does not specify that using `LogLevel(-1)` is crucial.

These are issues I noticed while writing a ProgressMeter-Logging bridge [ProgressMeterLogging.jl](https://github.com/tkf/ProgressMeterLogging.jl) and adding a frontend support in my package https://github.com/tkf/Transducers.jl/pull/63.  I think a cleaner solution may be having a base package with a spec and a reference implementation of frontend progress macros and functions.

What do you think? Is it a good approach to decouple progress logging interface (frontend API and specification documentation) from Juno?

**Comment by pfitzseb** [comment]
Yes, definitely. 

> does not specify that using `LogLevel(-1)` is crucial.

It isn't for Juno's implementation -- any logging level higher or equal to `-1` works (or higher than the `min_enabled_level` of the global logger). Should still be documented though.

**Comment by tkf** [comment]
OK, I created https://github.com/tkf/ProgressLogging.jl. Do you want to move it to https://github.com/JunoLab?

**Comment by pfitzseb** [comment]
Sure, why not -- invited you to the org. Thanks for splitting out the code!

**Comment by tkf** [comment]
I got a permission error when I tried to transfer it to JunoLab so I transferred the repository to you.  Can you move it to JunoLab?

**Comment by pfitzseb** [comment]
Hm, weird. Should be transferred now.

**Comment by tkf** [comment]
Thanks!
