### ISSUE TITLE
[BUG] Slow down when using Julia 1.3rc4

### ISSUE THREAD

**Issue by xiaodaigh** [JunoLab/Juno.jl#403]
There seem to be slow downs using Julia v1.3rc4.

The slowdown doesn't appear in Julia v1.2 nor v.1.3.rc3

## Details
- Atom version: 1.40.1 x64
- Julia version: 1.3rc4
- OS: Windows 10
- Package versions:
  - Atom.jl: v0.11.1
  - julia-client: 0.11.2
  - ink: 0.11.5

### Steps to reproduce

1. Open Juno and set Julia executable to 1.3rc**4**, then run `using CSV` which takes 10 seconds
2. Open Juno and set Julia executable to 1.3rc**3**, then run `using CSV` which takes 2 seconds

**Comment by pfitzseb** [comment]
Pretty sure that's a base issue: https://github.com/JuliaLang/julia/issues/33615

**Comment by xiaodaigh** [comment]
> Doesn't the same slowdown occur when not in Juno ? i.e. want to clearfy this is not caused by CSV.jl.

Actualy, in normal Julia REPL it's fine at 2 seconds. Only in Juno `using CSV` 10 seconds. I double-checked. It's Julia 1.3 rc4 in REPL and Juno
