### ISSUE TITLE
[BUG] Julia Run Buttons gone dark after upgrade 

### ISSUE THREAD

**Issue by SvenSerneels** [JunoLab/Juno.jl#409]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.41.0
- Julia version: 1.2.0
- OS: Win10
- Package versions:
  - Atom.jl: 0.11.2
  - julia-client: 0.11.2
  - ink: 0.11.5
- Juno: 0.7.2 
- uber-juno: 0.3

### Steps to reproduce

1. Since upgrade to `uber-juno` version 0.3, the buttons to run, interrupt and stop Julia, and the 'Run All' button in the Julia toolbar have gone dark. They are still functional, though. 
![image](https://user-images.githubusercontent.com/37901756/67489805-27591480-f640-11e9-8e0f-30d2a61c9ad7.png)

**Comment by aviatesk** [comment]
Updating tool-bar package should fix this.
