### ISSUE TITLE
Add ability to add a prompt for `input`

### ISSUE THREAD

**Issue by haberdashPI** [JunoLab/Juno.jl#41]
Juno's `input` method isn't very useful without a prompt to tell the user *what* they should type in. But, if you call the following...

```julia
print("Enter a number: ")
result = input()
```

...immediately entering a number doesn't work, because the cursor has moved away. You have to click next to the little page icon. Confusingly, there is an additional line that gets printed with a `>` symbol, which the user can easily mistake as the location where a number should be entered, but will instead execute the line as a julia command. 

This can be sort of fixed with the following approach.

```julia
print("Enter a number: ")
sleep(0.5)
result = input()
```

Most of the time, the cursor will now be located in the correct spot, and the user experience is much more intuitive. However, this doesn't work all the time.

**Comment by pfitzseb** [comment]
The above commit together with the master branches of ink and julia-client fix this issue for me -- the cursor consistently is in the input field after calling `input("Foo")`.

**Comment by haberdashPI** [comment]
That's great to hear!! I'll check it out. Thanks for your hard work!
