### ISSUE TITLE
Warning: Atom.jl: unrecognised message updateeditor. [BUG]

### ISSUE THREAD

**Issue by mkarikom** [JunoLab/Juno.jl#414]
The following displays over and over in the REPL

julia> ┌ Warning: Atom.jl: unrecognised message updateeditor.
└ @ Atom ~/.julia/packages/Atom/BVajq/src/comm.jl:171

## Details
- Atom version: 1.40.1
- Julia version: 1.2.0
- OS: Ubuntu 18.04
- Package versions:
  - Atom.jl: 
  - julia-client:
  - ink:

### Steps to reproduce

1. start atom
2. open a repl
3. start julia
4. A = zeros(2,2), enter

**Comment by aviatesk** [comment]
update Atom.jl package.
