### ISSUE TITLE
[BUG] Julia-client fields look shut and unaccessible.

### ISSUE THREAD

**Issue by xanfus** [JunoLab/Juno.jl#416]
##  Details
- Atom version: 1.41.0
- Julia version: 1.3.0-rc4.1
- OS: Ubuntu MATE 18.04.3.
- Package versions:
  - Atom.jl: 0.11.2
  - julia-client: 0.11.2
  - ink: 0.11.5

### Steps to reproduce

1. Enter number of threads into "Number of threads" field.
2. Check number of threads with Threads.nthreads()
3. Kill session.
4. Start session.
5. Review field values.
![Screenshot from 2019-10-28 09-47-41](https://user-images.githubusercontent.com/5682375/67658310-4d492680-f96a-11e9-8f97-a170f7819609.png)
Oh, number of threads have updated 24->48, just like i intended. I wonder if i'm right about hyper-threading.

**Comment by pfitzseb** [comment]
How did you install Atom? Pretty sure that only happens for "unofficial"  builds.

**Comment by xanfus** [comment]
> How did you install Atom? Pretty sure that only happens for "unofficial" builds.

I do only download .deb right from showcase link or from releases' page. Then i do "dpkg -i".

**Comment by pfitzseb** [comment]
Hm, interesting. Regardless, this isn't a problem with Juno but rather with Atom, so please open an issue [here](https://github.com/atom/atom/issues) or [here](https://github.com/atom/settings-view/issues).

**Comment by marius311** [comment]
This also happened to me right after updating to julia-client 0.11.3 I think. I'm also on Atom 1.41.0 and also installing standard versions from .deb on Ubuntu 19.10. FWIW, if you double-click right on the thin collapsed line it opens back up, and sometimes that even survivs an Atom reboot. 

Is there not a chance it is indeed a julia-client thing? I don't see this with any of ~10 other random plugins I just checked.

**Comment by xanfus** [comment]
I confirm, double-LMB does open collapsed field. I'm not sure if i ever tried it before, sorry.
