### ISSUE TITLE
[FR] Debugger simpler Step into Function 

### ISSUE THREAD

**Issue by rveltz** [JunoLab/Juno.jl#417]
Hi,

I have been using the debugger part of Juno lately and it works very well!

However, I quickly needed a way to Step into function without going through evaluating arguments. This is especially cumbersome when the number of (keyword) arguments is large. Is there a way to Step into Function in such a way?

Thank you for your work,

Best regards

**Comment by aviatesk** [comment]
It would be helpful if you open an issue on https://github.com/JuliaDebug/JuliaInterpreter.jl, since Juno is internally calling JuliaInterpreter's debug commands according to user input via our GUI, and imo this option is better to be implemented in the upstream.
