### ISSUE TITLE
[FR] Play button for plot pane

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JunoLab/Juno.jl#418]
For skimming many plots it would be nice to show them automatically one after another at a configurable framerate.
Also needs the ability to stop again.

**Comment by aviatesk** [comment]
It would be technically possible, but I'm curious in what situation you need to generate so many plots instead of just create a single gif ?

**Comment by BeastyBlacksmith** [comment]
My usecase would be to see simulation results in memory and decide afterwards, if I want to store them or if I have to adjust something. Also this way you have the ability to view the overall results quickly and then inspect interesting regions frame by frame.
I mean, ideally i could then specify a range of plots that I can export in a video format.

**Comment by pfitzseb** [comment]
Honestly, this feels a bit like an anti-feature to me. If you want a video, make a video. If you want to quickly scrub through a bunch of plots in a video-like manner, use Interact to get a slider:
```julia
using Plots, Interact

x = -10:10
data = []
for i in 1:100
    global data
    push!(data, i^2 .*x./100 .+ x.^3)
end

@manipulate for i in 1:100
    plot(x, data[i])
end
```
produces
![interact_plots](https://user-images.githubusercontent.com/6735977/68327504-c44e8f80-00cd-11ea-8687-8c91362ed067.gif)

**Comment by BeastyBlacksmith** [comment]
Nice idea! What about having the slider by default (beside the buttons)?

**Comment by aviatesk** [comment]
The slider is provided by Interact.jl, I think it should be created by each user.
