### ISSUE TITLE
[BUG] when start julia and add Pkg

### ISSUE THREAD

**Issue by wzz1999** [JunoLab/Juno.jl#420]
Please search existing issues to avoid duplicates.

## Details
- Atom version:1.41.0
- Julia version:1.2.0 and 1.1.0(both version can not start)
- Package versions:
  - julia-client: 0.11.3
  - ink: 0.11.6

### Steps to reproduce

1.Hold on tight while we are installing some packages for you.
This should only take a few seconds...

Activating environment at `C:\Users\wzz\.julia\environments\v1.2\Project.toml`
   Cloning default registries into `C:\Users\wzz\.julia`
   Cloning registry from "https://github.com/JuliaRegistries/General.git"

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (i
n their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6ea84f5d -- _libssh2_wincng_bignum_bits at C:\Users\wzz\A
ppData\Local\Julia-1.2.0\bin\libssh2.dll (unknown line)
in expression starting at C:\Users\wzz\.atom\packages\julia-client\script\boot_repl.jl:1
_libssh2_wincng_bignum_bits at C:\Users\wzz\AppData\Local\Julia-1.2.0\bin\libssh2.dll (unknown line)
kex_method_diffie_hellman_group_exchange_sha256_key_exchange at C:\Users\wzz\AppData\Local\Julia-1.2
.0\bin\libssh2.dll (unknown line)
_libssh2_kex_exchange at C:\Users\wzz\AppData\Local\Julia-1.2.0\bin\libssh2.dll (unknown line)      
libssh2_session_handshake at C:\Users\wzz\AppData\Local\Julia-1.2.0\bin\libssh2.dll (unknown line)  
_git_ssh_setup_conn at C:\Users\wzz\AppData\Local\Julia-1.2.0\bin\libgit2.DLL (unknown line)
git_smart__connect at C:\Users\wzz\AppData\Local\Julia-1.2.0\bin\libgit2.DLL (unknown line) 
git_remote_fetch at C:\Users\wzz\AppData\Local\Julia-1.2.0\bin\libgit2.DLL (unknown line)   
git_clone at C:\Users\wzz\AppData\Local\Julia-1.2.0\bin\libgit2.DLL (unknown line)
clone at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.
2\LibGit2\src\error.jl:99
#clone#131 at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdli
b\v1.2\LibGit2\src\LibGit2.jl:580
#clone at .\none:0 [inlined]
#clone#4 at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\
v1.2\Pkg\src\GitTools.jl:120
#clone at .\none:0 [inlined]
#130 at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2
\Pkg\src\Types.jl:1003
shred! at .\secretbuffer.jl:184
clone_or_cp_registries at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share
\julia\stdlib\v1.2\Pkg\src\Types.jl:1002
clone_or_cp_registries at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share
\julia\stdlib\v1.2\Pkg\src\Types.jl:987 [inlined]
clone_default_registries at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\sha
re\julia\stdlib\v1.2\Pkg\src\Types.jl:937
find_registered! at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia
\stdlib\v1.2\Pkg\src\Types.jl:1216
registry_resolve! at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\juli
a\stdlib\v1.2\Pkg\src\Types.jl:854
#add#25 at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v
1.2\Pkg\src\API.jl:92
add at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\
Pkg\src\API.jl:69 [inlined]
#add#24 at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v
1.2\Pkg\src\API.jl:67 [inlined]
add at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\
Pkg\src\API.jl:67 [inlined]
#add#21 at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v
1.2\Pkg\src\API.jl:65 [inlined]
add at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\
Pkg\src\API.jl:65 [inlined]
#add#20 at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v
1.2\Pkg\src\API.jl:64
add at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\
Pkg\src\API.jl:64
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/b
tor/buildbot/worker/package_win64/build/src\toplevel.c:815
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\ast.c:873
jl_load at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:879 [inlined]
jl_load_ at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:886
include at .\boot.jl:328 [inlined]
include_relative at .\loading.jl:1094
include at .\Base.jl:31
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2191
exec_options at .\client.jl:295
_start at .\client.jl:464
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2191
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/ui/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1614 [inlined]
true_main at /home/Administrator/buildbot/worker/package_win64/build/ui/home/Administrator/buildbot/worker/package_win64/build/ui\repl.c:96
wmain at /home/Administrator/buildbot/worker/package_win64/build/ui/home/Administrator/buildbot/worker/package_win64/build/ui\repl.c:217
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-6.0.0-1/usr/src/debug/mingw64-x86_64-runtime-6.0.0-1/crt\crtexe.c:334
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-6.0.0-1/usr/src/debug/mingw64-x86_64-runtime-6.0.0-1/crt\crtexe.c:223
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 466668 (Pool: 466574; Big: 94); GC: 0
2.

**Comment by pfitzseb** [comment]
This doesn't seem to be related to Juno.
Can you try opening Julia outside of Juno and run `using Pkg; Pkg.add("Atom")`? Does that fail with the same error?

**Comment by wzz1999** [comment]
libssh2 crash on recently updated Windows 10
https://github.com/JuliaLang/julia/issues/32907
