### ISSUE TITLE
[FR] Don't hold focus in result popups

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/Juno.jl#429]
After clicking on a result widget (for instance to expand a tree view) it seems to keep the focus, requiring another click on the text editor canvas to be able to start typing again. Is there an easy way to automatically return focus to the editor? I guess that would be a problem if there was some text entry that happened inside the widget, but that's generally not the case for me, and I seem to frequently forget to click back on the editor before I start typing.

Feel free to close if this is a bad idea - maybe I can change my habit.

**Comment by ssfrr** [comment]
interesting - this seems to only happen with in-line results, not floating ones.

**Comment by pfitzseb** [comment]
Should be fixed by https://github.com/JunoLab/atom-ink/pull/239. After that PR results only acquire focus if you select text.

**Comment by ssfrr** [comment]
Way ahead, as usual. Thanks!

**Comment by ssfrr** [comment]
As of the latest release there still seems to be a remnant of this - when you click the "x" to close a popup result it seems that the focus isn't returned to the editor window.

**Comment by pfitzseb** [comment]
Indeed. Fixed by https://github.com/JunoLab/atom-ink/commit/4ddee7816ce50a3f90a555aadd78feaef586850b.

**Comment by ssfrr** [comment]
Yay, thanks as always!
