### ISSUE TITLE
Multiline in debugger

### ISSUE THREAD

**Issue by jurasofish** [JunoLab/Juno.jl#430]
In a normal Julia REPL the following works fine

``` julia
julia> 5 +
       2
7
```

However, in the debugger within Juno, using ``Juno.@run``, I can't find a way to enter a multiline statement.

``` julia
debug> 5 +
ERROR: syntax: invalid syntax (incomplete #<julia: "incomplete: premature end of input">)
Stacktrace:
...
```

**Comment by aviatesk** [comment]
will be fixed by https://github.com/JunoLab/Atom.jl/pull/218

**Comment by jurasofish** [comment]
nice
