### ISSUE TITLE
Juno: Error downloading package info for tool-bar[BUG]

### ISSUE THREAD

**Issue by JING-XINXING** [JunoLab/Juno.jl#432]
Please search existing issues to avoid duplicates.

## Details
- Atom version:
- Julia version:v1.2
- OS:window10, 64bit
- Package versions:
  - Atom.jl:
  - julia-client:
  - ink:

### Steps to reproduce

1.install juno
2.Error: Fetching package 'tool-bar' failed.

**Comment by aviatesk** [comment]
It seems you didn't have the Internet access at that time. Make sure you have a stable access and retry installation process.
