### ISSUE TITLE
Setting environment variables

### ISSUE THREAD

**Issue by xgdgsc** [JunoLab/Juno.jl#434]
Is it possible to set LD_LIBRARY_PATH and launch julia with per folder saved settings? Currently I start a terminal , set LD_LIBRARY_PATH and connect to it.

**Comment by xgdgsc** [comment]
I develop code that calls cpp libraries and the LD_LIBRARY_PATH may need to change in different projects.

**Comment by aviatesk** [comment]
you want to have `LD_LIBRARY_PATH` as an environment variable, or just pass it as an command line args for julia startup ?

If former, you can set it before launching Atom or setting it in [your init script](https://flight-manual.atom.io/hacking-atom/sections/the-init-file/).
If latter, you can just use `ARGUMENTS` config under `Julia Options`.

***

> in different projects.

for that purpose, you need to use this pacakge: https://github.com/harmsk/atomic-management
but it can make your Atom startup slow.
