### ISSUE TITLE
[FR] Disable Alt usage of Juno

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#436]
At the moment it seems like the only thing that does not allow me to use a mouse-free Atom is the hijacking of the Alt key from Juno.

I would very much appreciate it if there was a simple option in juno to "disable hijacking Alt", so that Alt can be used for Atom-wide defined keybindings.

**Comment by Datseris** [comment]
Ha, I have now understood that if one writes:
```
Alt, Alt-2
```
in the white box (i.e. add *both* alt and alt-2), then alt works. But it is a bit of a hassle to add alt followed by 10 different letters. Is it possible to do what I am suggesting here, add an option that simply drops Alt from being used by atom?

**Comment by pfitzseb** [comment]
> add _both_ alt and alt-2

It's enough to only write `Alt-2` for me.

> But it is a bit of a hassle to add alt followed by 10 different letters.

True, but there's no good way around it. `Alt` is a useful modifier on its own, both for terminal programs *and* vertical selection in the terminal.

**Comment by pfitzseb** [comment]
Seems unlikely we will change anything about this.
