### ISSUE TITLE
[BUG] Julia REPL crashes when Julia Path contains environment variables.

### ISSUE THREAD

**Issue by racinmat** [JunoLab/Juno.jl#439]
## Details
- Atom version: 1.41.0
- Julia version: 1.3.0
- OS: Windows 10 Pro
- Package versions:
  - Atom.jl: 0.11.3
  - julia-client: 0.11.3
  - ink: 0.11.7

### Steps to reproduce

1. Use environment variable in a Julia path in settings of julia-client, e.g. %HOMEPATH%\AppData\Local\Julia-1.3.0\bin\julia.exe

2. Julia REPL crashes, showing:
```
Press Enter to start Julia. 
Start-Process : This command cannot be run due to the error: The system cannot find the file
specified.
At C:\Users\Azathoth\.atom\packages\julia-client\script\spawnInterruptible.ps1:8 char:9
+ $proc = Start-Process "`"$jlpath`"" $jlargs -NoNewWindow -PassThru
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcess
   Command
```

I want to use env vars here, because I use sync-settings to synchronize settings between two PCs which have Julia installed in different directories, but same directory relatively to the `%HOMEPATH%` variable.

**Comment by pfitzseb** [comment]
Just use `~` instead of `%HOMEPATH%` (which looks up `USERPROFILE`). I don't think supporting arbitrary env variables makes any sense here.

**Comment by racinmat** [comment]
And does the `~` work on windows? Because usually windows does not support `~` for home directory.

**Comment by pfitzseb** [comment]
It does, yes. We're internally resolving that to `%USERPROFILE%`.
