### ISSUE TITLE
Creating multi-line anonymous functions with control-enter

### ISSUE THREAD

**Issue by JackDevine** [JunoLab/Juno.jl#44]
If you create a function using the syntax:
```julia
function foo(x)
    2x
end
```
You can then put the function into your workspace by placing the cursor anywhere in the function and pressing <kbd>CTRL</kbd>-<kbd>ENTER</kbd>. However, if you create an anonymous function using the following syntax:
```julia
function bar(x)
    3x
end
```
Then the above trick does not work, you have to highlight the whole function and then press <kbd>CTRL</kbd>-<kbd>ENTER</kbd>. This is obviously a pretty low priority issue since the workaround is so simple, but I thought that I would post this issue to make sure that people are aware of it.

**Comment by pfitzseb** [comment]
Your two examples are exactly the same -- could you clarify what you mean? The following works btw, provided you use proper indentation:
```julia
foo = function (x)
  x+x
end

foo = (x) ->
  x+x
```

**Comment by JackDevine** [comment]
Sorry, that was a typo, the second example was supposed to look like
```julia
bar = function(x)
    3x
end
```
Although the idea that you have is quite interesting. My long term need is for multi-line anonymous functions.

Sorry for the confusion.

**Comment by pfitzseb** [comment]
Oh, okay -- having a space between the `function` keyword and the argument list will work (fun fact: the same is true for github's syntax highlighting -- in my example above `function` is highlighted as a keyword, while in yours it's a identifier).

**Comment by JackDevine** [comment]
Oh, wow. Thanks so much for your help!

**Comment by pfitzseb** [comment]
Alright, I'll close this then.
