### ISSUE TITLE
[BUG] 10% Idle CPU with Ink enabled on Ubuntu 19.10

### ISSUE THREAD

**Issue by laborg** [JunoLab/Juno.jl#441]
Hi,

top reports a 10% CPU usage when idling. This only stops after I disable the Ink package and restart Atom.

## Details
- Atom version: 1.41.0
- Julia version: 1.3.0
- OS: Ubuntu 19.10 (x64, latest updates)
- Package versions:
  - Atom.jl: 0.11.3
  - julia-client: 0.11.3
  - ink: 0.11.7

### Steps to reproduce

1. Start Atom
2. Start top
3. Realize that top shows 10% CPU for Atom 

How can I debug this? Are there any logs to look for suspicious entries?

**Comment by pfitzseb** [comment]
What exact process is associated with the CPU usage?

**Comment by laborg** [comment]
```
ps aux | grep atom
gerhard  22578  0.0  0.0  18100  1836 ?        S    12:18   0:00 /bin/bash /usr/bin/atom
gerhard  22580  5.5  1.3 1092884 226620 ?      Sl   12:18   3:40 /usr/share/atom/atom --executed-from=/home/gerhard --pid=22567
gerhard  22582  0.0  0.2 232532 40268 ?        S    12:18   0:00 /usr/share/atom/atom --type=zygote --no-sandbox
gerhard  22608  0.2  0.4 299704 81004 ?        Sl   12:18   0:08 /usr/share/atom/atom --type=gpu-process --enable-features=SharedArrayBuffer --no-sandbox --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=2874281846672973336
gerhard  22626 12.9  1.8 946284 306212 ?       Sl   12:18   8:31 /usr/share/atom/atom --type=renderer --no-sandbox --enable-experimental-web-platform-features --enable-features=SharedArrayBuffer --service-pipe-token=######### --lang=en-US --app-path=/usr/share/atom/resources/app.asar --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Atom/1.41.0 Chrome/69.0.3497.128 Electron/4.2.7 Safari/537.36 --node-integration=true --webview-tag=true --no-sandbox --background-color=#fff --disable-blink-features=Auxclick --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=######### --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
gerhard  22717  0.1  1.8 1300864 295440 pts/0  Ssl+ 12:18   0:06 /home/gerhard/julia-1.3.0/bin/julia --depwarn=yes -O3 --color=yes -i /home/gerhard/.atom/packages/julia-client/script/boot_repl.jl  32807
gerhard  22727  0.0  0.8 592912 144776 ?       Sl   12:18   0:00 /usr/share/atom/atom --type=renderer --no-sandbox --enable-experimental-web-platform-features --enable-features=SharedArrayBuffer --service-pipe-token=######### --lang=en-US --app-path=/usr/share/atom/resources/app.asar --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Atom/1.41.0 Chrome/69.0.3497.128 Electron/4.2.7 Safari/537.36 --node-integration=true --webview-tag=true --no-sandbox --background-color=#fff --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=######### --renderer-client-id=6 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
```

**Comment by laborg** [comment]
Here is the Juno Debug output:
```
# Atom:
Version: 1.41.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.7",
  "chrome": "69.0.3497.128",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
# julia-client:
Version: 0.11.3
Config:
{
  "consoleOptions": {},
  "firstBoot": false,
  "juliaOptions": {
    "deprecationWarnings": false
  },
  "juliaPath": "~/julia-1.3.0/bin/julia",
  "uiOptions": {
    "enableMenu": true
  }
}


# ink:
Version: 0.11.7
Config:
undefined


# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}


# language-julia:
Version: 0.19.2
Config:
undefined


# language-weave:not installed


# indent-detective:
Version: 0.4.0
Config:
undefined


# latex-completions:
Version: 0.3.6
Config:
undefined


# versioninfo():
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6

    Status `~/.julia/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.11.3
  [336ed68f] CSV v0.5.20
  [a93c6f00] DataFrames v0.20.0
  [cd3eb016] HTTP v0.8.8
  [e5e0dc1b] Juno v0.7.2
  [295af30f] Revise v2.4.0


```

**Comment by laborg** [comment]
Using the developer tools it looks as if there is some action going on in `ink/lib/editor/result.js` and `ink/lib/debugger/breakpoint.js` . Any idea why those lines of code are firing so often?

![image](https://user-images.githubusercontent.com/9527104/71127365-452f9980-21eb-11ea-838c-b716db1b7f68.png)

**Comment by pfitzseb** [comment]
Most likely because horizontally resizing the inline widgets isn't possible with pure CSS and therefore needs a bit of JS. Thanks for tracking this down though, I'll try to take a look at optimizing that code this week.

**Comment by laborg** [comment]
Are you sure this is an optimization problem?

It bounces back and forth between breakpoints.js and results.js:
![image](https://user-images.githubusercontent.com/9527104/71130022-35b34f00-21f1-11ea-87d8-7b17c63a0d84.png)
![image](https://user-images.githubusercontent.com/9527104/71130130-875bd980-21f1-11ea-895c-c29f7413a670.png)

Its strange that the `gutterElement` in line 112 is always `null` (screenshot 1). The `addClickListener` is called constantly but never passes line 117. Should the code path following line 119 be executed when clicking next to the editor? Or is this usage of the atom gutter special to a debugger view? (never used the debugger so far).

**Comment by laborg** [comment]
I've looked further into this:
- The constant `window.requestAnimationFrame()` call between `result.js:258` and `result.js:274` burns down a lot of CPU. After commenting out line 274 everything everything still works, except some artifacts of inline displayed code when resizing or scrolling, but that is - i guess - expected. CPU utilization decreased from ~17% to ~2%.
- Under certain circumstances `editorElement.querySelector(...)` in line 112 of `breakpoints.js` always returns `null`, which in turn triggers endless calls to `window.requestAnimationFrame()` via line 115. This is similar to the first problem. My guess is that it has something to do with the ordering of the gutters, but couldn't reliably find a configuration to verify this. (Played around with switching grammars, breakpoints on files that were not yet saved, opening of jl files).

**Comment by pfitzseb** [comment]
Can you try using the commented out code that only calls `requestAnimationFrame` after `10` (also try another number here) milliseconds? Should also use the same `setTimeout` trick for adding the breakpoint gutter (with a higher value though, since it's not an animation).

**Comment by laborg** [comment]
Using the `setTimeout` with 500ms for the callbacks in `breakpoint.js` and in `result.js` brings CPU utilization down to acceptable levels while still providing useful cleanup of window elements. If you want I can prepare a PR.

I noticed an additional problem with Atom, which has nothing to do with Juno: The blinking cursor taxes the CPU by ~5%. (The difference can be seen when observing the CPU with `top` and selecting the Julia REPL, so that the editor cursor stops blinking)... There have been reports about this in the past (https://github.com/atom/atom/pull/5775) but I couldn't find anything up to date about this issue. (VScode has fixed this problem in 2017).
