### ISSUE TITLE
Set working directory to current file's folder doesn't work[BUG]

### ISSUE THREAD

**Issue by a101010** [JunoLab/Juno.jl#443]
## Details
- Atom version:1.42.0
- Julia version:1.3.0
- OS: windows 10
- Package versions:
  - Atom.jl: N/A
  - julia-client: 0.11.3
  - ink: 0.11.7

### Steps to reproduce

1. Open Atom
2. Open a project, create a subfolder and some *.jl files in the subfolder
3. Start REPL, type pwd()
Current directory is the project directory
4. With one of the new files focused (and click in the window to make sure), Juno->Working Directory->Current File's Folder
5. type pwd() at REPL
Current directory is still the project directory
6. Juno->Working Directory->Home Folder
7. pwd()
Current directory is now the users home folder
8. Juno->Working Directory->Current Project's Folder
9, pwd()
Current directory is now the project's folder
10. Juno->Working Directory->Select; and pick the files folder
11. pwd()
Current directory is the one selected
12. Juno->Working Directory->Home Folder
13. pwd()
Current directory is the home folder
14. Repeate 4 and 5
Current directory is still the home folder

**Comment by pfitzseb** [comment]
Can you provide the debug info under the "Juno" menu entry? The version of Atom.jl (a Julia package) is very relevant to this issue.

**Comment by benninkrs** [comment]
I'm also experiencing this with a setup I installed yesterday:
- Julia 1.2
- Atom 1.42.0
- julia-client 0.11.3
- ink 0.11.7
- language-julia 0.19.2
- Atom.jl  0.11.3 [c52e3926]
- Juno.jl 0.7.2 [e5e0dc1b]

**Comment by aviatesk** [comment]
fixed in https://github.com/JunoLab/atom-julia-client/commit/c757b1e9e0815632e3a76ea53cde4207a2f7ac3b and that should
be included in the next release. (just because of a minor typo)

The temporal remedy is to use command instead of menus.

**Comment by sylvaticus** [comment]
Hello, I don't understand.. the fixing commit is of 28 Oct 2019, the same date as the latest release available (v.0.11.3). Do you mean that it is not in that release and it will be in the next one (e.g. v.0.11.4 ) ?

**Comment by aviatesk** [comment]
Yes, the release including this fix isn't released yet.
We will try to make an new release within next 1~2 weeks.

You can try our cutting edge version of Juno by developer installation: http://docs.junolab.org/latest/devdocs/dev_install/
