### ISSUE TITLE
Gallium.breakpoint_on_error() not working

### ISSUE THREAD

**Issue by schlichtanders** [JunoLab/Juno.jl#45]
Dear Juno Team,

it would be awesome to be able to jump to errors for debugging. Gallium has a breakpoint for this, settable with ``Gallium.breakpoint_on_error()``, however despite I read Juno would use Gallium, this does not work unfortunately.

In my current workspace after activating the breakpoint I run something errorful. However instead of jumping to the position in the code where the error happened, the I get a new error which seems to relate to Gallium itself
```
KeyError: key Ptr{Void} @0x0000000064f34730 not found
 in pop!(::Dict{Ptr{Void},Gallium.Hooking.Hook}, ::Ptr{Void}) at dict.jl:726
 in unhook(::Ptr{Void}) at Hooking.jl:476
 in breakpoint_on_error_hit(::Gallium.Hooking.Hook, ::Gallium.X86_64.ExtendedRegs) at Gallium.jl:938
 in _callback(::Ptr{Void}) at Hooking.jl:289
 in callback(::Ptr{Void}) at Hooking.jl:326
```

**Comment by ChrisRackauckas** [comment]
Gallium needs to release an update for it to work. So I'd call it an upstream problem. But Keno is working on a v0.6-compatible release instead of trying to fix a release first. That is probably a decent idea at this point.

**Comment by pfitzseb** [comment]
Yeah, this is a Gallium bug; once the 0.6 compatible version is out, I'll probably spend some time on a rework of the Juno debugger integration.
