### ISSUE TITLE
[FR] Possible collaboration: upcoming package FlameGraphs.jl for profiling

### ISSUE THREAD

**Issue by timholy** [JunoLab/Juno.jl#452]
I've seen a number of complaints that profiling is still not ideal in Julia. My own package, ProfileView, probably contributed to that problem: it was written in the Julia 0.1 days and hadn't had a fundamental architecture update. Consequently it has a number of limitations. 

En route to fixing some of those limitations, I decided to split it into 4 packages:
- [LeftChildRightSiblingTrees](https://github.com/JuliaCollections/LeftChildRightSiblingTrees.jl) was used for internal data handling. The details aren't terribly special (any k-ary tree structure would do equally well), but I cleaned it up and made it a standalone package.
- [FlameGraphs](https://github.com/timholy/FlameGraphs.jl): handles the computational side of producing a flamegraph. 
- ProfileSVG and ProfileView will be visualization/export functionality (linked from the FlameGraphs README)

I don't know whether you're wishing for anything more from your profiling, but if so perhaps we could collaborate at the level of FlameGraphs.jl as it's GUI-agnostic. The `dev` (but not `stable`) docs have just built and been hosted, so you can read more about it if you want.

EDIT: FlameGraphs.jl is not yet registered but that might change in 3 days: https://github.com/JuliaRegistries/General/pull/7997

**Comment by pfitzseb** [comment]
FlameGraphs.jl makes things really easy for us indeed., thanks! :)

At some point it might make sense to create a common web-frontend based on e.g. [flamebearer](https://mapbox.github.io/flamebearer/examples/rollup.html#) (although there probably are better choices) to get around the performance problems with Juno's and, probably, ProfileSVGs implementation.
