### ISSUE TITLE
Error: Installing “julia-client@0.11.3” failed.

### ISSUE THREAD

**Issue by filipefpaulo** [JunoLab/Juno.jl#456]
This error appears when I try to install Juno packages in the Atom.io.

The complete note is:
> Juno: Error installing package julia-client
> 
> Please check your internet connection, or report this to https://github.com/JunoLab/Juno.jl/issues or https://discourse.julialang.org and we'll try to help.
> 
> Error: Installing “julia-client@0.11.3” failed.

**Comment by aviatesk** [comment]
It seems to be a problem related to network connectivity, maybe caused by your firewall app, etc.

**Comment by pfitzseb** [comment]
You can give `apm install julia-client` in the terminal a shot and see if that gives a more useful error message.

**Comment by filipefpaulo** [comment]
Thanks, guys, I have reinstalled all instances of the Atom and it finally works!!
