### ISSUE TITLE
[BUG] Juno -> Working Directory -> Current File's Folder

### ISSUE THREAD

**Issue by azev77** [JunoLab/Juno.jl#457]
## Details
- Atom version: 1.43
- Julia version: 1.3.0
- OS: Windows (x86_64-w64-mingw32)

### Steps to reproduce

1. Open file w/ Juno, click: Juno -> Working Directory -> Current File's Folder
Then `pwd()` remains the same.

2. But this works click: Juno -> Working Directory -> Select...

**Comment by aviatesk** [comment]
fixed by https://github.com/JunoLab/atom-julia-client/commit/c757b1e9e0815632e3a76ea53cde4207a2f7ac3b

not yet released tho
