### ISSUE TITLE
[BUG] idle CPU usage

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/Juno.jl#462]
I recently updated to the latest ink and I'm seeing some higher-than-expected idle CPU usage (around 100% of a CPU). I'm not sure exactly what triggered it, but it wasn't happening when I first launched Atom.

Here's a picture of the developer tools profiler:
![image](https://user-images.githubusercontent.com/734386/72947275-7dc51480-3d4f-11ea-8ed3-e0d2658eea57.png)

## Details
# Atom:
Version: 1.41.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.7",
  "chrome": "69.0.3497.128",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
# julia-client:
Version: 0.11.3
Config:
{
  "firstBoot": false,
  "juliaOptions": {
    "bootMode": "Basic"
  },
  "juliaPath": "/home/sfr/local/bin/julia",
  "remoteOptions": {
    "tmux": true
  },
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true
  }
}

# ink:
Version: 0.11.8
Config:
{
  "monotypeResults": true
}

# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}

# language-julia:
Version: 0.19.2
Config:
undefined

# language-weave:
Version: 0.6.5
Config:
undefined

# indent-detective:
Version: 0.4.0
Config:
undefined

# latex-completions:
Version: 0.3.6
Config:
undefined

# versioninfo():
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 2
  JULIA_PKG_DEVDIR = /home/sfr/Dropbox/juliadev

    Status `~/research_journal/2020/01/22/pca_denoise/Project.toml`
  [717857b8] DSP v0.6.2
  [9c0c333d] EZInterpolation v0.1.0 [`~/Dropbox/juliadev/EZInterpolation`]
  [7a1cc6ca] FFTW v1.2.0
  [5789e2e9] FileIO v1.2.1
  [b13ce0c6] LibSndFile v2.2.0
  [6f286f6a] MultivariateStats v0.7.0
  [91a5bcdd] Plots v0.28.4
  [295af30f] Revise v2.5.0
  [44d3d7a6] Weave v0.9.1
  [c103ce95] XCorr2 v0.1.0 [`~/Dropbox/juliadev/XCorr2`]
  [37e2e46d] LinearAlgebra 
  [10745b16] Statistics

**Comment by ssfrr** [comment]
I'm doing some updates, I'll let you know if they make a difference:
Atom 1.41.0 -> 1.43.0
Julia 1.3.0 -> 1.3.1
DocSeeker 0.3.1 -> 0.3.2

**Comment by pfitzseb** [comment]
The stacktrace suggests that this is related to the plot pane. (or profiler, potentially). Can you confirm you have on e of those open? If so, is there any "weird" content in there (e.g. really a really big picture or something)?

**Comment by ssfrr** [comment]
Yeah, I have the plot pane open. I've been working with a lot of heatmap visualizations, I'm not sure if they're being downsampled for display or if the full signal is contained. If I get into this state again are there things I can do to help troubleshoot? If the issue is due to a large image being displayed should I see it go down after I close the plot pane and/or plot a simpler plot?

**Comment by ssfrr** [comment]
Actually I'm seeing this again now. Plotting a simpler plot does not seem to bring the CPU usage down, nor does closing the plot pane.

I actually closed all the open documents and panes and it's still sitting at 50% CPU, so it seems that there's some callback or something that's still being called.

**Comment by ssfrr** [comment]
I just opened a fresh file and ran `using Plots; plot(rand(100))` and after the plot appears the CPU usage seems to be sitting around 15-30% at idle.

**Comment by pfitzseb** [comment]
Ok, good to know. What Plots backend are you using? GR? PlotlyJS?

**Comment by ssfrr** [comment]
GR

**Comment by pfitzseb** [comment]
I can't repro this on my machine. Is this happening with a fresh session? Can you maybe make a short video showcasing what's happening?

**Comment by ssfrr** [comment]
Here's a video of launching Atom and running `using Plots`, then checking `htop` and showing that Atom is using ~1-2% CPU, then after running a `plot` command `htop` shows Atom using more like 10-14%. The high `gnome-shell` CPU is because of the recording.

![atom idle CPU usage](https://user-images.githubusercontent.com/734386/73373719-11826d80-4287-11ea-8582-29a510c8a58d.gif)

**Comment by pfitzseb** [comment]
Ok, so I was just trying to record a video showing that my CPU usage doesn't go up. Which it then promptly does anyway...

Will debug this further.

**Comment by pfitzseb** [comment]
https://github.com/JunoLab/atom-ink/pull/248 fixes the issue for me. Care to try it before I merge?
