### ISSUE TITLE
[FR] SSH proxyjump support

### ISSUE THREAD

**Issue by bencardoen** [JunoLab/Juno.jl#464]
Hi,

I'm trying to setup remote Julia execution where I need to connect through an intermediate host:
|laptop| <-ssh-> nodeX <-ssh-> JuliaNode

I can set this up (Fedora 29) with ProxyJump:
~/.ssh/config
Host cdrcompute
  HostName JuliaNode
  ProxyJump nodeX

This works in the command line, but not in the ftp-remote-edit workflow described in the documentation.

I can setup port forwarding, but I can't start the Juno part on the local machine as described in the manual section. 
More specifically, when I select New Terminal, I get a default Linux console in Atom, I can't see to find the "Julia Client: Connect External Process" option. 

Can anyone advise on how to get this workflow running?

Thanks!

Atom 1:34
julia-client 0.8.10

**Comment by pfitzseb** [comment]
> More specifically, when I select New Terminal, I get a default Linux console in Atom, I can't see to find the "Julia Client: Connect External Process" option.

Yeah, you're supposed to be dropped into a normal shell. You can find `Connect External Process` in the command pane (which you can open with <kbd>Ctrl-Shift-P</kbd>).

You can also try [this](http://docs.junolab.org/latest/man/remote/#Customizing-the-command-to-launch-Julia-1) and write a script that forwards your connection.

**Comment by bencardoen** [comment]
Thanks ! 
I overlooked the command palette, sorry about that. With that I can tunnel through the remote.
On a side note, thanks for making this excellent IDE available

**Comment by pfitzseb** [comment]
No worries -- glad it's working for you!
Feel free to open an issue or PR [here](https://github.com/JunoLab/JunoDocs.jl) if you have any suggestions for improving the docs.
