### ISSUE TITLE
Accessing history in REPL only partially working

### ISSUE THREAD

**Issue by halirutan** [JunoLab/Juno.jl#47]
In the REPL in Juno of Julia Pro, when I use the up key to get the last few expressions I typed, it doesn't work for more than the last command. The second up-key gives me an empty line and when I then use the down-key, very old commands are shown.

Here is a gif showing the behaviour. Pay attention to the keystrokes on the right

![REPL history in Juno](http://i.imgur.com/unurICE.gif)

I had expected that this works like the history in a terminal. My system is XUbuntu 16.04 with JuliaPro 0.5.1.1

**Comment by pfitzseb** [comment]
What you could try short term is to rename `~/.julia_history` and try again, but that might not even help. This bug should be fixed on the master branches of ink and/or julia-client, so with the next release you should be good to go.

**Comment by pfitzseb** [comment]
I'll just close this for now, since it should be fixed on master.

**Comment by halirutan** [comment]
@pfitzseb OK, thanks. Renaming `.julia_history` didn't help.
