### ISSUE TITLE
[BUG] Random internal error

### ISSUE THREAD

**Issue by aminya** [JunoLab/Juno.jl#470]
![image](https://user-images.githubusercontent.com/16418197/74096195-454c6700-4ac1-11ea-9b4a-7bcc7be9df88.png)

## Details
- Atom version:   1.46.0-nightly0
- Julia version:    1.3.1
- OS: Windows
- Package versions:
  - Atom.jl:  [c52e3926] Atom v0.11.3
  - julia-client: 0.11.3
  - ink: 0.11.8

### Steps to reproduce

It was totally random. I copy-pasted something into REPL and clicked the editor.

**Comment by aviatesk** [comment]
Fixed already

**Comment by aminya** [comment]
> 
> 
> Dup of [JunoLab/Atom.jl#237](https://github.com/JunoLab/Atom.jl/issues/237) and fixed already.

Haha. Duplicate of my own issue 😄
