### ISSUE TITLE
[FR] Allowing specifying JuliaFormatter Style

### ISSUE THREAD

**Issue by aminya** [JunoLab/Juno.jl#471]
I would like to use `YASStyle` for formatting. It would be good if we have a setting in the config that we can specify our desired style.
https://github.com/JunoLab/Atom.jl/blob/52ef77a93605cb4ddbf455ba36d1d7e9ae637edc/src/formatter.jl#L11

**Comment by aviatesk** [comment]
Please open an issue on Juno.jl.
And this is done in https://github.com/JunoLab/atom-julia-client/pull/682 and will be enhanced with https://github.com/domluna/JuliaFormatter.jl/issues/184.

**Comment by aminya** [comment]
Oh, Thanks!
How can I get that version?

**Comment by aviatesk** [comment]
See http://docs.junolab.org/latest/devdocs/dev_install/
