### ISSUE TITLE
Juno: Error installing package ink

### ISSUE THREAD

**Issue by sushanthkapisthalam94** [JunoLab/Juno.jl#475]
Error: Installing “ink@0.11.8” failed.

Had problems initially with Julia path, uninstalled and re-installed Julia and atom. Before re-installi I also deleted .atom files. Now I have an issue with ink.

**Comment by pfitzseb** [comment]
Close Atom and try
```
apm uninstall ink
apm install ink
```

If that errors then please paste the error message here.

**Comment by sushanthkapisthalam94** [comment]
> Close Atom and try
> 
> ```
> apm uninstall ink
> apm install ink
> ```
> 
> If that errors then please paste the error message here.

From command prompt?

**Comment by pfitzseb** [comment]
Yes.

**Comment by sushanthkapisthalam94** [comment]
> > Close Atom and try
> > ```
> > apm uninstall ink
> > apm install ink
> > ```
> > 
> > 
> > If that errors then please paste the error message here.
> 
> From command prompt?

Uninstalling ink failed
Failed to delete ink: No package.json found at C:\Users\mails\.atom\packages\ink\package.json

**Comment by sushanthkapisthalam94** [comment]
> > Close Atom and try
> > ```
> > apm uninstall ink
> > apm install ink
> > ```
> > 
> > 
> > If that errors then please paste the error message here.
> 
> From command prompt?


C:\WINDOWS\system32>apm install ink
Installing ink to C:\Users\mails\.atom\packages failed

> ink@0.11.8 postinstall C:\Users\mails\AppData\Local\Temp\apm-install-dir-120110-12124-1rrtc58.1ev5\node_modules\ink
> node scripts/postinstall.js


npm WARN lifecycle npm is using C:\Users\mails\AppData\Local\atom\app-1.43.0\resources\app\apm\bin\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\mails\AppData\Local\Temp\apm-install-dir-120110-12124-1rrtc58.1ev5\package.json'
npm WARN apm-install-dir-120110-12124-1rrtc58.1ev5 No description
npm WARN apm-install-dir-120110-12124-1rrtc58.1ev5 No repository field.
npm WARN apm-install-dir-120110-12124-1rrtc58.1ev5 No README data
npm WARN apm-install-dir-120110-12124-1rrtc58.1ev5 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ink@0.11.8 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ink@0.11.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mails\.atom\.apm\_logs\2020-02-10T10_03_08_782Z-debug.log

**Comment by sushanthkapisthalam94** [comment]
Fixed it by installing JuliaPro and unchecking powershell wrappers.
