### ISSUE TITLE
missing compat 1.3 for Atom.jl ?

### ISSUE THREAD

**Issue by floswald** [JunoLab/Juno.jl#479]
hi there,

did you forget to increase the minimum julia version for the latest Atom.jl update? the Project.toml has version 1 for julia. but i see

```
(v1.2) pkg> precompile
Precompiling project...
Precompiling Atom
[ Info: Precompiling Atom [c52e3926-4ff0-5f6e-af25-54175e0327b1]
ERROR: LoadError: UndefVarError: allocatedinline not defined
Stacktrace:
 [1] _precompile_() at /Users/florian.oswald/.julia/packages/Atom/YPkPM/src/precompile.jl:133
 [2] top-level scope at /Users/florian.oswald/.julia/packages/Atom/YPkPM/src/Atom.jl:66
```

**Comment by aviatesk** [comment]
Hm maybe the precompile statement doesn't work for you some reason.
I would like to comment that out and make a patch release, but can you tell me your packages and Julia versions ?

**Comment by aviatesk** [comment]
Atom@0.12.2 will fix this. Try
```julia
] up Atom
```
