### ISSUE TITLE
[BUG] link from stack trace doesn't work any more

### ISSUE THREAD

**Issue by floswald** [JunoLab/Juno.jl#482]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.44.0
- Julia version: 1.3
- OS: MacOS 10.15.3
- Package versions:
  - Atom.jl:
```
(v1.3) pkg> st
    Status `~/.julia/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.12.2
  [e5e0dc1b] Juno v0.8.0
```

  - julia-client: 0.12
  - ink: 0.12

### Steps to reproduce

1. create file `testing.jl` with
```
function foo(x)
    x + y
end
```
2. `julia-client: run all`
3. call `foo(3)`.
```
julia> foo(3)
ERROR: UndefVarError: y not defined
Stacktrace:
 [1] foo(::Int64) at /Users/74097/testing.jl:4
 [2] top-level scope at none:0
```
4. The link at [1] used to be clickable and took me into the file /Users/74097/testing.jl at line 4. 
5. doesn't work since update.

**Comment by floswald** [comment]
notice that it *does* work if i evaluate inline in the file itself (i.e i highlight the function body, hit cmd+enter, then add a line `foo(3)`, evalaute that inline: the link in the red error message works as expected.

**Comment by pfitzseb** [comment]
You need to `Cmd`/`Ctrl` click the link since the latest release. It's possible to disable that option in the settings to, if you want.

We should probably add a tooltip indicating what's going on though.

**Comment by floswald** [comment]
ahhhh, got it. yeah, the tip would be nice particularly for old users)
