### ISSUE TITLE
Workspace pane does not allow mousewheel scrolling

### ISSUE THREAD

**Issue by metanoid** [JunoLab/Juno.jl#492]
Mousewheel scrolling in Juno seems to work on the editor, and the REPL, but not in the Workspace pane or Project pane.  Instead, I need to click and drag on the scrollbar.

I'm on Windows.

## Details
- Atom version: 1.40.1 x64
- Julia version: Version 1.0.5
- OS: Windows 10
- Package versions:
  - Atom.jl: 0.12.3
  - julia-client: 0.12.0
  - ink: 0.12.0

### Steps to reproduce

1. Create a large number of variables in julia, such that there are more than be displayed in the Worskpace pane.
2. Hover the mouse over the Workspace pane, and scroll the mousewheel to show the hidden variables.

**Comment by pfitzseb** [comment]
Can't repro the issue, scrolling works just fine for me.

**Comment by metanoid** [comment]
Reinstalled atom, and also can no longer reproduce.
