### ISSUE TITLE
REPL not displayed in the same style as the rest of the panes

### ISSUE THREAD

**Issue by nreigl** [JunoLab/Juno.jl#496]
I encountered a strange behaviour after the Juno 0.12 update.  The REPL was not displayed in the same style as the rest of the panes the first time I opened Atom.

![screen1](https://user-images.githubusercontent.com/7542423/75120439-b466b580-5694-11ea-870f-93d054a34d89.png)

After an Atom `Window:reload`, the REPL displayed correctly. 

![screen2](https://user-images.githubusercontent.com/7542423/75120513-04457c80-5695-11ea-93c7-92941869ea2b.png)

Julia Client Debug Info: 

```
# Atom:
Version: 1.44.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.7",
  "chrome": "69.0.3497.128",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
# julia-client:
Version: 0.12.0
Config:
{
  "consoleOptions": {},
  "firstBoot": false,
  "juliaOptions": {
    "optimisationLevel": 1
  },
  "juliaPath": "/Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia",
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true,
    "errorInRepl": true,
    "layouts": {
      "console": {
        "split": "left"
      },
      "defaultPanes": {}
    }
  }
}


# ink:
Version: 0.12.0
Config:
undefined


# uber-juno:not installed


# language-julia:
Version: 0.19.2
Config:
undefined


# language-weave:
Version: 0.6.7
Config:
undefined


# indent-detective:not installed


# latex-completions:
Version: 0.3.6
Config:
undefined


# versioninfo():
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, sandybridge)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 2

    Status `~/.julia/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.12.3
  [6e4b80f9] BenchmarkTools v0.4.3
  [7073ff75] IJulia v1.21.1
  [e5e0dc1b] Juno v0.8.0
  [d4b2101a] Lint v0.0.0 #master (https://github.com/tonyhffong/Lint.jl)
  [5fb14364] OhMyREPL v0.5.4
  [91a5bcdd] Plots v0.29.1
  [295af30f] Revise v2.5.1
  [37e2e46d] LinearAlgebra 
  [9a3f8284] Random
``` 

Reinstalling Atom and Juno did not help. However, after creating a project folder and restarting Atom, the REPL was displayed in the same style as the other panes.

**Comment by pfitzseb** [comment]
Just to make sure: Does this happen with other terminal backends (e.g. canvas or dom) too? Are you still getting the error described in https://github.com/JunoLab/atom-ink/pull/264?

**Comment by nreigl** [comment]
It does not happen with the other terminal backends. Switching back to the webgl reintroduces the wrongly displayed REPL. After updating to the atom-ink master, the REPL is displayed correctly.

**Comment by pfitzseb** [comment]
Alright, I'll close this then and hope the actual error will get fixed upstream :)
