### ISSUE TITLE
[BUG] Very slow image preview in Plots pane

### ISSUE THREAD

**Issue by ianshmean** [JunoLab/Juno.jl#497]
Image previews recently heavily slowed down for me. The example below takes ~5 minutes to plot, where the pixels are added scan-wise very slowly.

## Details
- Atom version: 1.44.0
- Julia version: 1.3.1
- OS: MacOS
- Package versions:
  - Atom.jl: 0.12.5
  - julia-client: 0.12.2
  - ink: 0.12.2

### Steps to reproduce

```julia
using ColorTypes
img = rand(Gray, 1000, 1000)
```

**Comment by pfitzseb** [comment]
With just
```
using ColorTypes
img = rand(Gray, 1000, 1000)
```
I'm getting
```
┌ Warning: Output swatches are reduced due to the large size (1000×1000).
│ Load the ImageShow package for large images.
└ @ Colors ~/.julia/packages/Colors/P2rUx/src/display.jl:148
```
and a low-res svg image displays in a couple of seconds. After loading `ImageShow` a png appears almost immediately. It seems likely you've somehow loaded a super slow `show` method or something like that.

**Comment by pfitzseb** [comment]
Should be much better now for SVGs and HTML plots.
