### ISSUE TITLE
julia-client boot script fails because Juno.jl does no precompile

### ISSUE THREAD

**Issue by alyst** [JunoLab/Juno.jl#5]
Atom 1.10.2, latest releases of uber-juno, julia 0.5.0.
Upon startup I've got

```
INFO: Precompiling module Atom.
WARNING: Module Juno with uuid 2506331663263 is missing from the cache.
This may mean module Juno does not support precompilation but is imported by a module that does.
ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
while loading /home/astukalov/.julia/v0.5/Atom/src/Atom.jl, in expression starting on line 5
ERROR: LoadError: Failed to precompile Atom to /home/astukalov/.julia/lib/v0.5/Atom.ji.
 in require(::Symbol) at /home/astukalov/.julia/v0.5/Requires/src/require.jl:12
while loading /home/astukalov/.atom/packages/julia-client/script/boot.jl, in expression starting on line 36
```

But when I've added `__precompile__()` to `src/Juno.jl`, the installation succeeded.

**Comment by pfitzseb** [comment]
Same issue as https://github.com/JunoLab/uber-juno/issues/15.

I don't think we actually want to add `__precompile__()` to Juno.jl, since other not-precompilable packages might want to require it.

**Comment by alyst** [comment]
Does it mean that the solution is to disable `Atom.jl` precompilation? Would it affect Juno startup times?

**Comment by pfitzseb** [comment]
No, the problem here is spurious and might be related to our startup script, don't know yet.

Doing `using Atom` once in the REPL seems to fix it for good though.

**Comment by pfitzseb** [comment]
This is hopefully fixed now.
