### ISSUE TITLE
Frequent error of "no method matching Tk.TkWidget(::String, ::String)" when using Images.jl

### ISSUE THREAD

**Issue by cvcore** [JunoLab/Juno.jl#50]
#### Description
This problem happens to be every time I use Images.jl inside juno.

#### Reproduction Guide
Inside Atom, with uber-juno installed, type:
`cmd-j cmd-o` to open console, then:

`using Images, ImageView, TestImages` to import related package(you may need to install them first) and
`img=testimage("mandrill")` to request the test image. After this command atom will throw out an error:
```
Error displaying Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}: MethodError: no method matching Tk.TkWidget(::String, ::String)
Closest candidates are:
  Tk.TkWidget(!Matched::Tk.TkWidget, ::Any) at /Users/core/.julia/v0.5/Tk/src/tkwidget.jl:110
  Tk.TkWidget{T}(::Any) at sysimg.jl:53
 in #make_widget#54(::Array{Any,1}, ::Function, ::String, ::String) at core.jl:211
 in #Text#74(::Array{Any,1}, ::Type{T}, ::String) at widgets.jl:48
 in render(::Juno.Inline, ::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}) at system.jl:179
 in render at view.jl:51 [inlined]
 in render(::Juno.Console, ::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}) at types.jl:16
 in render′(::Juno.Console, ::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}) at errors.jl:89
 in (::Atom.##65#68)() at eval.jl:104
 in withpath(::Atom.##65#68, ::Void) at utils.jl:30
 in withpath(::Function, ::Void) at eval.jl:38
 in macro expansion at eval.jl:101 [inlined]
 in (::Atom.##64#67{Dict{String,Any}})() at task.jl:60
```

Currently you can inspect the content of an image by `display(MIME("text/plain"), img)` but that's far too unfriendly.

#### System Info
Atom 1.16.0 w/ uber-juno 0.1.1
Julia Version 0.5.1 Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

**Comment by pfitzseb** [comment]
I'm pretty sure this happens because of https://github.com/JuliaGraphics/Tk.jl/issues/117. Not sure what the best way forward is though.

**Comment by cvcore** [comment]
So is there anything can be done on juno's side? If I try it in jupyter everything seemed normal.

**Comment by pfitzseb** [comment]
We could use `Text{typeof(x)}(x)` instead of `Text(x)` I think, but that's pretty ugly. Jupyter apparently doesn't use `Base.Text`, so it's not an issue for their setup.

**Comment by pfitzseb** [comment]
Changing [this line](https://github.com/JuliaGraphics/Tk.jl/blob/master/src/Tk.jl#L27) to  `import Base: ==, bind, getindex, isequal, parent, setindex!, show, string` solves the immediate problem, btw. Not sure what this might break though.

**Comment by cvcore** [comment]
@pfitzseb thanks for the quick workaround. I will test it for a while and get back if anything happens.

**Comment by pfitzseb** [comment]
For reference: https://github.com/JuliaGraphics/Tk.jl/pull/138

**Comment by cvcore** [comment]
So far so good.
