### ISSUE TITLE
[BUG] Julia does not start after killing it a second time

### ISSUE THREAD

**Issue by yha** [JunoLab/Juno.jl#503]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.44.0
- Julia version: 1.3.0
- OS: Windows 10
- Package versions:
  - Atom.jl: master
  - julia-client: 0.12.2
  - ink: 0.12.2

### Steps to reproduce

1. Start Julia (Enter at the REPL pane) and kill it (ctrl+J ctrl+K)
2. Repeat
3. Enter at the REPL pane now does nothing

On step 2, the following appear in the console pane:
![image](https://user-images.githubusercontent.com/4170948/75374078-46103600-58d4-11ea-9a82-f9e751066f57.png)

**Comment by mmikhasenko** [comment]
Same problem
