### ISSUE TITLE
[BUG] Formatter turns ##< into ##

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JunoLab/Juno.jl#504]
## Details
- Atom version: 1.44
- Julia version: 1.3.1
- OS: macOS
- Package versions:
  - Atom.jl: 0.12.7
  - julia-client: 0.12.2
  - ink: 0.12.2

### Steps to reproduce

1. Format a line with `##<` or `##>`
 This may be intended, but it brakes my custom fold plugin.

**Comment by pfitzseb** [comment]
Can't repro that:
![Peek 2020-02-27 10-11](https://user-images.githubusercontent.com/6735977/75429157-a2616d00-5949-11ea-81e3-fe0f14616b25.gif)

**Comment by aviatesk** [comment]
me neither.

**Comment by BeastyBlacksmith** [comment]
I can't reproduce either right now. But I can see the following, when using "Format on save"

![FormatJuno](https://user-images.githubusercontent.com/18145188/75543214-9a74fc00-5a21-11ea-87ed-ab7cd05f46f7.gif)
