### ISSUE TITLE
[BUG] Cursor vanishes in REPL

### ISSUE THREAD

**Issue by zsoerenm** [JunoLab/Juno.jl#507]
The cursor in the REPL seems to vanish after a while.

![Atom_no_cursor](https://user-images.githubusercontent.com/375486/75431290-ef930e00-594c-11ea-81bf-e019ae56a4f6.png)

The cursor should be after `signal`. I have to restart Atom to get the white cursor back.
This happens with newest 0.12. version. Before that the cursor did not vanish.

## Details
- Atom version: 1.44.0 x64
- Julia version: v1.3.1
- OS: Linux
- Package versions:
  - Atom.jl: v0.12.7
  - julia-client: 0.12.2
  - ink: 0.12.2

### Steps to reproduce

1. Start REPL
2. Wait?

**Comment by pfitzseb** [comment]
Is this still happening with the latest release?

**Comment by zsoerenm** [comment]
I have not seen this issue anymore for a while now. I think it can be closed.
