### ISSUE TITLE
Tooltip for clickable links

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/Juno.jl#508]
that suggests to Ctrl/Cmd-Click it.

**Comment by aviatesk** [comment]
If possible, we may want to suppress underline highlights on hover when <kbd>Ctrl/Cmd</kbd> isn't pressed.

**Comment by pfitzseb** [comment]
It's not possible, afaict.

**Comment by aviatesk** [comment]
ah, okay good to know.

**Comment by gzhang8** [comment]
I just want to comment on this. I though the clickable link feature is broken until I see this here...

**Comment by aviatesk** [comment]
well, we've announced this change in [our release note](https://discourse.julialang.org/t/ann-juno-0-12/34717), and you can turn off this setting and restore the previous behaviour:
![image](https://user-images.githubusercontent.com/40514306/75733497-d61d0800-5d38-11ea-9a95-f50362f9833d.png)
