### ISSUE TITLE
Ability to set a breakpoint on a line of code in a source file

### ISSUE THREAD

**Issue by quinnj** [JunoLab/Juno.jl#51]
Gallium supports setting breakpoints on specific lines in julia source files. It'd be super nifty (and match behavior of most debuggers) to be able to right click on a specific line and set a Gallium breakpoint.

**Comment by ChrisRackauckas** [comment]
It should be enabled already if Gallium actually its release. The issue has been that this is waiting on Gallium's release.

https://github.com/Keno/Gallium.jl/issues/187

**Comment by pfitzseb** [comment]
Setting them should work with the latest Gallium release anyways, but removing them doesn't. You should be able to set a breakpoint via <kbd>Alt-X</kbd>, but an entry in the context menu would be cool too.
