### ISSUE TITLE
[BUG] Atom crashes after killing->restarting Julia runtime (maybe only on Windows)

### ISSUE THREAD

**Issue by aviatesk** [JunoLab/Juno.jl#510]
Within the latest releases (Juno v0.12), a whole Atom process can get crashed on starting Julia process after killing the previous Julia process via `Julia Client: Kill Julia` command.
This doesn't happen for all the cases, so the issue happens kinda unpredictably.

Maybe related issues:
- https://github.com/JunoLab/atom-julia-client/pull/676

**Comment by kool7d** [comment]
I am having the same problem. It happens every time I stop julia. I am on Windows 10.

**Comment by aminya** [comment]
I tried to catch the error using `try catch` but it doesn't help https://github.com/aminya/juno-plus/blob/d545e0a820fb8f607e589aa7b3fa6e68a635165d/lib/juno-plus.coffee#L75

**Comment by davidzentlermunro** [comment]
Same issue here

**Comment by LasseKatten** [comment]
I also have the same error

After working on one Julia session for 1h and then stopping the session and attempting to start a new one, Julia gets stuck in a deadlock.

I do not get this issue when starting a new Julia session and killing it instantly after a fresh Atom start. I have only gotten it when working with Julia for a little while and then killing it and then attempting to restart.

The only way for me to get around this issue at the moment is by restarting Atom.

**Comment by aviatesk** [comment]
@pfitzseb has done another glorious work: https://github.com/JunoLab/atom-julia-client/pull/699
