### ISSUE TITLE
Feature request: more style for cell delimiter

### ISSUE THREAD

**Issue by touchft** [JunoLab/Juno.jl#515]
I noticed that when I jump between cells, the background color change impacts my attention. Although there is an option to disable this feature in the settings, I think this function is very useful. How about provide different style options for cell delimiter ? Such as:

1. Change the color of line numbers of the focused cell
2. Add a color bar beside the line number of the focused cell

Thanks.

**Comment by pfitzseb** [comment]
"Fixed" by https://github.com/JunoLab/atom-julia-client/pull/700.
