### ISSUE TITLE
[BUG] editor output sometimes displays in REPL

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/Juno.jl#520]
I haven't been able to reproduce this reliably unfortunately, but sometimes Juno seems to get into a state where when I evaluate code in the editor the results display in the REPL (in addition to the editor popup).

When it gets into this state it seems that longer-running evaluations are more prone to it, e.g.

```julia
begin
    sleep(1)
    1+1
end
```
Would print `2` pretty much every time, but just evaluating `1+1` only prints `2` maybe 10% of the time.

# Atom:
Version: 1.44.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.9.2",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.15.0",
  "modules": "69",
  "nghttp2": "1.39.2",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.12",
  "chrome": "69.0.3497.128",
  "icu": "65.1",
  "unicode": "12.1",
  "cldr": "36.0",
  "tz": "2019c"
}
# julia-client:
Version: 0.12.2
Config:
{
  "firstBoot": false,
  "juliaOptions": {
    "bootMode": "Basic",
    "noAutoParenthesis": true
  },
  "juliaPath": "/home/sfr/local/bin/julia",
  "remoteOptions": {
    "tmux": true
  },
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true,
    "layouts": {
      "console": {
        "split": "left"
      },
      "openDefaultPanesOnStartUp": false,
      "profiler": {
        "defaultLocation": "right"
      },
      "workspace": {
        "defaultLocation": "bottom"
      }
    }
  }
}

# ink:
Version: 0.12.2
Config:
{
  "monotypeResults": true
}

# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}

# language-julia:
Version: 0.19.2
Config:
undefined

# language-weave:
Version: 0.6.7
Config:
undefined

# indent-detective:
Version: 0.4.0
Config:
undefined

# latex-completions:
Version: 0.3.6
Config:
undefined

# versioninfo():
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 2
  JULIA_PKG_DEVDIR = /home/sfr/Dropbox/juliadev

    Status `~/research_journal/2020/02/28/full_data_sdr/Project.toml`
  [336ed68f] CSV v0.5.26
  [8f4d0f93] Conda v1.4.1
  [717857b8] DSP v0.6.3
  [7a1cc6ca] FFTW v1.2.0
  [c8e1da08] IterTools v1.3.0
  [50d2b5c4] Lazy v0.15.0
  [6f286f6a] MultivariateStats v0.7.0
  [91a5bcdd] Plots v0.29.4
  [438e738f] PyCall v1.91.4
  [295af30f] Revise v2.5.3
  [2cd0c555] SFRDSP v0.1.0 #master (https://github.com/ssfrr/SFRDSP.jl.git)
  [bd7594eb] SampledSignals v2.1.0
  [03a91e81] SplitApplyCombine v1.0.0
  [2913bbd2] StatsBase v0.32.1
  [f3b207a7] StatsPlots v0.14.0
  [bd369af6] Tables v1.0.2
  [02d47bb6] TensorCast v0.2.1
  [4f5259d8] TidmarshAudio v0.1.0 #master (https://github.com/mitmedialab/TidmarshAudio.jl.git)
  [44d3d7a6] Weave v0.9.1
  [37e2e46d] LinearAlgebra 
  [9a3f8284] Random 
  [9e88b42a] Serialization 
  [10745b16] Statistics

**Comment by pfitzseb** [comment]
Is this still happening with the [latest release](https://discourse.julialang.org/t/ann-juno-0-12/34717/70?u=pfitzseb)?

**Comment by pfitzseb** [comment]
Please re-open if you're still running into this issue.
