### ISSUE TITLE
Error: Installing “julia-client@0.12.3” failed.

### ISSUE THREAD

**Issue by Romeoly** [JunoLab/Juno.jl#525]
I can't get "julia-client" installed on my computer, and I have tried [this post](https://github.com/JunoLab/Juno.jl/issues/332#issuecomment-514319558). 

I did `apm install julia-client`. And here is the log:  
[2020-03-11T02_42_58_669Z-debug.log](https://github.com/JunoLab/Juno.jl/files/4315828/2020-03-11T02_42_58_669Z-debug.log)
I don't know what is the most important part, so please find it from the file. 

1. OS: Win10 v10.0.18363.657 
2. Julia: 1.3.0
3. I have got NodeJS, and `npm --version` shows `6.14.2`
4. But `apm --version` shows `apm  2.4.3\n npm  6.2.0\n node 10.2.1 x64\n atom 1.44.0\n python\n git\n visual studio`.
5. I have Visual Studio 2019.
6. I have both Python 3.7 and Python 2.7 installed. 

Thank you so much for your help. Please tell me if more info is required.

**Comment by pfitzseb** [comment]
A bunch of users have reported that using [apx](https://github.com/Aerijo/apx) to install julia-client (or ink) solved their issues, so please give that a go.

**Comment by Romeoly** [comment]
> 
> 
> A bunch of users have reported that using [apx](https://github.com/Aerijo/apx) to install julia-client (or ink) solved their issues, so please give that a go.

I failed again.  The error message is `request to https://api.github.com/repos/JunoLab/atom-julia-client/releases failed, reason: read ECONNRESET`. Perhaps it is because of my network.  

Thank you very much. I'll be very patient and wait for the next version.

**Comment by Romeoly** [comment]
> 
> 
> A bunch of users have reported that using [apx](https://github.com/Aerijo/apx) to install julia-client (or ink) solved their issues, so please give that a go.

One more question. 
I have got juno install on another computer. Can I copy some file from that computer to make this computer work?

**Comment by pfitzseb** [comment]
Yes, you _should_ be able to copy over `C:\Users\You\.atom` and be good to go (but I haven't tried that in quite a while).

**Comment by Romeoly** [comment]
> 
> 
> Yes, you _should_ be able to copy over `C:\Users\You\.atom` and be good to go (but I haven't tried that in quite a while).

Thank you so much. I can work with Julia and Juno now.
