### ISSUE TITLE
[BUG] Formatted strings which end in "u" break highlighting

### ISSUE THREAD

**Issue by marius311** [JunoLab/Juno.jl#528]
## Details
- Atom version: 1.45.0
- Julia version: 1.3.1
- OS: Linux
- Package versions:
  - Atom.jl: v0.12.9
  - julia-client: 0.12.3
  - ink: 0.12.3

## Steps to reproduce

Looks like a formatted string (in my example with `py`) which ends in `u` breaks highlighting. E.g.: 

```julia
py"u"
let # <- broken here
end
```

```julia
py"x"
let # <- ok
end
```

**Comment by aviatesk** [comment]
It would be better to reopen this in https://github.com/JuliaEditorSupport/atom-language-julia/issues

**Comment by marius311** [comment]
Should I do so? Not totally sure, but doesn't Github now have a feature to transfer Issues?

**Comment by pfitzseb** [comment]
Yes, but only inside of an org. Would be great if you could reopen this at language-julia :)
