### ISSUE TITLE
[FR] ≠  (\ne) should be syntax highlighted

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#530]
MWE:

![image](https://user-images.githubusercontent.com/19669089/77469684-c06aa200-6e0f-11ea-817b-b94fc139212a.png)

**Comment by aviatesk** [comment]
Improved already by https://github.com/JuliaEditorSupport/atom-language-julia/pull/204; update your language-julia package.

**Comment by aviatesk** [comment]
ops, I just found the PR is still not included within the latest release.
@pfitzseb how about making a new release (maybe patch one)

**Comment by pfitzseb** [comment]
New version is out and should fix this.
