### ISSUE TITLE
No finish notification evaluating a single line - Juno hangs/crashs/freezes

### ISSUE THREAD

**Issue by VoSiLk** [JunoLab/Juno.jl#532]
I´m using Julia Pro 1.3.1-2 on Windows. I´m facing the same problem with Julia Pro as I described in #405 . I evaluate some lines by single line evaluation and suddenly at one line I get no finish notification, despite a evaluation in the REPL works.

For the following Debug Info Juno hangs during loading a big csv-file. 

# Atom:
Version: 1.44.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.7",
  "chrome": "69.0.3497.128",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
# julia-client:
Version: 0.11.3
Config:
{
  "firstBoot": false,
  "juliaOptions": {
    "bootMode": "Cycler"
  },
  "juliaPath": "C:\\JuliaPro-1.3.1-2\\Julia-1.3.1\\bin\\julia.exe",
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true,
    "layouts": {
      "openDefaultPanesOnStartUp": true
    },
    "errorNotifications": false
  }
}

# ink:
Version: 0.11.8
Config:
undefined

# uber-juno:not installed

# language-julia:
Version: 0.19.2
Config:
undefined

# language-weave:not installed

# indent-detective:not installed

# latex-completions:
Version: 0.3.6
Config:
undefined

Could not connect to Julia.
2.

For anyone, who has the same problems the following setup with vanilla Julia 1.1.1 works for me,:
Julia packages:
Atom v0.9.1
Juno v0.7.2
Note: to install a specific version of julia package enter the package manager within the Julia REPL via ] and then use i.e add Juno@0.7.2 command

Atom packages:
ink 0.11.7
julia-client 0.11.3
language-julia 0.19.2
uber-juno 0.3.0
Note: to install a specific version of atom package open a power shell window and then use i.e
apm install ink@0.11.7 command

**Comment by aviatesk** [comment]
The debug info says you even couldn't connect to Julia properly.
Are you sure you were running code by Juno ?

**Comment by VoSiLk** [comment]
I´m confused. How should I run the code not by Juno, when I´m working with Julia Pro? I just opened Julia Pro and pressed SHIFT + ENTER to evaluate lines of a script.

**Comment by aviatesk** [comment]
Sometimes users assume some features are provided by Juno, but sometimes they actually provided by other packages that enables code execution like [Hydrogen](https://github.com/nteract/hydrogen) etc.
I'm curious how you can run code (within Juno) even when your Juno couldn't find a Julia.

well, as for this specific bug, https://github.com/JunoLab/Atom.jl/pull/300 will get rid of those dead lock issues.

**Comment by VoSiLk** [comment]
I´m not sure, but I think it could maybe have something to do with a change in Atom.jl, because if you compare the settings of #405  with my currently settings, which work, I could update all packages except for the Atom.jl package. Furthermore I didn´t experience this behaviour in an earlier version of Julia Pro, where also an older version of Atom.jl was uesd,

**Comment by pfitzseb** [comment]
We just released a new version of Atom.jl that you could try (not with JuliaPro, just in a normal Juno installation).
JuliaPro 1.4 will also be out this week, in case you want to wait for that.

**Comment by VoSiLk** [comment]
Thanks. I'll try and report later in the day.

**Comment by VoSiLk** [comment]
The first test was successful. The problem doesn´t appear again. I will work the next days with the latest version and report the results.

**Comment by pfitzseb** [comment]
Awesome. Sorry it's taken us such a long time to track this bug down...

**Comment by VoSiLk** [comment]
It hangs again on a custom module. I tried to load manual with the REPL and it worked. So unfortunately the bug isn´t solved.

**Information of Ctrl+ Shift + I:**
spell-check:en-us The package `spell-check` cannot load the system dictionary for `en-US`. See the settings for ways of changing the languages used,  resolving missing dictionaries, or hiding this warning.

The plugin checked the following paths for dictionary files:
* C:\
* C:\Users\VoSiLk\AppData\Local\atom\app-1.45.0\resources\app.asar.unpacked\node_modules\spellchecker\vendor\hunspell_dictionaries
view.js:32 Tried to start terminal with WebGL backend, but encountered the following error:
view.js:33 TypeError: Cannot read property 'onLinkHover' of undefined
    at new e (C:\Users\VoSiLk\.atom\packages\ink\node_modules\xterm-addon-webgl\lib\xterm-addon-webgl.js:1:32485)
    at new e (C:\Users\VoSiLk\.atom\packages\ink\node_modules\xterm-addon-webgl\lib\xterm-addon-webgl.js:1:15737)
    at t.activate (C:\Users\VoSiLk\.atom\packages\ink\node_modules\xterm-addon-webgl\lib\xterm-addon-webgl.js:1:14454)
    at e.loadAddon (C:\Users\VoSiLk\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1:270381)
    at e.loadAddon (C:\Users\VoSiLk\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1:55356)
    at HTMLElement.initialize (file:///C:/Users/VoSiLk/.atom/packages/ink/lib/console/view.js:30:29)
    at file:///C:/Users/VoSiLk/.atom/packages/ink/lib/console/console.js:61:19
    at Function.simpleDispatch (C:\Users\VoSiLk\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1214120)
    at Emitter.emit (C:\Users\VoSiLk\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1215561)
    at Workspace.didActivatePaneContainer (C:\Users\VoSiLk\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:424255)
    at Dock.subscriptions.l.paneContainer.onDidActivatePane (C:\Users\VoSiLk\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:469080)
    at Function.simpleDispatch (C:\Users\VoSiLk\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1214120)
    at Emitter.emit (C:\Users\VoSiLk\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1215561)
    at PaneContainer.didActivatePane (C:\Users\VoSiLk\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:446491)
    at Pane.activate (C:\Users\VoSiLk\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:463814)
    at Workspace.open (C:\Users\VoSiLk\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:431660)
initialize	@	view.js:33
misc.coffee:30 Julia Boot: 0.37s
internal/process/warning.js:18 (node:13804) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
﻿
**Debug Info:**
# Atom:
Version: 1.45.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.7",
  "chrome": "69.0.3497.128",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
# julia-client:
Version: 0.12.4
Config:
{
  "firstBoot": false,
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true,
    "layouts": {
      "debuggerPane": {
        "split": "right",
        "defaultLocation": "bottom"
      },
      "workspace": {
        "split": "up"
      }
    },
    "usePlotPane": false,
    "errorInRepl": true
  }
}


# ink:
Version: 0.12.3
Config:
undefined


# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}


# language-julia:
Version: 0.19.3
Config:
undefined


# language-weave:not installed


# indent-detective:
Version: 0.4.0
Config:
undefined


# latex-completions:
Version: 0.3.6
Config:
undefined


Could not connect to Julia.

**Package list:**
Atom v0.12.10
BenchmarkTools v0.5.0
CSV v0.5.26
CUDAnative v2.10.2
Cairo v1.0.2
Colors v0.11.2
ConcaveHull v1.0.0
Conda v1.4.1
CuArrays v1.7.3
DSP v0.6.3
DataFrames v0.20.2
Debugger v0.6.4
Distances v0.8.2
Distributions v0.23.1
FFTW v1.2.0
FileIO v1.2.4
Flux v0.10.3
GR v0.48.0
Gtk v1.1.3
Hwloc v1.0.3
IJulia v1.20.0
IRTools v0.3.1
InspectDR v0.3.6
Interpolations v0.12.5
JLD2 v0.1.12
JSON v0.21.0
JuliaInterpreter v0.7.13
Juno v0.8.1
LaTeXStrings v1.1.0
LatinHypercubeSampling v1.6.3
MAT v0.7.0
MATLAB v0.7.3
MLDataUtils v0.5.0
MacroTools v0.5.5
Missings v0.4.3
ORCA v0.3.1
OhMyREPL v0.5.5
PGFPlotsX v1.2.5
Plotly v0.3.0
PlotlyJS v0.13.1
Plots v0.27.1
ProfileView v0.5.3
PyCall v1.91.4
PyPlot v2.8.2
Query v0.12.2
RCall v0.13.4
Rebugger v0.3.3
Revise v2.5.4
Sobol v1.3.0
StatPlots v0.9.2
StringDistances v0.6.3
TensorFlow v0.11.0
Traceur v0.3.0
WinRPM v1.0.0
ZygoteRules v0.2.0
LinearAlgebra
Profile
Random
Statistics
Test

**Comment by pfitzseb** [comment]
Can you describe what you did just before the hang?

**Comment by VoSiLk** [comment]
I just restarted julia and loaded 

using JLD2
using MATLAB
using ACustomModule
using CSV

**Comment by aviatesk** [comment]
It may be possible that your script made Juno's static code analyzer crazy (will appear as memory consumption explosion usually). If so it will be helpful if you share your script with us.

**Comment by VoSiLk** [comment]
I would like to do this, but it isn´t so easy, because I use Julia for my work at a company and therefore I can´t simply share the code. Sorry.

**Comment by pfitzseb** [comment]
Right, makes sense. Can you keep an eye on memory and cpu consumption in the task manager?

You could also give the first patch suggested [here](https://github.com/JunoLab/Juno.jl/issues/524#issuecomment-602563867) a go, that _might_ help.

**Comment by VoSiLk** [comment]
Thanks. I will try it.

Here the informations when I run the same code under 

Julia 1.1.1 
Julia packages:
Atom v0.9.1
Juno v0.7.2

Atom packages:
ink 0.11.7
julia-client 0.11.3
language-julia 0.19.2
uber-juno 0.3.0

**Ctrl +Shif + I:**
internal/process/warning.js:18 (node:15260) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
<embedded>:14 spell-check:en-us The package `spell-check` cannot load the system dictionary for `en-US`. See the settings for ways of changing the languages used,  resolving missing dictionaries, or hiding this warning.

The plugin checked the following paths for dictionary files:
* C:\
* C:\Users\VoSiLk\AppData\Local\atom\app-1.45.0\resources\app.asar.unpacked\node_modules\spellchecker\vendor\hunspell_dictionaries
C:\Users\VoSiLk\.at…tion\ipc.coffee:155 julia-client: unrecognised message versionwarning 
Array(1)
C:\Users\VoSiLk\.at…\lib\misc.coffee:45 Julia Boot: 1.26s
C:\Users\VoSiLk\.at…tion\ipc.coffee:155 julia-client: unrecognised message versionwarning 
Array(1)


**Debug info:**
# Atom:
Version: 1.45.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.7",
  "chrome": "69.0.3497.128",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
# julia-client:
Version: 0.11.3
Config:
{
  "firstBoot": false,
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true,
    "errorInRepl": true,
    "layouts": {
      "debuggerPane": {
        "defaultLocation": "bottom",
        "split": "right"
      },
      "workspace": {
        "split": "up"
      }
    },
    "usePlotPane": false
  }
}


# ink:
Version: 0.11.7
Config:
undefined


# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}


# language-julia:
Version: 0.19.2
Config:
undefined


# language-weave:not installed


# indent-detective:
Version: 0.4.0
Config:
undefined


# latex-completions:not installed


Could not connect to Julia.

**Package list:**
Atom v0.9.1
BenchmarkTools v0.4.3
CSV v0.5.20
CUDAnative v2.7.0
Cairo v0.6.0
Colors v0.9.6
ConcaveHull v1.0.0
Conda v1.3.0
CuArrays v1.6.0
DSP v0.6.2
DataFrames v0.20.0
Debugger v0.5.0
Distances v0.8.2
DistributedArrays v0.6.4
Distributions v0.21.11
FFTW v1.1.0
FileIO v1.2.1
Flux v0.10.0
GR v0.44.0
Gtk v0.18.0
Hwloc v1.0.3
IJulia v1.20.2
IRTools v0.3.0
InspectDR v0.3.6
Interpolations v0.12.5
JLD2 v0.1.9
JSON v0.21.0
JuliaInterpreter v0.6.1
Juno v0.7.2
LaTeXStrings v1.0.3
LatinHypercubeSampling v1.4.0
Lint v0.0.0 #master (https://github.com/tonyhffong/Lint.jl)
MAT v0.7.0
MATLAB v0.7.3
MLDataUtils v0.5.0
MacroTools v0.5.3
Missings v0.4.3
ORCA v0.3.1
OhMyREPL v0.5.3
PGFPlotsX v1.2.0
Plotly v0.2.0
PlotlyJS v0.13.1
Plots v0.28.4
ProfileView v0.5.3
PyCall v1.91.2
PyPlot v2.8.2
Query v0.12.2
RCall v0.13.4
Rebugger v0.3.2
Revise v2.1.6
Sobol v1.3.0
StatPlots v0.9.2
StringDistances v0.4.0
TensorFlow v0.11.0
Traceur v0.3.0
WinRPM v0.4.2
ZygoteRules v0.2.0
LinearAlgebra
Profile
Random
SharedArrays
Statistics
Test

**Comment by pfitzseb** [comment]
Oh, one more question: Do you have Revise loaded while running your code?

**Comment by VoSiLk** [comment]
Yes I have put it in the startup like this:

ENV["JULIA_REVISE"] = "auto"
ENV["JULIA_REVISE_INCLUDE"] = "1"
ENV["JULIA_REVISE_POLL"] = "1"

atreplinit() do repl
    try
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
    catch
    end
end

**Comment by pfitzseb** [comment]
Can you check if you see the same error without Revise (in the neweset Juno release)?

**Comment by VoSiLk** [comment]
It doesn´t hangs until now and I notice that the loading of the modules is much faster.

**Comment by timholy** [comment]
Try without all those `ENV` customizations, especially the `INCLUDE` one. (You're certain you need `POLL`? Your code is on an NFS mount?)

**Comment by VoSiLk** [comment]
Oh, I think, when I first configured my startup file, I read something different "NTFS" and copied this code sequence somewhere. So I will try it :)

**Comment by VoSiLk** [comment]
For the moment I would say, that this was the problem. Thank you very much for your help and time :) . Despite this I would like to investigate it a little bit longer, because I had it several times, that I thought the problem is gone and it wasn´t.

**Comment by timholy** [comment]
> I read something different "NTFS" and copied this code sequence.

Thanks for letting me know, I can totally see how that would happen. I will tweak the docs to emphasize that the two are not the same.

**Comment by pfitzseb** [comment]
Ok, I'll close this for now then. Feel free to reopen if you run into similar issues again.

**Comment by VoSiLk** [comment]
Thank you
