### ISSUE TITLE
[BUG] Subtypes of functions and their fields display incorrectly in workspace

### ISSUE THREAD

**Issue by mewilhel** [JunoLab/Juno.jl#535]
When displaying functors the Workspace panel doesn't reflect the type of the functor or the fields of the structure. Running the below snippet, the example will display in the Workspace as "example   Any" and no drop down menu is present which can be used to example the fields "x" or "y" rather a definition of any is given. The correct type is `Functor`. Functor's a fairly useful for efficiently adding parameters to functions that previously lacked them (e.g. Jacobians with ForwardDiff.jl) or preallocating storage. So if would be nice if Juno's display supported them.

```julia 
struct Functor <: Function 
x::Int
y::Int
end
example = Functor(1,2)
```
![image](https://user-images.githubusercontent.com/28902607/77762520-0726ea80-7010-11ea-8f80-7e0ae006d02d.png)

## Details
- Juno version: 0.8.1
- Atom version: 1.45.0 x64
- Julia version: 1.3.1
- OS: Windows 10
- Package versions:
  - Atom.jl: 0.12.9
  - julia-client: 0.12.3
  - ink: 0.12.3

### Steps to reproduce

1. Run the code snippet included.
2. Inspect the workspace panel.

**Comment by aviatesk** [comment]
How about this ?
![image](https://user-images.githubusercontent.com/40514306/77776030-be634600-7090-11ea-91f8-9ff4fc27a19b.png)

https://github.com/JunoLab/Atom.jl/pull/303 will address this.

**Comment by mewilhel** [comment]
Looks good to me. Thanks!
