### ISSUE TITLE
[BUG] Right click > "Add Project Folder" crashes 2nd time

### ISSUE THREAD

**Issue by ianshmean** [JunoLab/Juno.jl#548]
I'm seeing crashes interacting with the "add project folder" action in the project pane right click menu.

## Details
- Atom version: 1.45.0
- Julia version: 1.4
- OS: MacOS Catalina
- Package versions:
  - Atom.jl: 1.45.0
  - julia-client: 0.12.4
  - ink: 0.12.3

### Steps to reproduce

1. Open Atom
2. Right click the project pane > "Add Project Folder"
3. Click cancel
4. Right click the project pane > "Add Project Folder"
Crash

**Comment by ianshmean** [comment]
I also just got a crash trying to delete a file through right click > delete

**Comment by aviatesk** [comment]
reopen an issue on [atom](https://github.com/atom/atom/issues) or [tree-view](https://github.com/atom/tree-view) especially

**Comment by ianshmean** [comment]
Seems like it’s been fixed in Atom, but not made it past the nightly yet https://github.com/atom/atom/issues/20034

**Comment by aviatesk** [comment]
nice, it'd great if you can give the nightly a try, but it's possible Juno will be temporarily unfunctional since it comes with electron update.
