### ISSUE TITLE
[BUG] Juno on Atom only works for the 64x bitsversion 

### ISSUE THREAD

**Issue by MJKooiman** [JunoLab/Juno.jl#550]
Details
- Atom version:v0.12.10
- Julia version: Julia 1.4.0 win32bits
- OS: windows 10 home
  - julia-client:  Juno v0.8.1

The julia client Juno doesn't work while using the 32 bits version of Julia. It gives an methode error. Using the 64bits version solves the problem.

**Comment by pfitzseb** [comment]
Would be good to know what method error this gives.

**Comment by MJKooiman** [comment]
![image](https://user-images.githubusercontent.com/63341013/78780147-6edd1e00-799e-11ea-903b-ead01974f0b2.png)

**Comment by aviatesk** [comment]
Maybe JSON.jl always returns `Int64` even in 32bit machine ?

**Comment by aviatesk** [comment]
seems like so: https://github.com/JuliaIO/JSON.jl/pull/178

**Comment by aviatesk** [comment]
@MJKooiman can you try https://github.com/JunoLab/Atom.jl/pull/314 ?

**Comment by MJKooiman** [comment]
I have already switched to the 64x bit version. I can also use that one. I just wanted to repport for others.

**Comment by aviatesk** [comment]
ah I see. Since I don't have 32 bits, it would be appreciated if you can give a test on it.

**Comment by MJKooiman** [comment]
I understand. But I also don't have 32 bits anymore. Since I switched to 64bits
