### ISSUE TITLE
[BUG] 1-element tuple missing comma

### ISSUE THREAD

**Issue by JeffBezanson** [JunoLab/Juno.jl#556]
## Details
- Atom version: 1.45.0
- Julia version: 1.4
- OS:
- Package versions:
  - Atom.jl: 
  - julia-client: 0.12.4
  - ink:

### Steps to reproduce

When evaluating a 1-element tuple in-line, e.g. `(1,)` the result is displayed as `(1)` instead of `(1,)`.

**Comment by aviatesk** [comment]
will be fixed by: https://github.com/JunoLab/Atom.jl/pull/323 ;)
