### ISSUE TITLE
[BUG] REPL doesn't show some results

### ISSUE THREAD

**Issue by NightMachinary** [JunoLab/Juno.jl#560]
### Steps to reproduce

1. Select the code below and eval it by CMD+ENTER:
```
using FreqTables
prop(freqtable([1,1,1,2,3,4,4,4,4,4,4,5,1,2]))
```

2. Now eval the last line. Its result is not shown in the REPL. If we use `display(...)`, then it will work. If we use inline results, then it will also work.

## Details
# Atom:
Version: 1.45.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.7",
  "chrome": "69.0.3497.128",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
# julia-client:
Version: 0.12.4
Config:
{
  "consoleOptions": {
    "cursorStyle": "bar",
    "terminal": "/Applications/iTerm.app/Contents/MacOS/iTerm2 -e"
  },
  "firstBoot": false,
  "juliaOptions": {
    "formattingOptions": {
      "whitespace_typedefs": true
    }
  },
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true,
    "usePlotPane": false,
    "errorInRepl": true,
    "scrollToResult": true,
    "resultsDisplayMode": "console"
  }
}

# ink:
Version: 0.12.3
Config:
undefined

# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}

# language-julia:
Version: 0.19.3
Config:
undefined

# language-weave:not installed

# indent-detective:
Version: 0.4.0
Config:
undefined

# latex-completions:
Version: 0.3.6
Config:
undefined

# versioninfo():
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 2

Status `~/.julia/environments/v1.4/Project.toml`
  [c52e3926] Atom v0.12.10
  [6e4b80f9] BenchmarkTools v0.5.0
  [35d6a980] ColorSchemes v3.7.0
  [5ae59095] Colors v0.12.0
  [a93c6f00] DataFrames v0.20.2
  [864edb3b] DataStructures v0.17.12
  [31c24e10] Distributions v0.23.2
  [da1fdf0e] FreqTables v0.3.2
  [c91e804a] Gadfly v1.2.1
  [c8e1da08] IterTools v1.3.0
  [e5e0dc1b] Juno v0.8.1
  [438e738f] PyCall v1.91.4
  [03a91e81] SplitApplyCombine v1.0.0
  [f3b207a7] StatsPlots v0.14.5

**Comment by pfitzseb** [comment]
Works fine on master.
