### ISSUE TITLE
[BUG]  White Screen on ATOM at Startup on Ubuntu

### ISSUE THREAD

**Issue by compleathorseplayer** [JunoLab/Juno.jl#561]
I installed Atom 1.45 (and previous versions), the .deb version on Ubuntu 18.04
and all goes well until I try to start it, resulting in a blank white screen (unresponsive).
I am running MATE session, but error is the same if I connect using ssh from an X11 environment.

I have had this problem for about 6 months and nobody seems to have any idea.   There have
been various issues relating to the "white screen" issue dating back from some time ago under different versions and circumstances.  I posted on the 'Atom' forum but nobody has responded.

### Steps to reproduce

1.  Just start atom.   White screen.  Nothing.
2.  Start looking for alternative Julia IDE's

**Comment by pfitzseb** [comment]
Did you try the possible solutions suggested [here](https://discuss.atom.io/t/white-screen-on-startup/42544/13)?

In any case, this isn't an issue with Juno, so I'll close this.

**Comment by compleathorseplayer** [comment]
Thanks - the disable-gpu subcommand worked!!
I'm sorry for bringing this here, but I had searched/posted on the other forums (obviously missed
the one you found) over a period of about 6 months!!
