### ISSUE TITLE
[FR] Visualize start/end of loop/if/function

### ISSUE THREAD

**Issue by azev77** [JunoLab/Juno.jl#564]
I don't know what this is called but a lot of IDEs (Matlab/STATA etc) have it.
Note: it is very convenient/easy to click on "-" to fold code.

![image](https://user-images.githubusercontent.com/7883904/80136533-d3d46e80-856f-11ea-8818-8d9003a2a148.png)

Update: even the free Notepad++ has
![image](https://user-images.githubusercontent.com/7883904/80137378-2cf0d200-8571-11ea-817a-65fa08671376.png)

**Comment by pfitzseb** [comment]
We do have markers for folding code, but you need to hover over the gutter to see them with the default theme:
![grafik](https://user-images.githubusercontent.com/6735977/80137213-398e1e00-85a3-11ea-8f4a-b3adf28f6c9a.png)

**Comment by azev77** [comment]
@pfitzseb you're right! But I like seeing the bars that connect the beginning w/ end.
Is that an option in Juno?
![image](https://user-images.githubusercontent.com/7883904/80138275-8e657080-8572-11ea-9783-ff74b04ec93f.png)

Notepad++ is cool bc the inner loop bar is a different color than the outer loop bar...

**Comment by azev77** [comment]
Also in the Juno homepage they have nested vertical lines connecting: 
function w/ end
for w/ end
if w/ end

How can I set the option to make these lines viewable in Juno (without the ...)? 

![image](https://user-images.githubusercontent.com/7883904/80267048-28114880-866d-11ea-8f57-e49192210510.png)

**Comment by aviatesk** [comment]
see e.g. https://stackoverflow.com/questions/44761009/how-to-enable-the-vertical-lines-in-atom
