### ISSUE TITLE
add renderdefault(i, x) method

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/Juno.jl#57]
So packages can fall back to default Juno rendering even though they provide a specialized `show` method for their type.

**Comment by MikeInnes** [comment]
Good to have this factored out. Might be nice to have an explicit API for this like `Juno.renderdefault(MyType)`.

**Comment by ChrisRackauckas** [comment]
I still don't know why it's the default to use `show` though. There are many cases where I have to use Juno just to override that. I think that's trying to be too smart.

**Comment by MikeInnes** [comment]
I don't like it that much either, but if we don't do it then we get complaints that e.g. BenchmarkTools doesn't display correctly and have to special-case a bunch of things.

**Comment by ChrisRackauckas** [comment]
I thought the complaint about BenchmarkTools was precisely because they had an override of `show` that made it print only the minimum time?

**Comment by MikeInnes** [comment]
Juno's rendering of `BenchmarkTools.Trial` is pretty unhelpful, it's just a list of trials – the default `show` method does all the calculations. Same with dataframes etc.

**Comment by ChrisRackauckas** [comment]
Where is this all being done so that they don't have to add dependencies? Is there a way others can PR to plug into that?
