### ISSUE TITLE
Force update Plot pane

### ISSUE THREAD

**Issue by cormullion** [JunoLab/Juno.jl#58]
I want to display an image in the Plot pane. While I can get it to work once, the display is very reluctant to update when the file changes. I've cobbled together this (M-ish)WE:

```
using Juno, Hiccup

mutable struct MyType
    filename::String
end 
 
Juno.media(MyType, Media.Plot)
Juno.media(MyType, Media.Graphical)

function Juno.render(pane::Juno.PlotPane, img::MyType)
    Juno.render(pane, Hiccup.div(Hiccup.img(src=img.filename)))
end

cd("/tmp")
m = MyType("/tmp/test.svg")

randtext = string(rand(1:20))
r, g, b = rand(0:256,  3)

open(m.filename, "w") do f
    println(f, """<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="250" height="250"> \n
    <rect x="0" y="0" width="250" height="250" fill="rgb($r, $g, $b)" /> \n """)

    println(f, """<text x="100" y="100" font-size="34px" fill="white" font-family="Helvetica-Bold">$(randtext)</text>\n""")

    println(f, "</svg>")
end

display(m)
```

Every time this runs it changes the file on disk, but you can't see the changes in the Plot pane. Its memory is very tenacious—surviving a Juno restart... Either there's a way to force it to update, or I'm doing something wrong and/or stupid
... ? :)

**Comment by pfitzseb** [comment]
[The joy of browser technologies...](http://stackoverflow.com/questions/1077041/refresh-image-with-a-new-one-at-the-same-url)

Changing your render method to 
```julia
function Juno.render(pane::Juno.PlotPane, img::MyType)
    Juno.render(pane, Hiccup.div(Hiccup.img(src=img.filename*"?$(time())")))
end
```
works for me. I'm relatively sure we can't work around this on our side.

**Comment by cormullion** [comment]
Oh, of course, that must be the cause. Perhaps the other packages write to a new file each time... 

Your solution works and is cool. :)

**Comment by pfitzseb** [comment]
Yeah, I think other packages use something like `tempname()`. Using the same file does seem nicer though :)
