### ISSUE TITLE
Error Downloading

### ISSUE THREAD

**Issue by Ifihanolusheye** [JunoLab/Juno.jl#580]
Tried downloading Juno in Atom and I kept on getting this error
`Error: Installing “julia-client@0.12.4” failed.`

**Comment by Lance729** [comment]
Have you Solved it?
I am also facing this  problem.

**Comment by aviatesk** [comment]
http://docs.junolab.org/dev/man/update/#Update-Instructions-1

**Comment by Ifihanolusheye** [comment]
> Have you Solved it?
> I am also facing this problem.

Yeah
I've found an alternative

**Comment by Ifihanolusheye** [comment]
https://medium.com/@Ifihan_/an-alternative-way-to-install-juno-853f1455cf39
