### ISSUE TITLE
[BUG] ERROR: type UnionAll has no field hasfreetypevars

### ISSUE THREAD

**Issue by VoSiLk** [JunoLab/Juno.jl#582]
Occurs when try to enter the debug mode via Run Block

## Details
- Atom version: 1.45.0
- Julia version: 1.4.0
- OS: Windows Server 2016
- Package versions:
  - Atom.jl: 0.12.10
  - Juno.jl: 0.8.1
  - julia-client: 0.12.4
  - ink: 0.12.3

**Comment by aviatesk** [comment]
Please reopen an issue at https://github.com/JuliaDebug/JuliaInterpreter.jl/issues with minimum reproducible example.
