### ISSUE TITLE
[BUG]uber-juno installation gets stuck with a blank text input dialog

### ISSUE THREAD

**Issue by pauljurczak** [JunoLab/Juno.jl#584]
I just installed Atom v1.47.0 on Ubuntu 18.04 using atom-amd64.deb, launched it and selected `uber-juno` extension for installation. I’m facing a grayed-out window with a mysterious text input dialog. Menu bar is active, except of most of Juno sub-menu. The installation does not progress past this point:

![Screenshot from 2020-05-19 21-22-30](https://user-images.githubusercontent.com/4933032/82404697-2c881180-9a1f-11ea-9321-c9c5922884e7.png)

After clicking around the main menu, I clicked Juno->Release Note and `uber-juno` installation got unstuck.

**Comment by pfitzseb** [comment]
Hm, weird. Could you just `Escape` out of that dialogue?

**Comment by pauljurczak** [comment]
I tried typing into it with no effect. It came into focus when I clicked on it. I don't think I hit `Esc`. In case you don't do it, maybe you could add testing `uber-juno` on fresh `Atom` installation as was my use case here.

**Comment by pauljurczak** [comment]
I followed the same installation path on another PC with Ubuntu 18.04 and I did not observe this problem. I will close this issue, since it is minor and hard to reproduce.
