### ISSUE TITLE
[BUG] Gadfly plots do not render in plot pane

### ISSUE THREAD

**Issue by evanfields** [JunoLab/Juno.jl#586]
Since updating to the latest Juno this morning, Gadfly plots no longer render in the plot pane. If I make multiple `Gadfly.plot` calls, the plot pane navigation buttons light up as if I can navigate between plots - but no plot is shown.

## Details
- Atom version: 1.47.0 x64
- Julia version: 1.4.1
- OS: MacOS 10.15.3
- Package versions:
  - Atom.jl: 0.12.11
  - julia-client: 0.12.5
  - ink: 0.12.4

### Steps to reproduce

1. Open a fresh Atom/Juno session.
2. In the REPL, `using Gadfly; plot(x = rand(10), y = rand(10), Geom.point)`

**Comment by pfitzseb** [comment]
Dup of https://github.com/JunoLab/Juno.jl/issues/583. The recent Atom update broke that functionality.
