### ISSUE TITLE
[BUG]Installing “julia-client@0.12.5” failed

### ISSUE THREAD

**Issue by Lance729** [JunoLab/Juno.jl#588]
Even thought the Juno have successfully installed in Atom@1.45.0 at first, the julia-clientn package fails to build after the Atom updates to latest version 1.47.0. Then I uninstall this package, reuse Atom@1.45.0 and suffer following problem:
<img width="642" alt="截屏2020-05-22 上午9 58 39" src="https://user-images.githubusercontent.com/58027404/82625269-49873500-9c17-11ea-8392-57e0ad968ef4.png">

#68  Details
- Atom version: 1.45.0
- Julia version: 1.4
- OS: MacOS 10.15.4

- Package versions:
  - Atom.jl: 0.12.11
  - julia-client:0.12.5
  - ink: 0.2.9

**Comment by aviatesk** [comment]
follow [our update instruction](http://docs.junolab.org/dev/man/update/#Update-Instructions-1)
