### ISSUE TITLE
[BUG] Autocompletion for `For` should prefer `ForwardDiff` over `for`

### ISSUE THREAD

**Issue by dpsanders** [JunoLab/Juno.jl#590]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 0.12.5
- Julia version: 1.4.1
- OS: MacOS
- Package versions:
  - Atom.jl: 0.12.11
  - julia-client: 0.12.5
  - ink: 0.12.4

### Steps to reproduce
1. `using ForwardDiff`
2. Type `For` and press `<TAB>`

Given that I type `For` with a capital `F`, I am looking for a package (or maybe a type) starting with `For`, rather than a `for` loop.

In general, capitalisation should be respected in autocompletions.

**Comment by aviatesk** [comment]
close in favour of https://github.com/JunoLab/FuzzyCompletions.jl/issues/2#issue-623086414

you can also go back to previons REPL like  completions via config

**Comment by dpsanders** [comment]
Thanks. I am trying to work out where the config option is, but can't find it.

**Comment by dpsanders** [comment]
OK, found it: "Julia options" in the `julia-client` package.
