### ISSUE TITLE
[BUG] Horizontal hover-over scroll bar prevents mouse access to expansion

### ISSUE THREAD

**Issue by ianshmean** [JunoLab/Juno.jl#592]
On MacOS, the hover-only horizontal scroll bar that appears for long messages makes expanding in-line results almost impossible.

One idea for a fix would be increasing the height of the in-line results so that the expand button has some space above the scroll bar.

There’s currently a few pixel high accessible clickbox on the expander when the scrollbar appears.
![C60C2AD0-0C57-4F4D-8C19-B1B1764C68EA](https://user-images.githubusercontent.com/1694067/83374634-32c0ab00-a39a-11ea-87fd-0efc60152c16.jpeg)

**Comment by aviatesk** [comment]
I can repro this, let's just hide the scroll bar.
xref: https://github.com/JunoLab/atom-ink/pull/279
