### ISSUE TITLE
Juno Documentation

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Juno.jl#6]
Juno needs some documentation (generally the infromation has passed in the Gitter chat and the Discourse forum, but there's enough repetition that this would really help). Some of it is already written, but I think it should all be compiled in one spot. Here's what I thought of so far:
- Juno standard installation instructions
- Some basic usage instructions:
  - How to open the workspace pane
  - What's compatible with the plot pane
  - Adding keyboard shortcuts
  - Some basic keyboard commands
  - Using the debugger
  - A longer description of the options in the settings panel
- FAQ
  - Current list of common issues and fixes (i.e. the Juno.jl precompilation + `using Atom` fix)
  - Where to leave issues (I don't really know) 
- Juno.jl front-end instructions (essentially what you have in the README, expand a little more)
- Developer Docs
  - Developer install
  - Version specific installation instructions (for right now, v0.6, and try to keep it as up-to-date as possible)
  - What packages do what (I'll fill in what I can but some of this will need other input)
  - A description of the new CI for the Juno stack

I'll put a PR in (this weekend?) to get this generally together over the weekend (Documenter.jl with the native HTML rendering).

**Comment by MikeInnes** [comment]
This would be great and if you want to help out I'm sure that it'd be highly appreciated by many. Note also that we have the manual folder in julia-client which makes a start on this. I don't know how well documenter works for more manual-style content but it'd be great to try it out.

**Comment by ChrisRackauckas** [comment]
I have the documentation coming along here: [JunoDocs.jl](https://github.com/ChrisRackauckas/JunoDocs.jl).

Like the PR I just put in, I realized that Juno.jl should be small since it's the dependency that you're asking for developers to accept, so the documentation should not overlap with this package. Thus I made it its own repository. Some of the links are not in yet because I am waiting for the org migration (could I get membership to migrate it?) and I am still filling out some pages (some of the dev docs will be left blank for you to fill in. I'll let you know which ones).

**Comment by MikeInnes** [comment]
Awesome. Me and @pfitzseb should take a look over things and make sure the setup looks like a good fit, then we can go ahead with this stuff. Looking forward to having the docs!

**Comment by ChrisRackauckas** [comment]
Note that because of JuliaDocs/Documenter.jl#300 I haven't fixed the urls for any images since the only way I know to make them work with Documenter is via absolute paths.

**Comment by ChrisRackauckas** [comment]
Hey, big updates to it:

- The image links are relative so they should be showing now.
- The documentation is mostly complete. Places which still need to be filled in are: 
   - Adding your own keyboard shortcuts (I always forget how...)
   - Using the Debugger 
   - Juno CI (a devdoc spot to explain the new CI)

**Comment by MikeInnes** [comment]
Chris, this looks like really good work and I'm excited to get this set up properly. I added you to JunoLab so you can transfer the repo; if that's not enough, let me know.

**Comment by ChrisRackauckas** [comment]
Hey, the transferred docs are hidden because the junolab.org server is in charge of them, but didn't want to display them "at the normal place". I added a CNAME to try to get it to display at docs.junolab.org, but I think you need to do something on the server to allow it:

https://help.github.com/articles/troubleshooting-custom-domains/#dns-configuration-errors

https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

**Comment by MikeInnes** [comment]
I set up the docs.junolab subdomain – I think it may take a while to update everywhere though.

**Comment by pfitzseb** [comment]
Since docs.junolab.org is working now, I'll close this.

Thanks again for setting this up, Chris!

**Comment by fb87** [comment]
This link shows the GitHub page - you have to link docs.junolab.org to docs.junolab.org/latest or create a new starting page.

**Comment by ChrisRackauckas** [comment]
>This link shows the GitHub page

Hey, is there a bad link someone? Indeed, it should all be `docs.junolab.org/latest` and anywhere without the `/latest` will go to the Github page, but all of the links I've tried are correct. If you could point me to the bad link / put in a PR that would be great!

**Comment by fb87** [comment]
Yes, without /latest/ it points to a part of the github page, could this be forwarded to /latest, since the half GitHub page makes not much sense to me…

**Comment by ChrisRackauckas** [comment]
>Yes, without /latest/ it points to a part of the github page, could this be forwarded to /latest, since the half GitHub page makes not much sense to me…

I see what you mean. I made a redirect for `docs.junolab.org` to `docs.junolab.org/latest`. Please test it out to make sure it works for you!

**Comment by fb87** [comment]
Nice, works, thanks!

Today I went to this page and was wondering why I couldn't find any documentation anywhere and was looking for junodocs.jl for information… So no more confusing visitors. :)
