### ISSUE TITLE
[BUG] Base.:* = ... (and not Base.:+ or Base.:/) causes internal error

### ISSUE THREAD

**Issue by VitaminBrad** [JunoLab/Juno.jl#604]
## Details
- Atom version: 1.49.0
- Julia version: 1.4.2
- OS: Linux (Fedora 32)
- Package versions:
  - Atom.jl:
  - julia-client:
  - ink:

### Steps to reproduce

1. `Base.:*(a::String,b::String) = string(a,"*",b)`
and not 
`Base.:+(a::String,b::String) = string(a,"+",b)` 
or
`Base.:/(a::String,b::String) = string(a,"/",b)`
causes 
![](https://i.imgur.com/ndBiPwy.png)
the REPL still works perfectly fine, but running any line directly in the script causes the above to appear again.

With an active project:
1. `Base.:*(a::String,b::String) = string(a,"*",b)`
and not 
`Base.:+(a::String,b::String) = string(a,"+",b)` 
or
`Base.:/(a::String,b::String) = string(a,"/",b)`
causes 
![](https://i.imgur.com/e8yZFx7.png)
once again the REPL still works perfectly fine, but running any line directly in the script causes the above to appear again.

Thanks!

**Comment by VitaminBrad** [comment]
I just noticed that Base.:*(a::String,b::String) is the only function actually already defined. That might be what's causing the problem.

**Comment by pfitzseb** [comment]
Yeah, by re-defining `Base.:*(a::String,b::String)` you end up breaking a bunch of things. Not much we can do about that, unfortunately.
