### ISSUE TITLE
Option for starting Julia with N threads

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Juno.jl#61]
Multithreading is already very useful. It would be nice if it was easy to make Juno always start with a desired number of threads.

**Comment by pfitzseb** [comment]
While specifying startup options for Julia would be cool in general, can't you just add `addprocs(N)` to `.junorc.jl` (or `.juliarc.jl`)? Or is there some fundamental difference between the two?

**Comment by ChrisRackauckas** [comment]
No, that's multiprocessing. Threads is an environment variable that has to be set before Julia starts.

https://docs.julialang.org/en/stable/manual/parallel-computing/#setup

**Comment by pfitzseb** [comment]
Right, my bad (not enough coffee or something). This would indeed be nice to have.
