### ISSUE TITLE
[BUG] Juno REPL Display Error with 4K Monitor and Ubuntu 20.04

### ISSUE THREAD

**Issue by qin-yu** [JunoLab/Juno.jl#618]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.53.0
- Julia version: 1.5.3
- OS: Ubuntu 20.04
- Package versions:
  - Atom.jl: 0.12.27
  - Juno.jl: 0.8.4
  - julia-client: 0.12.6
  - ink: 0.12.5

### Steps to reproduce

1. Start Juno installed on a Ubuntu machine with a 4K display (not sure if it has something to do with the resolution);
2. Close the lid / put the system to sleep
3. Wake up and enter password
4. The REPL has some display error (no showing every character)
![Screenshot from 2020-12-16 15-20-05](https://user-images.githubusercontent.com/17722010/102395069-f1f94e00-3fda-11eb-944b-82a2999a6aa0.png)

**Comment by pfitzseb** [comment]
Try switching to another terminal renderer in the julia-client settings. This is a known issue with xterm.js.

**Comment by qin-yu** [comment]
Thanks! I just tried all the options: `webgl`, `canvas` and `dom`. Only `dom` works after suspend the machine. Should I close the issue? It seems that it's still an issue!

> Try switching to another terminal renderer in the julia-client settings. This is a known issue with xterm.js.

**Comment by pfitzseb** [comment]
I don't think there's anything we can do about this here, so yeah, will close the issue.
