### ISSUE TITLE
UndefVarError: isnothing not defined (after print() or println())

### ISSUE THREAD

**Issue by AlexisMrc** [JunoLab/Juno.jl#619]
I am starting with Julia and I have this message of internal error each time I write "**print()**" or "**println()**" in my script on Atom : 

UndefVarError: isnothing not defined
(::getfield(FuzzyCompletions, Symbol("##1#2")){FuzzyCompletions.MethodCompletion})(::Base.GenericIOBuffer{Array{UInt8,1}}) at FuzzyCompletions.jl:128
#sprint#326(::Nothing, ::Int64, ::Function, ::Function) at io.jl:101
sprint at io.jl:97 [inlined]
_completion_text at FuzzyCompletions.jl:128 [inlined]
completion_text at FuzzyCompletions.jl:133 [inlined]
completion_text at completions.jl:175 [inlined]
completiontext at completions.jl:259 [inlined]
completion(::Module, ::FuzzyCompletions.MethodCompletion, ::String) at completions.jl:251
_broadcast_getindex at broadcast.jl:582 [inlined]
getindex at broadcast.jl:515 [inlined]
macro expansion at broadcast.jl:846 [inlined]
macro expansion at simdloop.jl:73 [inlined]
copyto! at broadcast.jl:845 [inlined]
copyto! at broadcast.jl:800 [inlined]
copy at broadcast.jl:776 [inlined]
materialize at broadcast.jl:756 [inlined]
fuzzycompletionadapter(::String, ::String, ::String, ::Int64, ::Int64, ::Bool) at completions.jl:158
(::getfield(Atom, Symbol("##275#276")))(::Dict{String,Any}) at completions.jl:54
handlemsg(::Dict{String,Any}, ::Dict{String,Any}) at comm.jl:169
(::getfield(Atom, Symbol("##31#33")){Array{Any,1}})() at task.jl:259

I do not know how to stop this message. If someone can help me I would be grateful !

## Details
<img width="1440" alt="Capture d’écran 2020-12-23 à 07 49 02" src="https://user-images.githubusercontent.com/53317398/102967974-593f6280-44f3-11eb-889b-85fd8d891efa.png">

- Atom version: 1.53.0
- Julia version: 1.0.5 (2019-09-09)
- OS: macOS Big Sur 11.1 
- Package versions:
  - Atom.jl: 
  - julia-client: 0.12.6
  - ink:

### Steps to reproduce

1. 
2.

**Comment by aviatesk** [comment]
please update your Julia version higher than 1.1
