### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zaki-29871** [JunoLab/Juno.jl#621]
Shortcut key for opening Juno's Setting is "Ctrl+J, Ctrl+,", but not "Ctrl+J, Ctrl+,]"

**Comment by pfitzseb** [comment]
Yes. Where is it listed as <kbd>Ctrl+J Ctrl+,]</kbd>?

**Comment by zaki-29871** [comment]
![Snipaste_2021-01-21_19-26-32](https://user-images.githubusercontent.com/18009246/105345050-b88db100-5c1e-11eb-8c46-9f6d572b201f.png)

here, thanks for replying

**Comment by zaki-29871** [comment]
Oh, I found that is should not include "]", I think is not a bug, sorry about that
