### ISSUE TITLE
Phi (possibly also other greek letters) behaving different in comments and code

### ISSUE THREAD

**Issue by MarcusBecker-GitHub** [JunoLab/Juno.jl#631]
![image](https://user-images.githubusercontent.com/75479673/114842854-8b920a00-9dd9-11eb-8985-60060ae61bdc.png)

In my Juno, \phi in code returns what in LaTeX would be \varphi and vice versa. In the comments however, \phi and \varphi return the expected symbol. The screenshot shows only the use of \phi
(Juno 0.12.6, Julia 1.5.3, UTF-8)

**Comment by pfitzseb** [comment]
That's a font issue -- the italics variant switches phi and varphi. I'd recommend using [JuliaMono](https://juliamono.netlify.app/) (or any other consistent font):
![image](https://user-images.githubusercontent.com/6735977/114845977-85e9f380-9ddc-11eb-9eeb-f79d2da026c8.png)
