### ISSUE TITLE
[BUG] Julia has exited. Press Enter to start a new session. 2 deprecations

### ISSUE THREAD

**Issue by NateNesbitt** [JunoLab/Juno.jl#633]
Today when I tried to start Julia in Atom by pressing "Enter" in REPL, it immediate gave me "Julia has exited. Press Enter to start a new session." There is also a warning about there being 2 deprecations. If I click for details on the deprecations, I get the following:

Use require("electron").shell instead of require("shell")

Object.<anonymous> - C:\Users\nnesbitt\AppData\Local\atom\app-1.56.0\resources\app.asar\exports\shell.js:4:6
Object.<anonymous> - C:\Users\nnesbitt\AppData\Local\atom\app-1.56.0\resources\app.asar\exports\shell.js:9:3
Module._compile - <embedded>:11:149837
Object..js - <embedded>:11:153385
Module.load - internal/modules/cjs/loader.js:815:32
Module._load - internal/modules/cjs/loader.js:727:14
Use require("electron").remote instead of require("remote")

Object.<anonymous> - C:\Users\nnesbitt\AppData\Local\atom\app-1.56.0\resources\app.asar\exports\remote.js:4:6
Object.<anonymous> - C:\Users\nnesbitt\AppData\Local\atom\app-1.56.0\resources\app.asar\exports\remote.js:11:3
Module._compile - <embedded>:11:149837
Object..js - <embedded>:11:153385
Module.load - internal/modules/cjs/loader.js:815:32
Module._load - internal/modules/cjs/loader.js:727:14

## Details
- Atom version: 1.56.0
- Julia version: 
- OS: Windows 10
- Package versions:
  - Atom.jl: 
  - julia-client: 0.12.6
  - ink: 0.12.6

# Atom:
Version: 1.56.0
Dev Mode: false
Official Release: true
{
  "node": "12.14.1",
  "v8": "8.3.110.13-electron.0",
  "uv": "1.33.1",
  "zlib": "1.2.11",
  "brotli": "1.0.7",
  "ares": "1.15.0",
  "modules": "80",
  "nghttp2": "1.40.0",
  "napi": "5",
  "llhttp": "2.0.1",
  "http_parser": "2.8.0",
  "openssl": "1.1.0",
  "icu": "65.1",
  "unicode": "12.1",
  "electron": "9.4.4",
  "chrome": "83.0.4103.122"
}
# julia-client:
Version: 0.12.6
Config:
{
  "currentVersion": "0.12.6",
  "firstBoot": false,
  "juliaPath": "C:\\Users\\nnesbitt\\AppData\\Local\\Julia-1.3.1\\bin\\julia.exe",
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true
  }
}

# ink:
Version: 0.12.6
Config:
undefined

# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}

# language-julia:
Version: 0.21.1
Config:
undefined

# language-weave:not installed

# indent-detective:
Version: 0.4.0
Config:
undefined

# latex-completions:
Version: 0.3.6
Config:
undefined

Could not connect to Julia.

### Steps to reproduce

1. Open Atom
2. Click in REPL
3. Press Enter to start Julia.

**Comment by pfitzseb** [comment]
The instructions at http://docs.junolab.org/latest/man/update/ should resolve this issue. Deprecations are unrelated.

**Comment by NateNesbitt** [comment]
Thanks! That worked.
