### ISSUE TITLE
I have the following installation error for Juno 0.6 on a Windows PC running Julia 0.6

### ISSUE THREAD

**Issue by mwsohn** [JunoLab/Juno.jl#66]
Installing “julia-client@0.6.0” failed.Hide output…

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Min\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Min\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Min\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Min\\.atom\\.apmrc" "install" "C:\\Users\\Min\\AppData\\Local\\Temp\\d-117519-6316-lom4v7.qk8gyfd2t9\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file C:\Users\Min\.atom\.apm\underscore-plus\1.6.6\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\Min\.atom\.apm\underscore-plus\1.6.6\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Min\AppData\Local\Temp\apm-install-dir-117519-6316-1epymrk.6x7rhhbyb9\npm-debug.log

I found that the package.json file contains nothing but null bytes.

**Comment by pfitzseb** [comment]
This seems like a corrupted download -- try renaming `C:\Users\Min\.atom\.apm` to something else and restart Atom.

**Comment by mwsohn** [comment]
That solved the issue. Thank you.

**Comment by pfitzseb** [comment]
Great! Enjoy Juno! :)
