### ISSUE TITLE
@progress for while loop

### ISSUE THREAD

**Issue by KadeG** [JunoLab/Juno.jl#72]
[ProgressMeter.jl](https://github.com/timholy/ProgressMeter.jl) can be used "for tasks such as reading file data where the progress increment varies between iterations" (though I get errors for `update!()`...) Could this feature be added to `@progress`? ProgressMeter.jl's implementation uses `position(IOStream)`.

**Comment by pfitzseb** [comment]
Did you have a look at the [docs](http://docs.junolab.org/latest/man/juno_frontend.html#Progress-Meters-1)? You can just do something like
```julia
Juno.progress(name="quadratic") do p
  i = 1
  while i < 10
    sleep(1)
    i += 1
    Juno.progress(p, i^2/100)
  end
end
```
Not sure if there's any value to adding this kind of functionality to the macro though.

**Comment by KadeG** [comment]
Thanks! Just tested it with
```
Juno.progress(name = "readfile") do readfile
    file = open("testData.bin")
    while !eof(file)
        data = read(file, Float64, 1)
        Juno.progress(readfile, position(file) / filesize(file))
    end
    close(file)
end
```
and it works well.
