### ISSUE TITLE
Improve rendering of Vector of Vectors

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#73]
Vector of Vectors is a common interface that many packages use, including the ultra famous DifferentialEquations. In the REPL, those are represented wonderfully:
```julia
julia> a = [rand(3) for i in 1:5]
5-element Array{Array{Float64,1},1}:
 [0.868189, 0.466908, 0.903934]
 [0.384618, 0.766843, 0.731352]
 [0.281518, 0.563307, 0.495208]
 [0.903727, 0.942015, 0.764291]
 [0.337518, 0.761427, 0.836121]
```
however, in the console of Juno you have:
![image](https://user-images.githubusercontent.com/19669089/29830692-9d8b5084-8ceb-11e7-9b2f-ef27a33000e2.png)
which is (sorry for the expression) completely useless. Not only I am seeing the same type again and again, which I already know due to the fact that all elements in a `Vector` *must* be of the same type, but I also need to click **countless** times to see some numbers. 

I tried to change that, but it only did bad things. It actually broke everything! First of all, I simply tried `Base.show(a)`. This doesn't work, everything is printed linearly and not in awesome columns. I wish I knew what was the function that base uses for printing this awesome thing. It isn't `showarray()` either because this is also linear. I spent a lot of time in the source file `show.jl` but couldn't crack it!

Then I tried to just straight-out implement my own printing in Juno. For the following, I simply define
`const Dataset{D, T} = Vector{SVector{D, T}}` simply for shorthand. The first thing was to create a function that works similarly to how REPL prints:
```julia
function stringrep(d::Dataset, nshow::Int=21, ndigits::Int=5)
  iseven(nshow) && throw(ArgumentError("nshow must be odd"))
  n = min(nshow, length(d))
  s = ""
  if n < nshow
    for i in 1:n
      s *= string(" ", v[i], "\n")
    end
  else
    for i in 1:(n÷2)
      s *= string(" ", v[i], "\n")
    end
    padlen = length(string(v[n÷2]))÷2
    s *= lpad("⋮\n", padlen+1)
    for i in (length(v)-(n÷2)+1):length(v)
      s *= string(" ", v[i], "\n")
    end
  end
  return s
end
```
and then apply that to Juno:
```julia
  function Juno.render(i::Juno.Inline, d::Dataset{D,T}) where {D,T}
    N = length(d)
    Juno.render(
      Juno.Tree(Text("$D-dimensional Dataset{$T} with $N points"),
        [Juno.Text(stringrep(d))])
    )
  end
```
that worked. It now showed the Vectors of SVectors like it does in base. However, it broke many other things. It broke for example how many objects that have as a field a Vector of Vectors, are rendered. Look at the comparison figure:

![print_vov](https://user-images.githubusercontent.com/19669089/29831815-f9f798c0-8cee-11e7-92e2-c0a6fa74c1c7.jpg)

Notice that on the "AFTER" the printing goes on for many PAGES!!! What is happening (I think) is that the internal structure is broken and now all fields of a type (e.g. `sol`) are auto-exanded instead of having the neat down-arrow everything has. For example in the AFTER the field `k`  is auto-expanded.

I understand that you may have many reasons to not change this. But could you please at least give me some way to change it for myself (and others that may want it)?

**Comment by ChrisRackauckas** [comment]
One thing I have to note is that it should be careful how each internal vector is rendered. Currently when it "unrolls" it does the shortened print. This is nice it's not uncommon for me (and I'd assume others) to use this stuff where instead of `Vector` of small `Vector`, it could be a `Vector` of 3-tensor, or more. So the printed form for each element could be a wall of text. I think the current way of "opt-in to see it" is good because otherwise it can be a very heavy print, but I do admit it could be better.

**Comment by Datseris** [comment]
It is important to note that I am referring to Vector of Vector **only**. Not to Vector of Arrays. And of course, my case there can be an easy check to not print everyting if the inner vectors have more than 10 elements, but print only the first 5 and last 5.

**Comment by Datseris** [comment]
I have solved my problem. I had to use a new `struct` though, a container for a vector of vectors. What I did was the following:

Define a 
```julia
struct Dataset{
  D, T<:Number, V<:Union{Vector{T}, SVector{D,T}}}
  data::Vector{V}
end
```
along with a convert method:
```julia
function Base.convert{D, T}(::Type{Matrix}, d::Dataset{D,T})
  mat = Matrix{T}(length(d), D)
  for i in 1:length(d)
    mat[i,:] .= d.data[i]
  end
  mat
end
```

Then, define a function that uses the representation of base (magic that @pfitzseb knows how it works):
```julia
function matstring(d::Dataset)
  N = length(d); D = dimension(d)
  if N > 50
    mat = zeros(eltype(d), 50, D)
    for (i, a) in enumerate(chain(1:25, N-24:N))
      mat[i, :] .= d[a]
    end
  else
    mat = convert(Matrix, d)
  end
  s = sprint(io -> show(IOContext(io, limit=true), MIME"text/plain"(), mat))
  s = join(split(s, '\n')[2:end], '\n')
  tos = "$D-dimensional Dataset with $N points ($(vectorname(d))):"*"\n"*s
  return tos
end
@require Juno begin
  function Juno.render(i::Juno.Inline, d::Dataset{D, T, V}) where {D, T, V}
    N = length(d)
    tos = matstring(d)
    Juno.render(
      Juno.Tree(Text(tos), []))
  end
end
```
this produces this **BEAUTIFUL** output on the console: 
![image](https://user-images.githubusercontent.com/19669089/30274717-ed4f17d2-96fe-11e7-9000-58ab70ef2746.png)

I am so happy. I hope this post may help somebody in the future!
