### ISSUE TITLE
Toggle documentation  command only opens it, but does not close it.

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JunoLab/Juno.jl#78]
I use Atom 1.21.1 on Windows 10.

When I toggle documentation for a function, a "panel" with the documentation opens below. There does not appear to be any way of getting rid of it, in particular "toggle documentation" command does not get rid of this "panel".

**Comment by pfitzseb** [comment]
Dup of https://github.com/JunoLab/atom-julia-client/issues/336.
Try `Esc` until I've figured out the proper behaviour for this :)

**Comment by PetrKryslUCSD** [comment]
Thanks.  I've actually tried that:  Esc closes the latest documentation panel, but not any of the  previously opened ones.
