### ISSUE TITLE
Compatibility with atom-ide

### ISSUE THREAD

**Issue by BenJWard** [JunoLab/Juno.jl#81]
Atom now has packages such as atom-ide-ui, and other languages have a *-ide package which works with it. I was wondering if Juno features could be made useable with the atom-ide-ui system. For example, I think I had to disable the linter I previously used in favor of atom-ide-diagnostics which does linting and other jobs.

**Comment by pfitzseb** [comment]
[This](https://github.com/pfitzseb/atom-julia-lsp-client) provides some LSP functionality, but proper Juno integration isn't trivial. We'll definitely take a look at this soonish though.

**Comment by aviatesk** [comment]
Close since now atom-ide-ui is dead and we definitely don't want to go along with it.
