### ISSUE TITLE
Allow custom Module switching

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Juno.jl#85]
Currently the module switches automatically if a file is included via `include` in the module core file.

To the best of my knowledge there is no other way to do this automatic switch.

I am requesting a way to do just that: implement some rule, or any kind of option that allows scripts to change the current module upon activating the atom panel.

One simple way would be for this module automatic switch to also happen in commented include commands:
```julia
module Mod

include("f.jl") # automatic switch
# include("g.jl") #I Would also like automatic switch here

end
```

**Comment by pfitzseb** [comment]
Dup of #20 (forgot about that issue).
