### ISSUE TITLE
Render resets

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Juno.jl#86]
I got this piece of code from @pfitzseb 

```julia
Juno.@render Juno.Inline x::DESolution begin
  fields = fieldnames(typeof(x))
  Juno.LazyTree(typeof(x), () -> [Juno.SubTree(Juno.Text("$f → "), Juno.getfield′(x, f)) for f in fields])
end
```

and I use it on all of my abstract array types to get rid of the rendering override. Could there just be a simple function to call instead?

**Comment by pfitzseb** [comment]
http://docs.junolab.org/latest/man/info_developer.html#Juno.defaultrepr
