### ISSUE TITLE
Small console issues

### ISSUE THREAD

**Issue by MikeInnes** [JunoLab/Juno.jl#89]
Just logging here for reference:

* Should boot to `$SHELL` by default
* Would be nice to see `Booting...` or similar, rather than a blank terminal, when booting
* The "julia has exited" message doesn't show until I press a key
* Varies whether I see a Julia banner or not (I guess due to the cycler? If so we should probably log output from the process).
* I can imagine it being useful to keep output from an old session around – so maybe we should make clearing always explicit, rather than doing it on boot?
* `println` leaves an extra newline now (presumably to fix the issue with `print`). Not sure if there's a way to detect the right thing to do here.

**Comment by pfitzseb** [comment]
> Should boot to $SHELL by default

Should be fixed on master.

> Would be nice to see Booting... or similar, rather than a blank terminal, when booting

Makes sense I guess.

> The "julia has exited" message doesn't show until I press a key

Hm. It works great for me on linux and not-so-great on Windows.

> Varies whether I see a Julia banner or not (I guess due to the cycler? If so we should probably log output from the process).

I was actually thinking of disabling the banner altogether, but logging the output and dumping it into the console on startup seems sane too.

> I can imagine it being useful to keep output from an old session around – so maybe we should make clearing always explicit, rather than doing it on boot?

Fair enough.

> println leaves an extra newline now (presumably to fix the issue with print). Not sure if there's a way to detect the right thing to do here.

Probably can adapt [this](https://github.com/JunoLab/Atom.jl/blob/master/src/repl.jl#L77-L118) to check for trailing newlines or something, I'll look into it.

**Comment by ChrisRackauckas** [comment]
Line breaks seem off sometimes.

![capture2](https://user-images.githubusercontent.com/1814174/34619043-a13c51f0-f1f5-11e7-862c-138bdc6a2819.PNG)

**Comment by pfitzseb** [comment]
Can you try resizing the console tab once? I think there's something wonky on windows.

**Comment by ChrisRackauckas** [comment]
It's still like that after resizing.

**Comment by pfitzseb** [comment]
Oh do you mean the extra space on the right? I think that's an upstream issue actually.

**Comment by ChrisRackauckas** [comment]
I mean the cutting of `OrdinaryDiff`
`Eq.jl`.

**Comment by MikeInnes** [comment]
> We could maybe also only hide the prompt if something is printed

Yeah that sounds good if possible.

I kind of like the banner; we could well have an option to disable it though.

It would be a good idea to boot on startup as well. One thing I've noticed occasionally, if I boot and quit repeatedly, is that the working indicator hangs on some boots; I *think* this may be due to autocomplete as no completions are available.

**Comment by pfitzseb** [comment]
> It would be a good idea to boot on startup as well.

That's exactly the same now as with the old console, i.e. the Cycler starts booting processes on Atom startup, but the Basic mode only does so on demand.

**Comment by MikeInnes** [comment]
Yeah, I guess that's so we don't boot loads of extra processes where it isn't necessary.

I thought we had on option for this at one point, but we should probably boot on startup when cycler mode is enabled.

**Comment by pfitzseb** [comment]
We do, we just don't connect automatically.

**Comment by MikeInnes** [comment]
Right, that's what I mean. It's just nice to see the banner, and if we're booting a process anyway it seems like there's no downside to connecting and showing that.

**Comment by pfitzseb** [comment]
I *think* all of these are fixed on latest master, except maybe for the "Julia has exited" thing, right @MikeInnes?

**Comment by MikeInnes** [comment]
yeah master is looking good :+1:

I'll test for a couple more days but I think we're about ready to cut a release on this
