### ISSUE TITLE
Standard layout not working on master

### ISSUE THREAD

**Issue by MikeInnes** [JunoLab/Juno.jl#90]
```
Uncaught TypeError: Cannot read property 'close' of undefined
/Users/mike/projects/julia-client/lib/ui/layout.js:50
```

Will definitely need this working for a JuliaPro release; it may be to do with the new console.

**Comment by MikeInnes** [comment]
In fact, it probably needs an overhaul anyway to use panes properly and expose the doc browser etc

**Comment by pfitzseb** [comment]
Yeah, I'll take a look. Should be easy enough to fix from the technical side.

**Comment by pfitzseb** [comment]
Ok, the error is fixed on master, but we should use docks instead of panes imho. What do you think about the following:
![image](https://user-images.githubusercontent.com/6735977/34891565-4bdd71da-f7d6-11e7-89af-4ad2f9feb05d.png)

**Comment by Datseris** [comment]
I always have the console on the right, and I cannot change it now after a year of getting used to it :P I would appreciate it if we can still move the console, just like now (which I guess that will be the case).

**Comment by pfitzseb** [comment]
So I was thinking -- should we make this a command instead of an option? Opinion, @MikeInnes?

**Comment by MikeInnes** [comment]
As in, to move the console to the right?

The layout system was originally designed so we could easily support multiple options; maybe we can add a console-on-right option there.

**Comment by pfitzseb** [comment]
No, I meant have a command `Change To Standard Layout` instead of a setting that checks on each startup etc. We could even call that once on initialization when used with JuliaPro.
There doesn't seem to be any need to reconfigure everything on startup since Atoms deserialization of the workspace works pretty well.

**Comment by MikeInnes** [comment]
> We could even call that once on initialization when used with JuliaPro.

Ah ok. It seems like a good idea, but it'd still be nice to have the option to turn it off in JuliaPro (or turn it on in a normal install), right?

**Comment by pfitzseb** [comment]
TIL that we already had that command: `Julia: Standard Layout`. Do you think there's any need for a setting that does this or is a command sufficient?

**Comment by MikeInnes** [comment]
I think it's important for this to be on by default for JuliaPro (as the point is that people might not be aware of advanced features, including commands). And in that case there should really be a command to turn it off, I would've thought (which normal Atom users can also use is if it's convenient for them).

**Comment by pfitzseb** [comment]
I kinda feel like we've been talking past each other a bit ;)

Can you try https://github.com/JunoLab/atom-julia-client/pull/409? What's implemented there seems like a pretty good solution/compromise imho.
