### ISSUE TITLE
Feature request: choose in which folder to open a terminal

### ISSUE THREAD

**Issue by piever** [JunoLab/Juno.jl#98]
in VS Code, when I have multiple projects open (meaning multiple top-level folders) and I open an integrated terminal, I get a dropdown menu (which here would be `Juno.selector` I guess) asking me on which of my top-level folder I want to open the terminal.

I find this feature useful as I switch pretty often from one project to another and I generally need to have the integrated terminal in the correct folder.

If this can be implemented in Juno as well, I think it'd be a nice addition.

**Comment by pfitzseb** [comment]
Implemented on master (together with Terminals remembering their cwd after an Atom restart).
